CURRENT_TURN=9;
OTHER_SAVE_DATA={
  "scale": 0.6868916452474125,
  "canvasOffsetX": -1685.0097415331293,
  "canvasOffsetY": -243.38360728911618,
  "shapeColor": "#930000"
};
USER_RESOURCES={
  "Нейтралы": {},
  "Враги": {},
  "Десант": {},
  "Эл-во": {}
};
OWNER_MAP={};
DEFAULT_DATA=[
  {
    "id": 3,
    "type": "shape",
    "name": "Алтарь_Покоя",
    "shape": "custom",
    "color": "#d3d3d3",
    "x": 1854.84,
    "y": 680.85,
    "width": 80,
    "height": 80,
    "curr_hp": 3,
    "endedTurn": false,
    "disabled": true
  },
  {
    "id": 5,
    "type": "shape",
    "name": "Движетель",
    "shape": "custom",
    "color": "#d3d3d3",
    "x": 4784.91,
    "y": 879.4,
    "width": 80,
    "height": 80,
    "curr_hp": 3,
    "endedTurn": false
  },
  {
    "id": 6,
    "type": "shape",
    "name": "Движетель",
    "shape": "custom",
    "color": "#d3d3d3",
    "x": 4787.28,
    "y": 2082.54,
    "width": 80,
    "height": 80,
    "curr_hp": 3,
    "endedTurn": false
  },
  {
    "id": 7,
    "type": "shape",
    "name": "Цепи_движетеля",
    "shape": "custom",
    "color": "#d3d3d3",
    "x": 4697.56,
    "y": 788.06,
    "width": 60,
    "height": 60,
    "curr_hp": 3,
    "endedTurn": false
  },
  {
    "id": 8,
    "type": "shape",
    "name": "Цепи_движетеля",
    "shape": "custom",
    "color": "#d3d3d3",
    "x": 4593.745457720724,
    "y": 683.3927495639743,
    "width": 60,
    "height": 60,
    "curr_hp": 3,
    "endedTurn": false
  },
  {
    "id": 9,
    "type": "shape",
    "name": "Цепи_движетеля",
    "shape": "custom",
    "color": "#d3d3d3",
    "x": 4794.38,
    "y": 984.62,
    "width": 60,
    "height": 60,
    "curr_hp": 3,
    "endedTurn": false
  },
  {
    "id": 10,
    "type": "shape",
    "name": "Цепи_движетеля",
    "shape": "custom",
    "color": "#d3d3d3",
    "x": 4794.24,
    "y": 1099.53,
    "width": 60,
    "height": 60,
    "curr_hp": 3,
    "endedTurn": false
  },
  {
    "id": 11,
    "type": "shape",
    "name": "Цепи_движетеля",
    "shape": "custom",
    "color": "#d3d3d3",
    "x": 4903.54,
    "y": 792.96,
    "width": 60,
    "height": 60,
    "curr_hp": 3,
    "endedTurn": false
  },
  {
    "id": 12,
    "type": "shape",
    "name": "Цепи_движетеля",
    "shape": "custom",
    "color": "#d3d3d3",
    "x": 5006.66,
    "y": 685.08,
    "width": 60,
    "height": 60,
    "curr_hp": 3,
    "endedTurn": false
  },
  {
    "id": 13,
    "type": "shape",
    "name": "Цепи_движетеля",
    "shape": "custom",
    "color": "#d3d3d3",
    "x": 4791.43,
    "y": 1991.75,
    "width": 60,
    "height": 60,
    "curr_hp": 3,
    "endedTurn": false
  },
  {
    "id": 14,
    "type": "shape",
    "name": "Цепи_движетеля",
    "shape": "custom",
    "color": "#d3d3d3",
    "x": 4795.79,
    "y": 1903.77,
    "width": 60,
    "height": 60,
    "curr_hp": 3,
    "endedTurn": false
  },
  {
    "id": 15,
    "type": "shape",
    "name": "Цепи_движетеля",
    "shape": "custom",
    "color": "#d3d3d3",
    "x": 4902.14,
    "y": 2196.88,
    "width": 60,
    "height": 60,
    "curr_hp": 3,
    "endedTurn": false
  },
  {
    "id": 16,
    "type": "shape",
    "name": "Цепи_движетеля",
    "shape": "custom",
    "color": "#d3d3d3",
    "x": 5000.63,
    "y": 2300.99,
    "width": 60,
    "height": 60,
    "curr_hp": 3,
    "endedTurn": false
  },
  {
    "id": 17,
    "type": "shape",
    "name": "Цепи_движетеля",
    "shape": "custom",
    "color": "#d3d3d3",
    "x": 4696.87,
    "y": 2194.92,
    "width": 60,
    "height": 60,
    "curr_hp": 3,
    "endedTurn": false
  },
  {
    "id": 18,
    "type": "shape",
    "name": "Цепи_движетеля",
    "shape": "custom",
    "color": "#d3d3d3",
    "x": 4604.4,
    "y": 2299.86,
    "width": 60,
    "height": 60,
    "curr_hp": 3,
    "endedTurn": false
  },
  {
    "id": 19,
    "type": "shape",
    "name": "Центр_управления",
    "shape": "custom",
    "color": "#d3d3d3",
    "x": 955.48,
    "y": 1488.01,
    "width": 80,
    "height": 80,
    "curr_hp": 3,
    "endedTurn": false,
    "disabled": true
  },
  {
    "id": 21,
    "type": "shape",
    "name": "Центр_связи",
    "shape": "custom",
    "color": "#d3d3d3",
    "x": 1451.39,
    "y": 779.14,
    "width": 80,
    "height": 80,
    "curr_hp": 3,
    "endedTurn": false,
    "disabled": true
  },
  {
    "id": 31,
    "type": "shape",
    "name": "Пульсар_Душ",
    "shape": "custom",
    "color": "#d3d3d3",
    "x": 1862.55,
    "y": 1691.28,
    "width": 80,
    "height": 80,
    "curr_hp": 3,
    "endedTurn": false,
    "disabled": true
  },
  {
    "id": 34,
    "type": "shape",
    "name": "Чертог_Скрижалей",
    "shape": "custom",
    "color": "#d3d3d3",
    "x": 3779.68,
    "y": 676.24,
    "width": 80,
    "height": 80,
    "curr_hp": 3,
    "endedTurn": false
  },
  {
    "id": 39,
    "type": "shape",
    "name": "Оранжерея",
    "shape": "custom",
    "color": "#930000",
    "x": 2368.12,
    "y": 1181.08,
    "width": 80,
    "height": 80,
    "curr_hp": 3,
    "endedTurn": false
  },
  {
    "id": 43,
    "type": "shape",
    "name": "Обсерватория_Пустоты",
    "shape": "custom",
    "color": "#930000",
    "x": 2871.7,
    "y": 1685.87,
    "width": 80,
    "height": 80,
    "curr_hp": 3,
    "endedTurn": false
  },
  {
    "id": 46,
    "type": "shape",
    "name": "Алтарь_Покоя",
    "shape": "custom",
    "color": "#d3d3d3",
    "x": 3270.84,
    "y": 1584.96,
    "width": 80,
    "height": 80,
    "curr_hp": 3,
    "endedTurn": false
  },
  {
    "id": 47,
    "type": "shape",
    "name": "Кровоточащий_Колодец",
    "shape": "custom",
    "color": "#d3d3d3",
    "x": 3780.64,
    "y": 2288.17,
    "width": 80,
    "height": 80,
    "curr_hp": 3,
    "endedTurn": false
  },
  {
    "id": 63,
    "type": "shape",
    "name": "Пульсар_Душ",
    "shape": "custom",
    "color": "#d3d3d3",
    "x": 3276.27,
    "y": 777.9,
    "width": 80,
    "height": 80,
    "curr_hp": 3,
    "endedTurn": false
  },
  {
    "id": 67,
    "type": "shape",
    "name": "Портальный_чертог",
    "shape": "custom",
    "color": "#d3d3d3",
    "x": 2867.66,
    "y": 1183.39,
    "width": 80,
    "height": 80,
    "curr_hp": 3,
    "endedTurn": false
  },
  {
    "id": 68,
    "type": "shape",
    "name": "Звёздная_Арка",
    "shape": "custom",
    "color": "#d3d3d3",
    "x": 2776.48,
    "y": 992.51,
    "width": 60,
    "height": 60,
    "curr_hp": 3,
    "endedTurn": false
  },
  {
    "id": 69,
    "type": "shape",
    "name": "Звёздная_Арка",
    "shape": "custom",
    "color": "#d3d3d3",
    "x": 2983.37,
    "y": 993.04,
    "width": 60,
    "height": 60,
    "curr_hp": 3,
    "endedTurn": false
  },
  {
    "id": 70,
    "type": "shape",
    "name": "Звёздная_Арка",
    "shape": "custom",
    "color": "#d3d3d3",
    "x": 2789.52,
    "y": 1395.47,
    "width": 60,
    "height": 60,
    "curr_hp": 3,
    "endedTurn": false
  },
  {
    "id": 74,
    "type": "shape",
    "name": "Звёздная_Арка",
    "shape": "custom",
    "color": "#d3d3d3",
    "x": 1981.15,
    "y": 1806.51,
    "width": 60,
    "height": 60,
    "curr_hp": 3,
    "endedTurn": false
  },
  {
    "id": 75,
    "type": "shape",
    "name": "Звёздная_Арка",
    "shape": "custom",
    "color": "#d3d3d3",
    "x": 3170.74,
    "y": 683.36,
    "width": 60,
    "height": 60,
    "curr_hp": 3,
    "endedTurn": false
  },
  {
    "id": 77,
    "type": "shape",
    "name": "Звёздная_Арка",
    "shape": "custom",
    "color": "#d3d3d3",
    "x": 3592.59,
    "y": 2200.6,
    "width": 60,
    "height": 60,
    "curr_hp": 3,
    "endedTurn": false
  },
  {
    "id": 79,
    "type": "shape",
    "name": "Целительная",
    "shape": "custom",
    "color": "#930000",
    "x": 2865.6,
    "y": 675.26,
    "width": 80,
    "height": 80,
    "curr_hp": 3,
    "endedTurn": false,
    "disabled": true
  },
  {
    "id": 80,
    "type": "shape",
    "name": "Карта_корабля",
    "shape": "custom",
    "color": "#d3d3d3",
    "x": 1063.75,
    "y": 1498.07,
    "width": 60,
    "height": 60,
    "curr_hp": 3,
    "endedTurn": false
  },
  {
    "id": 81,
    "type": "shape",
    "name": "Скрижаль",
    "shape": "custom",
    "color": "#d3d3d3",
    "x": 3566.41,
    "y": 577.41,
    "width": 60,
    "height": 60,
    "curr_hp": 3,
    "endedTurn": false
  },
  {
    "id": 82,
    "type": "shape",
    "name": "Скрижаль",
    "shape": "custom",
    "color": "#d3d3d3",
    "x": 3671.75,
    "y": 581.56,
    "width": 60,
    "height": 60,
    "curr_hp": 3,
    "endedTurn": false
  },
  {
    "id": 83,
    "type": "shape",
    "name": "Скрижаль",
    "shape": "custom",
    "color": "#d3d3d3",
    "x": 3862.49,
    "y": 571.92,
    "width": 60,
    "height": 60,
    "curr_hp": 3,
    "endedTurn": false
  },
  {
    "id": 85,
    "type": "shape",
    "name": "Скрижаль",
    "shape": "custom",
    "color": "#d3d3d3",
    "x": 3773.01,
    "y": 576.65,
    "width": 60,
    "height": 60,
    "curr_hp": 3,
    "endedTurn": false
  },
  {
    "id": 86,
    "type": "shape",
    "name": "Скрижаль",
    "shape": "custom",
    "color": "#d3d3d3",
    "x": 2765.57,
    "y": 800.31,
    "width": 60,
    "height": 60,
    "curr_hp": 3,
    "endedTurn": false
  },
  {
    "id": 87,
    "type": "shape",
    "name": "Скрижаль",
    "shape": "custom",
    "color": "#d3d3d3",
    "x": 4584.29,
    "y": 1895.97,
    "width": 60,
    "height": 60,
    "curr_hp": 3,
    "endedTurn": false
  },
  {
    "id": 88,
    "type": "shape",
    "name": "Звёздная_Арка",
    "shape": "custom",
    "color": "#d3d3d3",
    "x": 4597.23,
    "y": 787.73,
    "width": 60,
    "height": 60,
    "curr_hp": 3,
    "endedTurn": false
  },
  {
    "id": 89,
    "type": "shape",
    "name": "Звёздная_Арка",
    "shape": "custom",
    "color": "#d3d3d3",
    "x": 2984.67,
    "y": 1397.54,
    "width": 60,
    "height": 60,
    "curr_hp": 3,
    "endedTurn": false
  },
  {
    "id": 90,
    "type": "shape",
    "name": "Жилая_секция",
    "shape": "custom",
    "color": "#d3d3d3",
    "x": 1855.14,
    "y": 1190.32,
    "width": 80,
    "height": 80,
    "curr_hp": 3,
    "endedTurn": false,
    "disabled": true
  },
  {
    "id": 93,
    "type": "shape",
    "name": "Кровать",
    "shape": "custom",
    "color": "#d3d3d3",
    "x": 1757.7,
    "y": 1406.66,
    "width": 60,
    "height": 60,
    "curr_hp": 3,
    "endedTurn": false
  },
  {
    "id": 94,
    "type": "shape",
    "name": "Кровать",
    "shape": "custom",
    "color": "#d3d3d3",
    "x": 1757.7,
    "y": 1301.43,
    "width": 60,
    "height": 60,
    "curr_hp": 3,
    "endedTurn": false
  },
  {
    "id": 95,
    "type": "shape",
    "name": "Кровать",
    "shape": "custom",
    "color": "#d3d3d3",
    "x": 1760.26,
    "y": 1105.08,
    "width": 60,
    "height": 60,
    "curr_hp": 3,
    "endedTurn": false
  },
  {
    "id": 96,
    "type": "shape",
    "name": "Кровать",
    "shape": "custom",
    "color": "#d3d3d3",
    "x": 1762.83,
    "y": 1007.55,
    "width": 60,
    "height": 60,
    "curr_hp": 3,
    "endedTurn": false
  },
  {
    "id": 97,
    "type": "shape",
    "name": "Кровать",
    "shape": "custom",
    "color": "#d3d3d3",
    "x": 1991.26,
    "y": 1012.68,
    "width": 60,
    "height": 60,
    "curr_hp": 3,
    "endedTurn": false
  },
  {
    "id": 98,
    "type": "shape",
    "name": "Кровать",
    "shape": "custom",
    "color": "#d3d3d3",
    "x": 1989.98,
    "y": 1103.8,
    "width": 60,
    "height": 60,
    "curr_hp": 3,
    "endedTurn": false
  },
  {
    "id": 99,
    "type": "shape",
    "name": "Кровать",
    "shape": "custom",
    "color": "#d3d3d3",
    "x": 1987.41,
    "y": 1305.28,
    "width": 60,
    "height": 60,
    "curr_hp": 3,
    "endedTurn": false
  },
  {
    "id": 100,
    "type": "shape",
    "name": "Кровать",
    "shape": "custom",
    "color": "#d3d3d3",
    "x": 1987.41,
    "y": 1402.81,
    "width": 60,
    "height": 60,
    "curr_hp": 3,
    "endedTurn": false
  },
  {
    "id": 101,
    "type": "shape",
    "name": "Кровать",
    "shape": "custom",
    "color": "#d3d3d3",
    "x": 2863.31,
    "y": 603.31,
    "width": 60,
    "height": 60,
    "curr_hp": 3,
    "endedTurn": false
  },
  {
    "id": 102,
    "type": "shape",
    "name": "Кровать",
    "shape": "custom",
    "color": "#d3d3d3",
    "x": 2964.16,
    "y": 606.25,
    "width": 60,
    "height": 60,
    "curr_hp": 3,
    "endedTurn": false
  },
  {
    "id": 103,
    "type": "shape",
    "name": "Скрижаль",
    "shape": "custom",
    "color": "#d3d3d3",
    "x": 837.4,
    "y": 1609.05,
    "width": 60,
    "height": 60,
    "curr_hp": 3,
    "endedTurn": false
  },
  {
    "id": 104,
    "type": "shape",
    "name": "Кровать",
    "shape": "custom",
    "color": "#d3d3d3",
    "x": 2765.64,
    "y": 601.88,
    "width": 60,
    "height": 60,
    "curr_hp": 3,
    "endedTurn": false
  },
  {
    "id": 115,
    "type": "shape",
    "name": "Звёздная_Арка",
    "shape": "custom",
    "color": "#d3d3d3",
    "x": 4599.79,
    "y": 2199.31,
    "width": 60,
    "height": 60,
    "curr_hp": 3,
    "endedTurn": false
  },
  {
    "id": 116,
    "type": "shape",
    "name": "Созерцатель",
    "shape": "custom",
    "color": "#d3d3d3",
    "x": 1847.07,
    "y": 1074.84,
    "width": 60,
    "height": 60,
    "curr_hp": 3,
    "endedTurn": false,
    "title": "Связь1"
  },
  {
    "id": 117,
    "type": "shape",
    "name": "Пси-клинок",
    "shape": "custom",
    "color": "#d3d3d3",
    "x": 880.31,
    "y": 1472,
    "width": 60,
    "height": 60,
    "curr_hp": 1,
    "endedTurn": false,
    "title": "Капитан"
  },
  {
    "id": 118,
    "type": "shape",
    "name": "Хранитель",
    "shape": "custom",
    "color": "#d3d3d3",
    "x": 1052.62,
    "y": 1387.14,
    "width": 60,
    "height": 60,
    "curr_hp": 3,
    "endedTurn": false,
    "title": "Начтех"
  },
  {
    "id": 119,
    "type": "shape",
    "name": "_могила",
    "shape": "custom",
    "color": "#930000",
    "x": 1066.39,
    "y": 1703.44,
    "width": 60,
    "height": 60,
    "curr_hp": 0,
    "endedTurn": false,
    "title": "Навигатор",
    "src": ""
  },
  {
    "id": 121,
    "type": "shape",
    "name": "Звёздный_зомби",
    "shape": "custom",
    "color": "#930000",
    "x": 3759.68,
    "y": 916.91,
    "width": 60,
    "height": 60,
    "curr_hp": 0,
    "endedTurn": true,
    "title": "Двиг1",
    "src": ""
  },
  {
    "id": 122,
    "type": "shape",
    "name": "Хранитель",
    "shape": "custom",
    "color": "#d3d3d3",
    "x": 3610.56,
    "y": 810.47,
    "width": 60,
    "height": 60,
    "curr_hp": 3,
    "endedTurn": false,
    "title": "Наука"
  },
  {
    "id": 123,
    "type": "shape",
    "name": "Хранитель",
    "shape": "custom",
    "color": "#d3d3d3",
    "x": 1962.75,
    "y": 1668.36,
    "width": 60,
    "height": 60,
    "curr_hp": 3,
    "endedTurn": false,
    "title": "Инж1"
  },
  {
    "id": 124,
    "type": "shape",
    "name": "Кровотворец",
    "shape": "custom",
    "color": "#d3d3d3",
    "x": 1950.47,
    "y": 675.52,
    "width": 60,
    "height": 60,
    "curr_hp": 3,
    "endedTurn": false,
    "title": "Свящ1"
  },
  {
    "id": 125,
    "type": "shape",
    "name": "Звёздный_зомби",
    "shape": "custom",
    "color": "#930000",
    "x": 3092.67,
    "y": 1080.03,
    "width": 60,
    "height": 60,
    "curr_hp": 0,
    "endedTurn": true,
    "title": "Свящ2",
    "src": ""
  },
  {
    "id": 126,
    "type": "shape",
    "name": "Звёздный_зомби",
    "shape": "custom",
    "color": "#930000",
    "x": 3810.27,
    "y": 1076.61,
    "width": 60,
    "height": 60,
    "curr_hp": 0,
    "endedTurn": true,
    "title": "Инж2",
    "src": ""
  },
  {
    "id": 127,
    "type": "shape",
    "name": "Созерцатель",
    "shape": "custom",
    "color": "#d3d3d3",
    "x": 1436.46,
    "y": 859.01,
    "width": 60,
    "height": 60,
    "curr_hp": 3,
    "endedTurn": false,
    "title": "Связь2"
  },
  {
    "id": 128,
    "type": "shape",
    "name": "Око_Аннигиляции",
    "shape": "custom",
    "color": "#930000",
    "x": 2954.1,
    "y": 1670.56,
    "width": 60,
    "height": 60,
    "curr_hp": 3,
    "endedTurn": false,
    "title": "Астроном",
    "src": ""
  },
  {
    "id": 130,
    "type": "shape",
    "name": "Кровотворец",
    "shape": "custom",
    "color": "#d3d3d3",
    "x": 961.27,
    "y": 1395.23,
    "width": 60,
    "height": 60,
    "curr_hp": 3,
    "endedTurn": false,
    "title": "Старпом",
    "src": ""
  },
  {
    "id": 131,
    "type": "shape",
    "name": "Кристалл_души",
    "shape": "custom",
    "color": "#d3d3d3",
    "x": 3611.93,
    "y": 1896.47,
    "width": 60,
    "height": 60,
    "curr_hp": 3,
    "endedTurn": false,
    "src": ""
  },
  {
    "id": 132,
    "type": "shape",
    "name": "Обзор",
    "shape": "custom",
    "color": "#d3d3d3",
    "x": 3999.78,
    "y": 2287.18,
    "width": 60,
    "height": 60,
    "curr_hp": 3,
    "endedTurn": false
  },
  {
    "id": 133,
    "type": "shape",
    "name": "Кристалл_души",
    "shape": "custom",
    "color": "#d3d3d3",
    "x": 4079.19,
    "y": 1276.16,
    "width": 60,
    "height": 60,
    "curr_hp": 3,
    "endedTurn": false,
    "src": ""
  },
  {
    "id": 134,
    "type": "shape",
    "name": "Кристалл_души",
    "shape": "custom",
    "color": "#d3d3d3",
    "x": 3764.1,
    "y": 1078.56,
    "width": 60,
    "height": 60,
    "curr_hp": 3,
    "endedTurn": false,
    "src": ""
  },
  {
    "id": 135,
    "type": "shape",
    "name": "Кристалл_души",
    "shape": "custom",
    "color": "#d3d3d3",
    "x": 4272.06,
    "y": 906.06,
    "width": 60,
    "height": 60,
    "curr_hp": 3,
    "endedTurn": false,
    "src": ""
  },
  {
    "id": 136,
    "type": "shape",
    "name": "Кристалл_души",
    "shape": "custom",
    "color": "#d3d3d3",
    "x": 4474.76,
    "y": 1272.36,
    "width": 60,
    "height": 60,
    "curr_hp": 3,
    "endedTurn": false,
    "src": ""
  },
  {
    "id": 137,
    "type": "shape",
    "name": "Кристалл_души",
    "shape": "custom",
    "color": "#d3d3d3",
    "x": 4073.41,
    "y": 1684.49,
    "width": 60,
    "height": 60,
    "curr_hp": 3,
    "endedTurn": false,
    "src": ""
  },
  {
    "id": 138,
    "type": "shape",
    "name": "Кристалл_души",
    "shape": "custom",
    "color": "#d3d3d3",
    "x": 3671.46,
    "y": 1269.98,
    "width": 60,
    "height": 60,
    "curr_hp": 3,
    "endedTurn": false,
    "src": ""
  },
  {
    "id": 139,
    "type": "shape",
    "name": "Кристалл_души",
    "shape": "custom",
    "color": "#d3d3d3",
    "x": 3266.01,
    "y": 1276.16,
    "width": 60,
    "height": 60,
    "curr_hp": 3,
    "endedTurn": false,
    "src": ""
  },
  {
    "id": 140,
    "type": "shape",
    "name": "Кристалл_души",
    "shape": "custom",
    "color": "#d3d3d3",
    "x": 3265.15,
    "y": 1076.38,
    "width": 60,
    "height": 60,
    "curr_hp": 3,
    "endedTurn": false,
    "src": ""
  },
  {
    "id": 141,
    "type": "shape",
    "name": "Обзор",
    "shape": "custom",
    "color": "#d3d3d3",
    "x": 3202.11,
    "y": 1889.6,
    "width": 60,
    "height": 60,
    "curr_hp": 3,
    "endedTurn": false
  },
  {
    "id": 142,
    "type": "shape",
    "name": "Обзор",
    "shape": "custom",
    "color": "#d3d3d3",
    "x": 3206.53,
    "y": 2099.62,
    "width": 60,
    "height": 60,
    "curr_hp": 3,
    "endedTurn": false
  },
  {
    "id": 143,
    "type": "shape",
    "name": "Кристалл_души",
    "shape": "custom",
    "color": "#d3d3d3",
    "x": 4263.3,
    "y": 2081.94,
    "width": 60,
    "height": 60,
    "curr_hp": 3,
    "endedTurn": false,
    "src": ""
  },
  {
    "id": 144,
    "type": "shape",
    "name": "Обзор",
    "shape": "custom",
    "color": "#d3d3d3",
    "x": 4569.19,
    "y": 1985.06,
    "width": 60,
    "height": 60,
    "curr_hp": 3,
    "endedTurn": false
  },
  {
    "id": 146,
    "type": "shape",
    "name": "Кристалл_души",
    "shape": "custom",
    "color": "#d3d3d3",
    "x": 4579.44,
    "y": 974.33,
    "width": 60,
    "height": 60,
    "curr_hp": 3,
    "endedTurn": false,
    "src": ""
  },
  {
    "id": 147,
    "type": "shape",
    "name": "Кристалл_души",
    "shape": "custom",
    "color": "#d3d3d3",
    "x": 2360.32,
    "y": 1062.85,
    "width": 60,
    "height": 60,
    "curr_hp": 3,
    "endedTurn": false,
    "src": ""
  },
  {
    "id": 148,
    "type": "shape",
    "name": "Обзор",
    "shape": "custom",
    "color": "#d3d3d3",
    "x": 1546.63,
    "y": 1175.34,
    "width": 60,
    "height": 60,
    "curr_hp": 3,
    "endedTurn": false
  },
  {
    "id": 150,
    "type": "shape",
    "name": "Кристалл_души",
    "shape": "custom",
    "color": "#d3d3d3",
    "x": 1249.48,
    "y": 1480.71,
    "width": 60,
    "height": 60,
    "curr_hp": 0,
    "endedTurn": false,
    "src": ""
  },
  {
    "id": 151,
    "type": "shape",
    "name": "Кристалл_души",
    "shape": "custom",
    "color": "#d3d3d3",
    "x": 1541.59,
    "y": 1769.08,
    "width": 60,
    "height": 60,
    "curr_hp": 3,
    "endedTurn": false,
    "src": ""
  },
  {
    "id": 152,
    "type": "shape",
    "name": "Кристалл_души",
    "shape": "custom",
    "color": "#d3d3d3",
    "x": 1039.58,
    "y": 1777.89,
    "width": 60,
    "height": 60,
    "curr_hp": 3,
    "endedTurn": false,
    "src": ""
  },
  {
    "id": 153,
    "type": "shape",
    "name": "Обзор",
    "shape": "custom",
    "color": "#d3d3d3",
    "x": 2372.38,
    "y": 1391.85,
    "width": 60,
    "height": 60,
    "curr_hp": 3,
    "endedTurn": false
  },
  {
    "id": 154,
    "type": "shape",
    "name": "Кровать",
    "shape": "custom",
    "color": "#d3d3d3",
    "x": 3364.51,
    "y": 1914.56,
    "width": 60,
    "height": 60,
    "curr_hp": 3,
    "endedTurn": false
  },
  {
    "id": 155,
    "type": "shape",
    "name": "Кровать",
    "shape": "custom",
    "color": "#d3d3d3",
    "x": 3266.95,
    "y": 1916.6,
    "width": 60,
    "height": 60,
    "curr_hp": 3,
    "endedTurn": false
  },
  {
    "id": 156,
    "type": "shape",
    "name": "Кровать",
    "shape": "custom",
    "color": "#d3d3d3",
    "x": 3359.47,
    "y": 1114.07,
    "width": 60,
    "height": 60,
    "curr_hp": 3,
    "endedTurn": false
  },
  {
    "id": 157,
    "type": "shape",
    "name": "Кровать",
    "shape": "custom",
    "color": "#d3d3d3",
    "x": 3461.27,
    "y": 1117.66,
    "width": 60,
    "height": 60,
    "curr_hp": 3,
    "endedTurn": false
  },
  {
    "id": 158,
    "type": "shape",
    "name": "Хранитель",
    "shape": "custom",
    "color": "#d3d3d3",
    "x": 4783.53,
    "y": 2166.6,
    "width": 60,
    "height": 60,
    "curr_hp": 3,
    "endedTurn": false,
    "title": "ГлавДвиг"
  },
  {
    "id": 159,
    "type": "shape",
    "name": "Хранитель",
    "shape": "custom",
    "color": "#d3d3d3",
    "x": 4780.94,
    "y": 774.64,
    "width": 60,
    "height": 60,
    "curr_hp": 3,
    "endedTurn": false,
    "title": "Двиг2"
  },
  {
    "id": 160,
    "type": "shape",
    "name": "Звёздный_зомби",
    "shape": "custom",
    "color": "#930000",
    "x": 2100.88,
    "y": 1206.55,
    "width": 60,
    "height": 60,
    "curr_hp": 0,
    "endedTurn": true,
    "title": "Биомант",
    "src": ""
  },
  {
    "id": 161,
    "type": "shape",
    "name": "Кровотворец",
    "shape": "custom",
    "color": "#d3d3d3",
    "x": 3356.12,
    "y": 1566.83,
    "width": 60,
    "height": 60,
    "curr_hp": 3,
    "endedTurn": false,
    "title": "Кровь"
  },
  {
    "id": 162,
    "type": "shape",
    "name": "Кровать",
    "shape": "custom",
    "color": "#d3d3d3",
    "x": 3560.47,
    "y": 1114.89,
    "width": 60,
    "height": 60,
    "curr_hp": 3,
    "endedTurn": false
  },
  {
    "id": 163,
    "type": "shape",
    "name": "Кровать",
    "shape": "custom",
    "color": "#d3d3d3",
    "x": 3466.95,
    "y": 1917.25,
    "width": 60,
    "height": 60,
    "curr_hp": 3,
    "endedTurn": false
  },
  {
    "id": 164,
    "type": "shape",
    "name": "Контрольное_кресло",
    "shape": "custom",
    "color": "#d3d3d3",
    "x": 897.38,
    "y": 1517.59,
    "width": 60,
    "height": 60,
    "curr_hp": 3,
    "endedTurn": false,
    "title": "Капитан"
  },
  {
    "id": 165,
    "type": "shape",
    "name": "Контрольное_кресло",
    "shape": "custom",
    "color": "#d3d3d3",
    "x": 983.58,
    "y": 1409.76,
    "width": 60,
    "height": 60,
    "curr_hp": 3,
    "endedTurn": false,
    "title": "Старпом"
  },
  {
    "id": 166,
    "type": "shape",
    "name": "Контрольное_кресло",
    "shape": "custom",
    "color": "#d3d3d3",
    "x": 1078.78,
    "y": 1405.99,
    "width": 60,
    "height": 60,
    "curr_hp": 3,
    "endedTurn": false,
    "title": "Начтех"
  },
  {
    "id": 167,
    "type": "shape",
    "name": "Контрольное_кресло",
    "shape": "custom",
    "color": "#d3d3d3",
    "x": 979.46,
    "y": 1606.97,
    "width": 60,
    "height": 60,
    "curr_hp": 3,
    "endedTurn": false,
    "title": "Навигатор"
  },
  {
    "id": 168,
    "type": "shape",
    "name": "Контрольное_кресло",
    "shape": "custom",
    "color": "#d3d3d3",
    "x": 1983.9,
    "y": 1710.57,
    "width": 60,
    "height": 60,
    "curr_hp": 3,
    "endedTurn": false,
    "title": "Контроль"
  },
  {
    "id": 169,
    "type": "shape",
    "name": "Контрольное_кресло",
    "shape": "custom",
    "color": "#d3d3d3",
    "x": 1987.15,
    "y": 698.37,
    "width": 60,
    "height": 60,
    "curr_hp": 3,
    "endedTurn": false,
    "title": "Контроль"
  },
  {
    "id": 170,
    "type": "shape",
    "name": "Контрольное_кресло",
    "shape": "custom",
    "color": "#d3d3d3",
    "x": 1487.51,
    "y": 704.23,
    "width": 60,
    "height": 60,
    "curr_hp": 3,
    "endedTurn": false
  },
  {
    "id": 171,
    "type": "shape",
    "name": "Контрольное_кресло",
    "shape": "custom",
    "color": "#d3d3d3",
    "x": 1484.99,
    "y": 902.82,
    "width": 60,
    "height": 60,
    "curr_hp": 3,
    "endedTurn": false
  },
  {
    "id": 172,
    "type": "shape",
    "name": "Контрольное_кресло",
    "shape": "custom",
    "color": "#d3d3d3",
    "x": 1995.03,
    "y": 608.6,
    "width": 60,
    "height": 60,
    "curr_hp": 3,
    "endedTurn": false
  },
  {
    "id": 173,
    "type": "shape",
    "name": "Контрольное_кресло",
    "shape": "custom",
    "color": "#d3d3d3",
    "x": 3402.14,
    "y": 1605.83,
    "width": 60,
    "height": 60,
    "curr_hp": 3,
    "endedTurn": false,
    "title": "Контроль"
  },
  {
    "id": 174,
    "type": "shape",
    "name": "Контрольное_кресло",
    "shape": "custom",
    "color": "#d3d3d3",
    "x": 3398.73,
    "y": 1712.41,
    "width": 60,
    "height": 60,
    "curr_hp": 3,
    "endedTurn": false
  },
  {
    "id": 175,
    "type": "shape",
    "name": "Контрольное_кресло",
    "shape": "custom",
    "color": "#d3d3d3",
    "x": 2992.82,
    "y": 1202.62,
    "width": 60,
    "height": 60,
    "curr_hp": 3,
    "endedTurn": false,
    "title": "Контроль"
  },
  {
    "id": 176,
    "type": "shape",
    "name": "Контрольное_кресло",
    "shape": "custom",
    "color": "#d3d3d3",
    "x": 2391.59,
    "y": 1306.02,
    "width": 60,
    "height": 60,
    "curr_hp": 3,
    "endedTurn": false,
    "title": "Биомант"
  },
  {
    "id": 177,
    "type": "shape",
    "name": "Контрольное_кресло",
    "shape": "custom",
    "color": "#d3d3d3",
    "x": 2991.96,
    "y": 1714.01,
    "width": 60,
    "height": 60,
    "curr_hp": 3,
    "endedTurn": false,
    "title": "Астроном"
  },
  {
    "id": 178,
    "type": "shape",
    "name": "Контрольное_кресло",
    "shape": "custom",
    "color": "#d3d3d3",
    "x": 2796.64,
    "y": 1711.68,
    "width": 60,
    "height": 60,
    "curr_hp": 3,
    "endedTurn": false
  },
  {
    "id": 179,
    "type": "shape",
    "name": "Контрольное_кресло",
    "shape": "custom",
    "color": "#d3d3d3",
    "x": 2991.46,
    "y": 700.38,
    "width": 60,
    "height": 60,
    "curr_hp": 3,
    "endedTurn": false,
    "title": "Контроль"
  },
  {
    "id": 180,
    "type": "shape",
    "name": "Контрольное_кресло",
    "shape": "custom",
    "color": "#d3d3d3",
    "x": 3398.38,
    "y": 802.11,
    "width": 60,
    "height": 60,
    "curr_hp": 3,
    "endedTurn": false,
    "title": "Контроль"
  },
  {
    "id": 181,
    "type": "shape",
    "name": "Контрольное_кресло",
    "shape": "custom",
    "color": "#d3d3d3",
    "x": 4816.01,
    "y": 805.35,
    "width": 60,
    "height": 60,
    "curr_hp": 3,
    "endedTurn": false,
    "title": "Главный"
  },
  {
    "id": 182,
    "type": "shape",
    "name": "Контрольное_кресло",
    "shape": "custom",
    "color": "#d3d3d3",
    "x": 4711.85,
    "y": 1102.04,
    "width": 60,
    "height": 60,
    "curr_hp": 3,
    "endedTurn": false,
    "title": "Резервный"
  },
  {
    "id": 183,
    "type": "shape",
    "name": "Контрольное_кресло",
    "shape": "custom",
    "color": "#d3d3d3",
    "x": 4815.96,
    "y": 2202.55,
    "width": 60,
    "height": 60,
    "curr_hp": 3,
    "endedTurn": false,
    "title": "Главный"
  },
  {
    "id": 184,
    "type": "shape",
    "name": "Контрольное_кресло",
    "shape": "custom",
    "color": "#d3d3d3",
    "x": 4715.38,
    "y": 1915.35,
    "width": 60,
    "height": 60,
    "curr_hp": 3,
    "endedTurn": false,
    "title": "Резервный"
  },
  {
    "id": 186,
    "type": "shape",
    "name": "Контрольное_кресло",
    "shape": "custom",
    "color": "#d3d3d3",
    "x": 3810.46,
    "y": 2216.46,
    "width": 60,
    "height": 60,
    "curr_hp": 3,
    "endedTurn": false,
    "title": "Контроль"
  },
  {
    "id": 187,
    "type": "shape",
    "name": "Контрольное_кресло",
    "shape": "custom",
    "color": "#d3d3d3",
    "x": 3803.22,
    "y": 803.18,
    "width": 60,
    "height": 60,
    "curr_hp": 3,
    "endedTurn": false,
    "title": "Контроль"
  },
  {
    "id": 188,
    "type": "shape",
    "name": "Контур_ответчик",
    "shape": "custom",
    "color": "#d3d3d3",
    "x": 1361.45,
    "y": 788.87,
    "width": 60,
    "height": 60,
    "curr_hp": 3,
    "endedTurn": false
  },
  {
    "id": 189,
    "type": "shape",
    "name": "Кровь_колодца",
    "shape": "custom",
    "color": "#d3d3d3",
    "x": 3887.6,
    "y": 2202.6,
    "width": 60,
    "height": 60,
    "curr_hp": 3,
    "endedTurn": false
  },
  {
    "id": 190,
    "type": "shape",
    "name": "Кровь_колодца",
    "shape": "custom",
    "color": "#d3d3d3",
    "x": 3685.49,
    "y": 2202.6,
    "width": 60,
    "height": 60,
    "curr_hp": 3,
    "endedTurn": false
  },
  {
    "id": 191,
    "type": "shape",
    "name": "Кровь_колодца",
    "shape": "custom",
    "color": "#d3d3d3",
    "x": 3884.71,
    "y": 2298.84,
    "width": 60,
    "height": 60,
    "curr_hp": 3,
    "endedTurn": false
  },
  {
    "id": 192,
    "type": "shape",
    "name": "Кровь_колодца",
    "shape": "custom",
    "color": "#d3d3d3",
    "x": 3684.53,
    "y": 2300.77,
    "width": 60,
    "height": 60,
    "curr_hp": 3,
    "endedTurn": false
  },
  {
    "id": 193,
    "type": "shape",
    "name": "Кровь_колодца",
    "shape": "custom",
    "color": "#d3d3d3",
    "x": 3688.38,
    "y": 2402.78,
    "width": 60,
    "height": 60,
    "curr_hp": 3,
    "endedTurn": false
  },
  {
    "id": 194,
    "type": "shape",
    "name": "Кровь_колодца",
    "shape": "custom",
    "color": "#d3d3d3",
    "x": 3787.5085798984846,
    "y": 2399.8957015353426,
    "width": 60,
    "height": 60,
    "curr_hp": 3,
    "endedTurn": false
  },
  {
    "id": 195,
    "type": "shape",
    "name": "Кровь_колодца",
    "shape": "custom",
    "color": "#d3d3d3",
    "x": 3887.6,
    "y": 2398.93,
    "width": 60,
    "height": 60,
    "curr_hp": 3,
    "endedTurn": false
  },
  {
    "id": 196,
    "type": "shape",
    "name": "Скрижаль",
    "shape": "custom",
    "color": "#d3d3d3",
    "x": 4571.4,
    "y": 1025.9,
    "width": 60,
    "height": 60,
    "curr_hp": 3,
    "endedTurn": false
  },
  {
    "id": 197,
    "type": "shape",
    "name": "Душевидец",
    "shape": "custom",
    "color": "#d3d3d3",
    "x": 4009.08,
    "y": 706.15,
    "width": 60,
    "height": 60,
    "curr_hp": 3,
    "endedTurn": false
  },
  {
    "id": 198,
    "type": "shape",
    "name": "Контрольное_кресло",
    "shape": "custom",
    "color": "#d3d3d3",
    "x": 4006.19,
    "y": 801.15,
    "width": 60,
    "height": 60,
    "curr_hp": 3,
    "endedTurn": false,
    "title": "Душевидец"
  },
  {
    "id": 200,
    "type": "shape",
    "name": "Кристалл_души",
    "shape": "custom",
    "color": "#d3d3d3",
    "x": 3573.9,
    "y": 872.88,
    "width": 60,
    "height": 60,
    "curr_hp": 3,
    "endedTurn": false,
    "src": ""
  },
  {
    "id": 201,
    "type": "shape",
    "name": "Кристалл_души",
    "shape": "custom",
    "color": "#d3d3d3",
    "x": 1746.34,
    "y": 1674.53,
    "width": 60,
    "height": 60,
    "curr_hp": 3,
    "endedTurn": false,
    "src": ""
  },
  {
    "id": 202,
    "type": "shape",
    "name": "Кристалл_души",
    "shape": "custom",
    "color": "#d3d3d3",
    "x": 3159.78,
    "y": 761.25,
    "width": 60,
    "height": 60,
    "curr_hp": 3,
    "endedTurn": false,
    "src": ""
  },
  {
    "id": 204,
    "type": "shape",
    "name": "Кровать",
    "shape": "custom",
    "color": "#d3d3d3",
    "x": 1256.65,
    "y": 1816.11,
    "width": 60,
    "height": 60,
    "curr_hp": 3,
    "endedTurn": false
  },
  {
    "id": 205,
    "type": "shape",
    "name": "Кровать",
    "shape": "custom",
    "color": "#d3d3d3",
    "x": 1354.83,
    "y": 1812.18,
    "width": 60,
    "height": 60,
    "curr_hp": 3,
    "endedTurn": false
  },
  {
    "id": 206,
    "type": "shape",
    "name": "Кровать",
    "shape": "custom",
    "color": "#d3d3d3",
    "x": 1445.55,
    "y": 1816.18,
    "width": 60,
    "height": 60,
    "curr_hp": 3,
    "endedTurn": false
  },
  {
    "id": 207,
    "type": "shape",
    "name": "Контрольное_кресло",
    "shape": "custom",
    "color": "#d3d3d3",
    "x": 2996.6,
    "y": 1313.19,
    "width": 60,
    "height": 60,
    "curr_hp": 3,
    "endedTurn": false
  },
  {
    "id": 208,
    "type": "shape",
    "name": "Контрольное_кресло",
    "shape": "custom",
    "color": "#d3d3d3",
    "x": 2797.27,
    "y": 1112.65,
    "width": 60,
    "height": 60,
    "curr_hp": 3,
    "endedTurn": false
  },
  {
    "id": 209,
    "type": "shape",
    "name": "Звёздный_зомби",
    "shape": "custom",
    "color": "#930000",
    "x": 3805.08,
    "y": 871.18,
    "width": 60,
    "height": 60,
    "src": "",
    "curr_hp": 0,
    "endedTurn": true,
    "title": "Штурм2"
  },
  {
    "id": 210,
    "type": "shape",
    "name": "Пси-клинок",
    "shape": "custom",
    "color": "#d3d3d3",
    "x": 1034.74,
    "y": 1730.04,
    "width": 60,
    "height": 60,
    "curr_hp": 3,
    "endedTurn": false,
    "title": "НачБез"
  },
  {
    "id": 211,
    "type": "shape",
    "name": "Звёздный_зомби",
    "shape": "custom",
    "color": "#930000",
    "x": 3200.58,
    "y": 1329.59,
    "width": 60,
    "height": 60,
    "curr_hp": 3,
    "endedTurn": true,
    "title": "Штурм3",
    "src": ""
  },
  {
    "id": 212,
    "type": "shape",
    "name": "Контрольное_кресло",
    "shape": "custom",
    "color": "#d3d3d3",
    "x": 2807.4,
    "y": 1311.89,
    "width": 60,
    "height": 60,
    "curr_hp": 3,
    "endedTurn": false
  },
  {
    "id": 213,
    "type": "shape",
    "name": "Кровать",
    "shape": "custom",
    "color": "#d3d3d3",
    "x": 3662.67,
    "y": 1112.37,
    "width": 60,
    "height": 60,
    "curr_hp": 3,
    "endedTurn": false
  },
  {
    "id": 214,
    "type": "shape",
    "name": "Контрольное_кресло",
    "shape": "custom",
    "color": "#d3d3d3",
    "x": 1087.2,
    "y": 1604.76,
    "width": 60,
    "height": 60,
    "curr_hp": 3,
    "endedTurn": false,
    "title": "НачБез"
  },
  {
    "id": 215,
    "type": "shape",
    "name": "Пси-клинок",
    "shape": "custom",
    "color": "#d3d3d3",
    "x": 1101.36,
    "y": 1666.78,
    "width": 60,
    "height": 60,
    "curr_hp": 3,
    "endedTurn": false,
    "title": "Штурм1"
  },
  {
    "id": 216,
    "type": "shape",
    "name": "Пси-клинок",
    "shape": "custom",
    "color": "#d3d3d3",
    "x": 1904.99,
    "y": 1165.51,
    "width": 60,
    "height": 60,
    "curr_hp": 3,
    "endedTurn": false,
    "title": "Штурм4"
  },
  {
    "id": 217,
    "type": "shape",
    "name": "Контрольное_кресло",
    "shape": "custom",
    "color": "#d3d3d3",
    "x": 2795.68,
    "y": 705.78,
    "width": 60,
    "height": 60,
    "curr_hp": 3,
    "endedTurn": false
  },
  {
    "id": 218,
    "type": "shape",
    "name": "Дерево",
    "shape": "custom",
    "color": "#d3d3d3",
    "x": 2280.48,
    "y": 1191.1,
    "width": 60,
    "height": 60,
    "curr_hp": 3,
    "endedTurn": false
  },
  {
    "id": 219,
    "type": "shape",
    "name": "Дерево",
    "shape": "custom",
    "color": "#d3d3d3",
    "x": 2178.3,
    "y": 1100.97,
    "width": 60,
    "height": 60,
    "curr_hp": 3,
    "endedTurn": false
  },
  {
    "id": 220,
    "type": "shape",
    "name": "Дерево",
    "shape": "custom",
    "color": "#d3d3d3",
    "x": 2179.69,
    "y": 1286.59,
    "width": 60,
    "height": 60,
    "curr_hp": 3,
    "endedTurn": false
  },
  {
    "id": 221,
    "type": "shape",
    "name": "Дерево",
    "shape": "custom",
    "color": "#d3d3d3",
    "x": 2180.8,
    "y": 1398.23,
    "width": 60,
    "height": 60,
    "curr_hp": 3,
    "endedTurn": false
  },
  {
    "id": 222,
    "type": "shape",
    "name": "Дерево",
    "shape": "custom",
    "color": "#d3d3d3",
    "x": 2577.24,
    "y": 1195.16,
    "width": 60,
    "height": 60,
    "curr_hp": 3,
    "endedTurn": false
  },
  {
    "id": 223,
    "type": "shape",
    "name": "Дерево",
    "shape": "custom",
    "color": "#d3d3d3",
    "x": 2578.62,
    "y": 1393.25,
    "width": 60,
    "height": 60,
    "curr_hp": 3,
    "endedTurn": false
  },
  {
    "id": 224,
    "type": "shape",
    "name": "Дерево",
    "shape": "custom",
    "color": "#d3d3d3",
    "x": 2581.39,
    "y": 1091.28,
    "width": 60,
    "height": 60,
    "curr_hp": 3,
    "endedTurn": false
  },
  {
    "id": 225,
    "type": "shape",
    "name": "Дерево",
    "shape": "custom",
    "color": "#d3d3d3",
    "x": 2477.5,
    "y": 1103.74,
    "width": 60,
    "height": 60,
    "curr_hp": 3,
    "endedTurn": false
  },
  {
    "id": 226,
    "type": "shape",
    "name": "Кровать",
    "shape": "custom",
    "color": "#d3d3d3",
    "x": 1138.74,
    "y": 1816.44,
    "width": 60,
    "height": 60,
    "curr_hp": 3,
    "endedTurn": false
  },
  {
    "id": 228,
    "type": "shape",
    "name": "Тень_Усопшего",
    "shape": "custom",
    "color": "#930000",
    "x": 4310.49,
    "y": 2084.36,
    "width": 60,
    "height": 60,
    "curr_hp": 3,
    "endedTurn": true,
    "src": ""
  },
  {
    "id": 229,
    "type": "shape",
    "name": "Костяной_паук",
    "shape": "custom",
    "color": "#930000",
    "x": 2471.6,
    "y": 1190.84,
    "width": 60,
    "height": 60,
    "curr_hp": 3,
    "endedTurn": true
  },
  {
    "id": 230,
    "type": "shape",
    "name": "Костяной_паук",
    "shape": "custom",
    "color": "#930000",
    "x": 2275.55,
    "y": 1390.86,
    "width": 60,
    "height": 60,
    "curr_hp": 3,
    "endedTurn": true
  },
  {
    "id": 231,
    "type": "shape",
    "name": "Костяной_паук",
    "shape": "custom",
    "color": "#930000",
    "x": 2255.21,
    "y": 1089.74,
    "width": 60,
    "height": 60,
    "curr_hp": 1,
    "endedTurn": true
  },
  {
    "id": 232,
    "type": "shape",
    "name": "Тень_Усопшего",
    "shape": "custom",
    "color": "#930000",
    "x": 3426,
    "y": 1068.29,
    "width": 60,
    "height": 60,
    "curr_hp": 3,
    "endedTurn": true
  },
  {
    "id": 234,
    "type": "shape",
    "name": "Холодный_свет",
    "shape": "custom",
    "color": "#930000",
    "x": 4016.61,
    "y": 1116.8,
    "width": 60,
    "height": 60,
    "curr_hp": 3,
    "endedTurn": true
  },
  {
    "id": 237,
    "type": "shape",
    "name": "Холодный_свет",
    "shape": "custom",
    "color": "#930000",
    "x": 3821.65,
    "y": 1118.5,
    "width": 60,
    "height": 60,
    "curr_hp": 3,
    "endedTurn": true
  },
  {
    "id": 238,
    "type": "shape",
    "name": "Холодный_свет",
    "shape": "custom",
    "color": "#930000",
    "x": 3700.27,
    "y": 1062.69,
    "width": 60,
    "height": 60,
    "curr_hp": 3,
    "endedTurn": true
  },
  {
    "id": 240,
    "type": "shape",
    "name": "Тень_Усопшего",
    "shape": "custom",
    "color": "#930000",
    "x": 3241.85,
    "y": 745.66,
    "width": 60,
    "height": 60,
    "curr_hp": 3,
    "endedTurn": true,
    "src": ""
  },
  {
    "id": 241,
    "type": "shape",
    "name": "Холодный_свет",
    "shape": "custom",
    "color": "#930000",
    "x": 2927.18,
    "y": 667.36,
    "width": 60,
    "height": 60,
    "curr_hp": 3,
    "endedTurn": false
  },
  {
    "id": 242,
    "type": "shape",
    "name": "Холодный_свет",
    "shape": "custom",
    "color": "#930000",
    "x": 2914.35,
    "y": 737.81,
    "width": 60,
    "height": 60,
    "curr_hp": 3,
    "endedTurn": false
  },
  {
    "id": 244,
    "type": "shape",
    "name": "Кристалл_души",
    "shape": "custom",
    "color": "#d3d3d3",
    "x": 2761.97,
    "y": 1167.94,
    "width": 60,
    "height": 60,
    "curr_hp": 3,
    "endedTurn": false,
    "src": ""
  },
  {
    "id": 245,
    "type": "shape",
    "name": "Кристалл_души",
    "shape": "custom",
    "color": "#d3d3d3",
    "x": 1543.7,
    "y": 1575.43,
    "width": 60,
    "height": 60,
    "curr_hp": 3,
    "endedTurn": false
  },
  {
    "id": 247,
    "type": "shape",
    "name": "Холодный_свет",
    "shape": "custom",
    "color": "#930000",
    "x": 2045.06,
    "y": 1177.13,
    "width": 60,
    "height": 60,
    "curr_hp": 3,
    "endedTurn": true
  },
  {
    "id": 248,
    "type": "shape",
    "name": "Холодный_свет",
    "shape": "custom",
    "color": "#930000",
    "x": 2151.38,
    "y": 1176.96,
    "width": 60,
    "height": 60,
    "src": "",
    "curr_hp": 3,
    "endedTurn": true
  },
  {
    "id": 250,
    "type": "shape",
    "name": "Холодный_свет",
    "shape": "custom",
    "color": "#930000",
    "x": 2149.93,
    "y": 1265.87,
    "width": 60,
    "height": 60,
    "curr_hp": 3,
    "endedTurn": true
  },
  {
    "id": 251,
    "type": "shape",
    "name": "Холодный_свет",
    "shape": "custom",
    "color": "#930000",
    "x": 2197.07,
    "y": 1216.01,
    "width": 60,
    "height": 60,
    "curr_hp": 3,
    "endedTurn": true
  },
  {
    "id": 252,
    "type": "shape",
    "name": "Холодный_свет",
    "shape": "custom",
    "color": "#930000",
    "x": 2051.38,
    "y": 1223.98,
    "width": 60,
    "height": 60,
    "curr_hp": 3,
    "endedTurn": true
  },
  {
    "id": 253,
    "type": "shape",
    "name": "Обзор",
    "shape": "custom",
    "color": "#d3d3d3",
    "x": 3579.33,
    "y": 2283.53,
    "width": 60,
    "height": 60,
    "curr_hp": 3,
    "endedTurn": false
  },
  {
    "id": 254,
    "type": "shape",
    "name": "Кристалл_души",
    "shape": "custom",
    "color": "#d3d3d3",
    "x": 3907.51,
    "y": 1914.51,
    "width": 60,
    "height": 60,
    "src": "",
    "curr_hp": 3,
    "endedTurn": false
  },
  {
    "id": 259,
    "type": "shape",
    "name": "Тень_Усопшего",
    "shape": "custom",
    "color": "#930000",
    "x": 4067.45,
    "y": 1312.44,
    "width": 60,
    "height": 60,
    "curr_hp": 3,
    "endedTurn": true
  },
  {
    "id": 260,
    "type": "shape",
    "name": "Тень_Усопшего",
    "shape": "custom",
    "color": "#930000",
    "x": 3499.23,
    "y": 1280.47,
    "width": 60,
    "height": 60,
    "curr_hp": 3,
    "endedTurn": true
  },
  {
    "id": 261,
    "type": "shape",
    "name": "Тень_Усопшего",
    "shape": "custom",
    "color": "#930000",
    "x": 3619.4,
    "y": 1062.64,
    "width": 60,
    "height": 60,
    "curr_hp": 3,
    "endedTurn": true
  },
  {
    "id": 262,
    "type": "shape",
    "name": "Тень_Усопшего",
    "shape": "custom",
    "color": "#930000",
    "x": 3256.3,
    "y": 824.02,
    "width": 60,
    "height": 60,
    "curr_hp": 3,
    "endedTurn": true
  },
  {
    "id": 267,
    "type": "shape",
    "name": "Тень_Усопшего",
    "shape": "custom",
    "color": "#930000",
    "x": 3914.23,
    "y": 1310.78,
    "width": 60,
    "height": 60,
    "curr_hp": 3,
    "endedTurn": true
  },
  {
    "id": 269,
    "type": "shape",
    "name": "Тень_Усопшего",
    "shape": "custom",
    "color": "#930000",
    "x": 4111.25,
    "y": 1314.19,
    "width": 60,
    "height": 60,
    "curr_hp": 3,
    "endedTurn": true
  },
  {
    "id": 270,
    "type": "shape",
    "name": "Тень_Усопшего",
    "shape": "custom",
    "color": "#930000",
    "x": 3563.56,
    "y": 1055.48,
    "width": 60,
    "height": 60,
    "src": "",
    "curr_hp": 3,
    "endedTurn": true
  },
  {
    "id": 272,
    "type": "shape",
    "name": "Тень_Усопшего",
    "shape": "custom",
    "color": "#930000",
    "x": 4527.84,
    "y": 1265.63,
    "width": 60,
    "height": 60,
    "src": "",
    "curr_hp": 3,
    "endedTurn": true
  },
  {
    "id": 274,
    "type": "shape",
    "name": "Тень_Усопшего",
    "shape": "custom",
    "color": "#930000",
    "x": 3700.28,
    "y": 678.92,
    "width": 60,
    "height": 60,
    "curr_hp": 3,
    "endedTurn": true
  },
  {
    "id": 275,
    "type": "shape",
    "name": "Тень_Усопшего",
    "shape": "custom",
    "color": "#930000",
    "x": 3314.05,
    "y": 749.14,
    "width": 60,
    "height": 60,
    "curr_hp": 3,
    "endedTurn": true
  },
  {
    "id": 276,
    "type": "shape",
    "name": "Тень_Усопшего",
    "shape": "custom",
    "color": "#930000",
    "x": 3317.36,
    "y": 833.82,
    "width": 60,
    "height": 60,
    "src": "",
    "curr_hp": 3,
    "endedTurn": true
  },
  {
    "id": 277,
    "type": "shape",
    "name": "Тень_Усопшего",
    "shape": "custom",
    "color": "#930000",
    "x": 2765.13,
    "y": 1071.96,
    "width": 60,
    "height": 60,
    "curr_hp": 3,
    "endedTurn": true
  },
  {
    "id": 279,
    "type": "shape",
    "name": "Холодный_свет",
    "shape": "custom",
    "color": "#930000",
    "x": 2701.53,
    "y": 1187.72,
    "width": 60,
    "height": 60,
    "src": "",
    "curr_hp": 3,
    "endedTurn": true
  },
  {
    "id": 280,
    "type": "shape",
    "name": "Холодный_свет",
    "shape": "custom",
    "color": "#930000",
    "x": 2655.41,
    "y": 1178.89,
    "width": 60,
    "height": 60,
    "curr_hp": 3,
    "endedTurn": true
  },
  {
    "id": 281,
    "type": "shape",
    "name": "Холодный_свет",
    "shape": "custom",
    "color": "#930000",
    "x": 2665.53,
    "y": 1209.94,
    "width": 60,
    "height": 60,
    "curr_hp": 3,
    "endedTurn": true
  },
  {
    "id": 282,
    "type": "shape",
    "name": "Холодный_свет",
    "shape": "custom",
    "color": "#930000",
    "x": 2761.94,
    "y": 1225.31,
    "width": 60,
    "height": 60,
    "curr_hp": 3,
    "endedTurn": true
  },
  {
    "id": 283,
    "type": "shape",
    "name": "Холодный_свет",
    "shape": "custom",
    "color": "#930000",
    "x": 2783.32,
    "y": 1179.09,
    "width": 60,
    "height": 60,
    "src": "",
    "curr_hp": 3,
    "endedTurn": true
  },
  {
    "id": 288,
    "type": "shape",
    "name": "Тень_Усопшего",
    "shape": "custom",
    "color": "#930000",
    "x": 1096.05,
    "y": 1780.68,
    "width": 60,
    "height": 60,
    "curr_hp": 3,
    "endedTurn": true
  },
  {
    "id": 289,
    "type": "shape",
    "name": "Тень_Усопшего",
    "shape": "custom",
    "color": "#930000",
    "x": 3389.67,
    "y": 1121.2,
    "width": 60,
    "height": 60,
    "curr_hp": 3,
    "endedTurn": true
  },
  {
    "id": 290,
    "type": "shape",
    "name": "Тень_Усопшего",
    "shape": "custom",
    "color": "#930000",
    "x": 3387.24,
    "y": 1066.68,
    "width": 60,
    "height": 60,
    "curr_hp": 3,
    "endedTurn": true
  },
  {
    "id": 291,
    "type": "shape",
    "name": "Тень_Усопшего",
    "shape": "custom",
    "color": "#930000",
    "x": 3556.46,
    "y": 1105.16,
    "width": 60,
    "height": 60,
    "curr_hp": 3,
    "endedTurn": true
  },
  {
    "id": 292,
    "type": "shape",
    "name": "Тень_Усопшего",
    "shape": "custom",
    "color": "#930000",
    "x": 3479.99,
    "y": 1062.23,
    "width": 60,
    "height": 60,
    "curr_hp": 3,
    "endedTurn": true
  },
  {
    "id": 293,
    "type": "shape",
    "name": "Тень_Усопшего",
    "shape": "custom",
    "color": "#930000",
    "x": 3751.96,
    "y": 1064.92,
    "width": 60,
    "height": 60,
    "curr_hp": 3,
    "endedTurn": false
  },
  {
    "id": 296,
    "type": "shape",
    "name": "Тень_Усопшего",
    "shape": "custom",
    "color": "#930000",
    "x": 3560.92,
    "y": 1875.82,
    "width": 60,
    "height": 60,
    "src": "",
    "curr_hp": 3,
    "endedTurn": true
  },
  {
    "id": 297,
    "type": "shape",
    "name": "Тень_Усопшего",
    "shape": "custom",
    "color": "#930000",
    "x": 3436.17,
    "y": 1122.83,
    "width": 60,
    "height": 60,
    "curr_hp": 3,
    "endedTurn": true
  },
  {
    "id": 298,
    "type": "shape",
    "name": "Холодный_свет",
    "shape": "custom",
    "color": "#930000",
    "x": 2809.05,
    "y": 1222.03,
    "width": 60,
    "height": 60,
    "curr_hp": 3,
    "endedTurn": true
  },
  {
    "id": 299,
    "type": "shape",
    "name": "Тень_Усопшего",
    "shape": "custom",
    "color": "#930000",
    "x": 1958.49,
    "y": 1175.36,
    "width": 60,
    "height": 60,
    "curr_hp": 3,
    "endedTurn": true
  },
  {
    "id": 300,
    "type": "shape",
    "name": "Тень_Усопшего",
    "shape": "custom",
    "color": "#930000",
    "x": 3758.15,
    "y": 1977.06,
    "width": 60,
    "height": 60,
    "curr_hp": 3,
    "endedTurn": true
  },
  {
    "id": 301,
    "type": "shape",
    "name": "Тень_Усопшего",
    "shape": "custom",
    "color": "#930000",
    "x": 4275.54,
    "y": 858.85,
    "width": 60,
    "height": 60,
    "curr_hp": 3,
    "endedTurn": true,
    "src": ""
  },
  {
    "id": 306,
    "type": "shape",
    "name": "Тень_Усопшего",
    "shape": "custom",
    "color": "#930000",
    "x": 3117.25,
    "y": 1131.34,
    "width": 60,
    "height": 60,
    "curr_hp": 3,
    "endedTurn": true
  },
  {
    "id": 307,
    "type": "shape",
    "name": "Тень_Усопшего",
    "shape": "custom",
    "color": "#930000",
    "x": 2953.21,
    "y": 810.95,
    "width": 60,
    "height": 60,
    "curr_hp": 3,
    "endedTurn": true
  },
  {
    "id": 308,
    "type": "shape",
    "name": "Тень_Усопшего",
    "shape": "custom",
    "color": "#930000",
    "x": 3063.5,
    "y": 766.19,
    "width": 60,
    "height": 60,
    "curr_hp": 3,
    "endedTurn": true
  },
  {
    "id": 309,
    "type": "shape",
    "name": "Тень_Усопшего",
    "shape": "custom",
    "color": "#930000",
    "x": 3066.4,
    "y": 1133.71,
    "width": 60,
    "height": 60,
    "curr_hp": 3,
    "endedTurn": true
  },
  {
    "id": 310,
    "type": "shape",
    "name": "Холодный_свет",
    "shape": "custom",
    "color": "#930000",
    "x": 2854.63,
    "y": 1268.46,
    "width": 60,
    "height": 60,
    "src": "",
    "curr_hp": 3,
    "endedTurn": true
  },
  {
    "id": 311,
    "type": "shape",
    "name": "Холодный_свет",
    "shape": "custom",
    "color": "#930000",
    "x": 2898.07,
    "y": 1295.48,
    "width": 60,
    "height": 60,
    "curr_hp": 3,
    "endedTurn": true
  },
  {
    "id": 312,
    "type": "shape",
    "name": "Холодный_свет",
    "shape": "custom",
    "color": "#930000",
    "x": 2858.03,
    "y": 1325.38,
    "width": 60,
    "height": 60,
    "curr_hp": 3,
    "endedTurn": true,
    "src": ""
  },
  {
    "id": 316,
    "type": "shape",
    "name": "Закрытая_дверь",
    "shape": "custom",
    "color": "#d3d3d3",
    "x": 1678.47,
    "y": 786.58,
    "width": 60,
    "height": 60,
    "curr_hp": 3,
    "endedTurn": false
  },
  {
    "id": 317,
    "type": "shape",
    "name": "Закрытая_дверь",
    "shape": "custom",
    "color": "#d3d3d3",
    "x": 1874.19,
    "y": 889.57,
    "width": 60,
    "height": 60,
    "curr_hp": 3,
    "endedTurn": false
  },
  {
    "id": 318,
    "type": "shape",
    "name": "Закрытая_дверь",
    "shape": "custom",
    "color": "#d3d3d3",
    "x": 1871.64,
    "y": 1498.9,
    "width": 60,
    "height": 60,
    "curr_hp": 3,
    "endedTurn": false
  },
  {
    "id": 319,
    "type": "shape",
    "name": "Закрытая_дверь",
    "shape": "custom",
    "color": "#d3d3d3",
    "x": 1689.252931858656,
    "y": 1806.0113694973827,
    "width": 60,
    "height": 60,
    "curr_hp": 3,
    "endedTurn": false
  },
  {
    "id": 320,
    "type": "shape",
    "name": "Закрытая_дверь",
    "shape": "custom",
    "color": "#d3d3d3",
    "x": 1691.94,
    "y": 1590.09,
    "width": 60,
    "height": 60,
    "curr_hp": 3,
    "endedTurn": false
  },
  {
    "id": 321,
    "type": "shape",
    "name": "Закрытая_дверь",
    "shape": "custom",
    "color": "#d3d3d3",
    "x": 3187.27,
    "y": 1796.62,
    "width": 60,
    "height": 60,
    "curr_hp": 3,
    "endedTurn": false
  },
  {
    "id": 322,
    "type": "shape",
    "name": "Закрытая_дверь",
    "shape": "custom",
    "color": "#d3d3d3",
    "x": 3184.45,
    "y": 1404.73,
    "width": 60,
    "height": 60,
    "curr_hp": 2,
    "endedTurn": false
  },
  {
    "id": 323,
    "type": "shape",
    "name": "Закрытая_дверь",
    "shape": "custom",
    "color": "#d3d3d3",
    "x": 3077.3,
    "y": 1603.5,
    "width": 60,
    "height": 60,
    "curr_hp": 3,
    "endedTurn": false
  },
  {
    "id": 324,
    "type": "shape",
    "name": "Закрытая_дверь",
    "shape": "custom",
    "color": "#d3d3d3",
    "x": 4504.12,
    "y": 2102.39,
    "width": 60,
    "height": 60,
    "curr_hp": 3,
    "endedTurn": false
  },
  {
    "id": 325,
    "type": "shape",
    "name": "Закрытая_дверь",
    "shape": "custom",
    "color": "#d3d3d3",
    "x": 4488.57,
    "y": 895.28,
    "width": 60,
    "height": 60,
    "curr_hp": 3,
    "endedTurn": false
  },
  {
    "id": 326,
    "type": "shape",
    "name": "Закрытая_дверь",
    "shape": "custom",
    "color": "#d3d3d3",
    "x": 4596.78,
    "y": 1194.1,
    "width": 60,
    "height": 60,
    "curr_hp": 3,
    "endedTurn": false
  },
  {
    "id": 327,
    "type": "shape",
    "name": "Тень_Усопшего",
    "shape": "custom",
    "color": "#930000",
    "x": 1044.59,
    "y": 1827.38,
    "width": 60,
    "height": 60,
    "curr_hp": 3,
    "endedTurn": true
  },
  {
    "id": 328,
    "type": "shape",
    "name": "Тень_Усопшего",
    "shape": "custom",
    "color": "#930000",
    "x": 3330.25,
    "y": 687.86,
    "width": 60,
    "height": 60,
    "curr_hp": 3,
    "endedTurn": true
  },
  {
    "id": 329,
    "type": "shape",
    "name": "Тень_Усопшего",
    "shape": "custom",
    "color": "#930000",
    "x": 3257.97,
    "y": 688.24,
    "width": 60,
    "height": 60,
    "curr_hp": 3,
    "endedTurn": true
  },
  {
    "id": 330,
    "type": "shape",
    "name": "Тень_Усопшего",
    "shape": "custom",
    "color": "#930000",
    "x": 3247.15,
    "y": 897.05,
    "width": 60,
    "height": 60,
    "curr_hp": 3,
    "endedTurn": true
  },
  {
    "id": 331,
    "type": "shape",
    "name": "Тень_Усопшего",
    "shape": "custom",
    "color": "#930000",
    "x": 3316.22,
    "y": 908.39,
    "width": 60,
    "height": 60,
    "curr_hp": 3,
    "endedTurn": true
  },
  {
    "id": 332,
    "type": "shape",
    "name": "Холодный_свет",
    "shape": "custom",
    "color": "#930000",
    "x": 2850.33,
    "y": 1582.69,
    "width": 60,
    "height": 60,
    "src": "",
    "curr_hp": 3,
    "endedTurn": true
  },
  {
    "id": 333,
    "type": "shape",
    "name": "Холодный_свет",
    "shape": "custom",
    "color": "#930000",
    "x": 2921.26,
    "y": 1614.28,
    "width": 60,
    "height": 60,
    "curr_hp": 3,
    "endedTurn": true
  },
  {
    "id": 334,
    "type": "shape",
    "name": "Холодный_свет",
    "shape": "custom",
    "color": "#930000",
    "x": 2888.6,
    "y": 1563.53,
    "width": 60,
    "height": 60,
    "curr_hp": 3,
    "endedTurn": true
  },
  {
    "id": 335,
    "type": "shape",
    "name": "Тень_Усопшего",
    "shape": "custom",
    "color": "#930000",
    "x": 4318.48,
    "y": 891.15,
    "width": 60,
    "height": 60,
    "curr_hp": 3,
    "endedTurn": true
  },
  {
    "id": 336,
    "type": "shape",
    "name": "Тень_Усопшего",
    "shape": "custom",
    "color": "#930000",
    "x": 4284.74,
    "y": 2136.95,
    "width": 60,
    "height": 60,
    "curr_hp": 3,
    "endedTurn": true
  },
  {
    "id": 337,
    "type": "shape",
    "name": "Тень_Усопшего",
    "shape": "custom",
    "color": "#930000",
    "x": 3577.31,
    "y": 1929.46,
    "width": 60,
    "height": 60,
    "curr_hp": 3,
    "endedTurn": true
  }
]