CURRENT_TURN=1;
OTHER_SAVE_DATA={
  "scale": 0.5013256704038761,
  "canvasOffsetX": -1697.3169899411364,
  "canvasOffsetY": -496.7492247167396,
  "shapeColor": "#d3d3d3"
};
USER_RESOURCES={
  "Нейтралы": {},
  "Враги": {},
  "Десант": {},
  "Эл-во": {}
};
OWNER_MAP={};
DEFAULT_DATA=[
  {
    "id": 3,
    "type": "shape",
    "name": "Алтарь_Покоя",
    "shape": "custom",
    "color": "#d3d3d3",
    "x": 1854.84,
    "y": 680.85,
    "width": 80,
    "height": 80,
    "curr_hp": 3,
    "endedTurn": false
  },
  {
    "id": 5,
    "type": "shape",
    "name": "Движетель",
    "shape": "custom",
    "color": "#d3d3d3",
    "x": 4784.91,
    "y": 879.4,
    "width": 80,
    "height": 80,
    "curr_hp": 3,
    "endedTurn": false
  },
  {
    "id": 6,
    "type": "shape",
    "name": "Движетель",
    "shape": "custom",
    "color": "#d3d3d3",
    "x": 4787.28,
    "y": 2082.54,
    "width": 80,
    "height": 80,
    "curr_hp": 3,
    "endedTurn": false
  },
  {
    "id": 7,
    "type": "shape",
    "name": "Цепи_движетеля",
    "shape": "custom",
    "color": "#d3d3d3",
    "x": 4697.56,
    "y": 788.06,
    "width": 60,
    "height": 60,
    "curr_hp": 3,
    "endedTurn": false
  },
  {
    "id": 8,
    "type": "shape",
    "name": "Цепи_движетеля",
    "shape": "custom",
    "color": "#d3d3d3",
    "x": 4593.745457720724,
    "y": 683.3927495639743,
    "width": 60,
    "height": 60,
    "curr_hp": 3,
    "endedTurn": false
  },
  {
    "id": 9,
    "type": "shape",
    "name": "Цепи_движетеля",
    "shape": "custom",
    "color": "#d3d3d3",
    "x": 4794.38,
    "y": 984.62,
    "width": 60,
    "height": 60,
    "curr_hp": 3,
    "endedTurn": false
  },
  {
    "id": 10,
    "type": "shape",
    "name": "Цепи_движетеля",
    "shape": "custom",
    "color": "#d3d3d3",
    "x": 4794.24,
    "y": 1099.53,
    "width": 60,
    "height": 60,
    "curr_hp": 3,
    "endedTurn": false
  },
  {
    "id": 11,
    "type": "shape",
    "name": "Цепи_движетеля",
    "shape": "custom",
    "color": "#d3d3d3",
    "x": 4903.54,
    "y": 792.96,
    "width": 60,
    "height": 60,
    "curr_hp": 3,
    "endedTurn": false
  },
  {
    "id": 12,
    "type": "shape",
    "name": "Цепи_движетеля",
    "shape": "custom",
    "color": "#d3d3d3",
    "x": 5006.66,
    "y": 685.08,
    "width": 60,
    "height": 60,
    "curr_hp": 3,
    "endedTurn": false
  },
  {
    "id": 13,
    "type": "shape",
    "name": "Цепи_движетеля",
    "shape": "custom",
    "color": "#d3d3d3",
    "x": 4791.43,
    "y": 1991.75,
    "width": 60,
    "height": 60,
    "curr_hp": 3,
    "endedTurn": false
  },
  {
    "id": 14,
    "type": "shape",
    "name": "Цепи_движетеля",
    "shape": "custom",
    "color": "#d3d3d3",
    "x": 4795.79,
    "y": 1903.77,
    "width": 60,
    "height": 60,
    "curr_hp": 3,
    "endedTurn": false
  },
  {
    "id": 15,
    "type": "shape",
    "name": "Цепи_движетеля",
    "shape": "custom",
    "color": "#d3d3d3",
    "x": 4902.14,
    "y": 2196.88,
    "width": 60,
    "height": 60,
    "curr_hp": 3,
    "endedTurn": false
  },
  {
    "id": 16,
    "type": "shape",
    "name": "Цепи_движетеля",
    "shape": "custom",
    "color": "#d3d3d3",
    "x": 5000.63,
    "y": 2300.99,
    "width": 60,
    "height": 60,
    "curr_hp": 3,
    "endedTurn": false
  },
  {
    "id": 17,
    "type": "shape",
    "name": "Цепи_движетеля",
    "shape": "custom",
    "color": "#d3d3d3",
    "x": 4696.87,
    "y": 2194.92,
    "width": 60,
    "height": 60,
    "curr_hp": 3,
    "endedTurn": false
  },
  {
    "id": 18,
    "type": "shape",
    "name": "Цепи_движетеля",
    "shape": "custom",
    "color": "#d3d3d3",
    "x": 4604.4,
    "y": 2299.86,
    "width": 60,
    "height": 60,
    "curr_hp": 3,
    "endedTurn": false
  },
  {
    "id": 19,
    "type": "shape",
    "name": "Центр_управления",
    "shape": "custom",
    "color": "#d3d3d3",
    "x": 858.21,
    "y": 1489.03,
    "width": 80,
    "height": 80,
    "curr_hp": 3,
    "endedTurn": false,
    "disabled": true
  },
  {
    "id": 21,
    "type": "shape",
    "name": "Центр_связи",
    "shape": "custom",
    "color": "#d3d3d3",
    "x": 1451.39,
    "y": 779.14,
    "width": 80,
    "height": 80,
    "curr_hp": 3,
    "endedTurn": false
  },
  {
    "id": 31,
    "type": "shape",
    "name": "Пульсар_Душ",
    "shape": "custom",
    "color": "#d3d3d3",
    "x": 1860.02,
    "y": 1687.65,
    "width": 80,
    "height": 80,
    "curr_hp": 3,
    "endedTurn": false,
    "disabled": true
  },
  {
    "id": 34,
    "type": "shape",
    "name": "Чертог_Скрижалей",
    "shape": "custom",
    "color": "#d3d3d3",
    "x": 3779.68,
    "y": 676.24,
    "width": 80,
    "height": 80,
    "curr_hp": 3,
    "endedTurn": false
  },
  {
    "id": 39,
    "type": "shape",
    "name": "Оранжерея",
    "shape": "custom",
    "color": "#d3d3d3",
    "x": 2368.12,
    "y": 1181.08,
    "width": 80,
    "height": 80,
    "curr_hp": 3,
    "endedTurn": false
  },
  {
    "id": 43,
    "type": "shape",
    "name": "Обсерватория_Пустоты",
    "shape": "custom",
    "color": "#d3d3d3",
    "x": 2871.7,
    "y": 1685.87,
    "width": 80,
    "height": 80,
    "curr_hp": 3,
    "endedTurn": false
  },
  {
    "id": 46,
    "type": "shape",
    "name": "Алтарь_Покоя",
    "shape": "custom",
    "color": "#0000ff",
    "x": 3270.84,
    "y": 1584.96,
    "width": 80,
    "height": 80,
    "curr_hp": 3,
    "endedTurn": false,
    "disabled": true
  },
  {
    "id": 47,
    "type": "shape",
    "name": "Кровоточащий_Колодец",
    "shape": "custom",
    "color": "#d3d3d3",
    "x": 3784.77,
    "y": 2195.33,
    "width": 80,
    "height": 80,
    "curr_hp": 3,
    "endedTurn": false,
    "disabled": true
  },
  {
    "id": 55,
    "type": "shape",
    "name": "Кровь_колодца",
    "shape": "custom",
    "color": "#d3d3d3",
    "x": 3688.63,
    "y": 2203.95,
    "width": 80,
    "height": 80,
    "curr_hp": 3,
    "endedTurn": false
  },
  {
    "id": 56,
    "type": "shape",
    "name": "Кровь_колодца",
    "shape": "custom",
    "color": "#d3d3d3",
    "x": 3577.84,
    "y": 2294.89,
    "width": 80,
    "height": 80,
    "curr_hp": 3,
    "endedTurn": false
  },
  {
    "id": 57,
    "type": "shape",
    "name": "Кровь_колодца",
    "shape": "custom",
    "color": "#d3d3d3",
    "x": 3983.8,
    "y": 2192.99,
    "width": 80,
    "height": 80,
    "curr_hp": 3,
    "endedTurn": false
  },
  {
    "id": 58,
    "type": "shape",
    "name": "Кровь_колодца",
    "shape": "custom",
    "color": "#d3d3d3",
    "x": 3882.54,
    "y": 2191.03,
    "width": 80,
    "height": 80,
    "curr_hp": 3,
    "endedTurn": false
  },
  {
    "id": 59,
    "type": "shape",
    "name": "Кровь_колодца",
    "shape": "custom",
    "color": "#d3d3d3",
    "x": 3782.35,
    "y": 2294.45,
    "width": 80,
    "height": 80,
    "curr_hp": 3,
    "endedTurn": false
  },
  {
    "id": 60,
    "type": "shape",
    "name": "Кровь_колодца",
    "shape": "custom",
    "color": "#d3d3d3",
    "x": 3785.59,
    "y": 2396.25,
    "width": 80,
    "height": 80,
    "curr_hp": 3,
    "endedTurn": false
  },
  {
    "id": 63,
    "type": "shape",
    "name": "Пульсар_Душ",
    "shape": "custom",
    "color": "#d3d3d3",
    "x": 3276.27,
    "y": 777.9,
    "width": 80,
    "height": 80,
    "curr_hp": 3,
    "endedTurn": false,
    "disabled": true
  },
  {
    "id": 67,
    "type": "shape",
    "name": "Портальный_чертог",
    "shape": "custom",
    "color": "#d3d3d3",
    "x": 2869.3,
    "y": 1183.78,
    "width": 80,
    "height": 80,
    "curr_hp": 3,
    "endedTurn": false
  },
  {
    "id": 68,
    "type": "shape",
    "name": "Звёздная_Арка",
    "shape": "custom",
    "color": "#d3d3d3",
    "x": 2776.48,
    "y": 992.51,
    "width": 60,
    "height": 60,
    "curr_hp": 3,
    "endedTurn": false
  },
  {
    "id": 69,
    "type": "shape",
    "name": "Звёздная_Арка",
    "shape": "custom",
    "color": "#d3d3d3",
    "x": 2985.27,
    "y": 998.73,
    "width": 60,
    "height": 60,
    "curr_hp": 3,
    "endedTurn": false
  },
  {
    "id": 70,
    "type": "shape",
    "name": "Звёздная_Арка",
    "shape": "custom",
    "color": "#d3d3d3",
    "x": 2779.1,
    "y": 1393.98,
    "width": 60,
    "height": 60,
    "curr_hp": 3,
    "endedTurn": false
  },
  {
    "id": 74,
    "type": "shape",
    "name": "Звёздная_Арка",
    "shape": "custom",
    "color": "#d3d3d3",
    "x": 1978.49,
    "y": 1799.41,
    "width": 60,
    "height": 60,
    "curr_hp": 3,
    "endedTurn": false
  },
  {
    "id": 75,
    "type": "shape",
    "name": "Звёздная_Арка",
    "shape": "custom",
    "color": "#d3d3d3",
    "x": 3170.74,
    "y": 683.36,
    "width": 60,
    "height": 60,
    "curr_hp": 3,
    "endedTurn": false
  },
  {
    "id": 77,
    "type": "shape",
    "name": "Звёздная_Арка",
    "shape": "custom",
    "color": "#d3d3d3",
    "x": 3592.59,
    "y": 2200.6,
    "width": 60,
    "height": 60,
    "curr_hp": 3,
    "endedTurn": false
  },
  {
    "id": 79,
    "type": "shape",
    "name": "Целительная",
    "shape": "custom",
    "color": "#d3d3d3",
    "x": 2865.6,
    "y": 675.26,
    "width": 80,
    "height": 80,
    "curr_hp": 3,
    "endedTurn": false,
    "disabled": true
  },
  {
    "id": 80,
    "type": "shape",
    "name": "Карта_корабля",
    "shape": "custom",
    "color": "#d3d3d3",
    "x": 963.4,
    "y": 1497.05,
    "width": 60,
    "height": 60,
    "curr_hp": 3,
    "endedTurn": false
  },
  {
    "id": 81,
    "type": "shape",
    "name": "Скрижаль",
    "shape": "custom",
    "color": "#d3d3d3",
    "x": 3595.36,
    "y": 790.04,
    "width": 60,
    "height": 60,
    "curr_hp": 3,
    "endedTurn": false
  },
  {
    "id": 82,
    "type": "shape",
    "name": "Скрижаль",
    "shape": "custom",
    "color": "#d3d3d3",
    "x": 3591.6,
    "y": 885.47,
    "width": 60,
    "height": 60,
    "curr_hp": 3,
    "endedTurn": false
  },
  {
    "id": 83,
    "type": "shape",
    "name": "Скрижаль",
    "shape": "custom",
    "color": "#d3d3d3",
    "x": 3894.21,
    "y": 891.75,
    "width": 60,
    "height": 60,
    "curr_hp": 3,
    "endedTurn": false
  },
  {
    "id": 85,
    "type": "shape",
    "name": "Скрижаль",
    "shape": "custom",
    "color": "#d3d3d3",
    "x": 3992.15,
    "y": 582.86,
    "width": 60,
    "height": 60,
    "curr_hp": 3,
    "endedTurn": false
  },
  {
    "id": 86,
    "type": "shape",
    "name": "Скрижаль",
    "shape": "custom",
    "color": "#d3d3d3",
    "x": 2986.51,
    "y": 774.41,
    "width": 60,
    "height": 60,
    "curr_hp": 3,
    "endedTurn": false
  },
  {
    "id": 87,
    "type": "shape",
    "name": "Скрижаль",
    "shape": "custom",
    "color": "#d3d3d3",
    "x": 4593.38,
    "y": 2008.1,
    "width": 60,
    "height": 60,
    "curr_hp": 3,
    "endedTurn": false
  },
  {
    "id": 88,
    "type": "shape",
    "name": "Звёздная_Арка",
    "shape": "custom",
    "color": "#d3d3d3",
    "x": 4597.23,
    "y": 787.73,
    "width": 60,
    "height": 60,
    "curr_hp": 3,
    "endedTurn": false
  },
  {
    "id": 89,
    "type": "shape",
    "name": "Звёздная_Арка",
    "shape": "custom",
    "color": "#d3d3d3",
    "x": 2986.16,
    "y": 1390.09,
    "width": 60,
    "height": 60,
    "curr_hp": 3,
    "endedTurn": false
  },
  {
    "id": 90,
    "type": "shape",
    "name": "Жилая_секция",
    "shape": "custom",
    "color": "#d3d3d3",
    "x": 1860.36,
    "y": 1187.71,
    "width": 80,
    "height": 80,
    "curr_hp": 3,
    "endedTurn": false
  },
  {
    "id": 93,
    "type": "shape",
    "name": "Кровать",
    "shape": "custom",
    "color": "#d3d3d3",
    "x": 1757.7,
    "y": 1406.66,
    "width": 60,
    "height": 60,
    "curr_hp": 3,
    "endedTurn": false
  },
  {
    "id": 94,
    "type": "shape",
    "name": "Кровать",
    "shape": "custom",
    "color": "#d3d3d3",
    "x": 1757.7,
    "y": 1301.43,
    "width": 60,
    "height": 60,
    "curr_hp": 3,
    "endedTurn": false
  },
  {
    "id": 95,
    "type": "shape",
    "name": "Кровать",
    "shape": "custom",
    "color": "#d3d3d3",
    "x": 1760.26,
    "y": 1105.08,
    "width": 60,
    "height": 60,
    "curr_hp": 3,
    "endedTurn": false
  },
  {
    "id": 96,
    "type": "shape",
    "name": "Кровать",
    "shape": "custom",
    "color": "#d3d3d3",
    "x": 1762.83,
    "y": 1007.55,
    "width": 60,
    "height": 60,
    "curr_hp": 3,
    "endedTurn": false
  },
  {
    "id": 97,
    "type": "shape",
    "name": "Кровать",
    "shape": "custom",
    "color": "#d3d3d3",
    "x": 1991.26,
    "y": 1012.68,
    "width": 60,
    "height": 60,
    "curr_hp": 3,
    "endedTurn": false
  },
  {
    "id": 98,
    "type": "shape",
    "name": "Кровать",
    "shape": "custom",
    "color": "#d3d3d3",
    "x": 1989.98,
    "y": 1103.8,
    "width": 60,
    "height": 60,
    "curr_hp": 3,
    "endedTurn": false
  },
  {
    "id": 99,
    "type": "shape",
    "name": "Кровать",
    "shape": "custom",
    "color": "#d3d3d3",
    "x": 1987.41,
    "y": 1305.28,
    "width": 60,
    "height": 60,
    "curr_hp": 3,
    "endedTurn": false
  },
  {
    "id": 100,
    "type": "shape",
    "name": "Кровать",
    "shape": "custom",
    "color": "#d3d3d3",
    "x": 1987.41,
    "y": 1402.81,
    "width": 60,
    "height": 60,
    "curr_hp": 3,
    "endedTurn": false
  },
  {
    "id": 101,
    "type": "shape",
    "name": "Кровать",
    "shape": "custom",
    "color": "#d3d3d3",
    "x": 2866.53,
    "y": 580.79,
    "width": 60,
    "height": 60,
    "curr_hp": 3,
    "endedTurn": false
  },
  {
    "id": 102,
    "type": "shape",
    "name": "Кровать",
    "shape": "custom",
    "color": "#d3d3d3",
    "x": 2968.99,
    "y": 577.3,
    "width": 60,
    "height": 60,
    "curr_hp": 3,
    "endedTurn": false
  },
  {
    "id": 103,
    "type": "shape",
    "name": "Скрижаль",
    "shape": "custom",
    "color": "#d3d3d3",
    "x": 947.74,
    "y": 1612.62,
    "width": 60,
    "height": 60,
    "curr_hp": 3,
    "endedTurn": false
  },
  {
    "id": 104,
    "type": "shape",
    "name": "Кровать",
    "shape": "custom",
    "color": "#d3d3d3",
    "x": 2770.47,
    "y": 582.58,
    "width": 60,
    "height": 60,
    "curr_hp": 3,
    "endedTurn": false
  },
  {
    "id": 105,
    "type": "shape",
    "name": "Пси-клинок",
    "shape": "custom",
    "color": "#0000ff",
    "x": 3178.88,
    "y": 1585.98,
    "width": 60,
    "height": 60,
    "curr_hp": 3,
    "endedTurn": true
  },
  {
    "id": 108,
    "type": "shape",
    "name": "Обзор",
    "shape": "custom",
    "color": "#0000ff",
    "x": 3216,
    "y": 2092.05,
    "width": 40,
    "height": 40,
    "curr_hp": 3,
    "endedTurn": true
  },
  {
    "id": 109,
    "type": "shape",
    "name": "Обзор",
    "shape": "custom",
    "color": "#0000ff",
    "x": 3167.39,
    "y": 1877.5,
    "width": 40,
    "height": 40,
    "curr_hp": 3,
    "endedTurn": true
  },
  {
    "id": 110,
    "type": "shape",
    "name": "Обзор",
    "shape": "custom",
    "color": "#0000ff",
    "x": 3309.27,
    "y": 1740.16,
    "width": 40,
    "height": 40,
    "curr_hp": 3,
    "endedTurn": true
  },
  {
    "id": 111,
    "type": "shape",
    "name": "Обзор",
    "shape": "custom",
    "color": "#0000ff",
    "x": 3170,
    "y": 1471.39,
    "width": 40,
    "height": 40,
    "curr_hp": 3,
    "endedTurn": true
  },
  {
    "id": 112,
    "type": "shape",
    "name": "Обзор",
    "shape": "custom",
    "color": "#0000ff",
    "x": 3419.92,
    "y": 1482.24,
    "width": 40,
    "height": 40,
    "curr_hp": 3,
    "endedTurn": true
  },
  {
    "id": 115,
    "type": "shape",
    "name": "Звёздная_Арка",
    "shape": "custom",
    "color": "#d3d3d3",
    "x": 4599.79,
    "y": 2199.31,
    "width": 60,
    "height": 60,
    "curr_hp": 3,
    "endedTurn": false
  }
]