CURRENT_TURN=1;
OTHER_SAVE_DATA={
  "scale": 0.38650253630891757,
  "canvasOffsetX": -739.7480262229749,
  "canvasOffsetY": -159.85882083049785,
  "shapeColor": "#930000"
};
USER_RESOURCES={
  "Нейтралы": {},
  "Враги": {},
  "Десант": {},
  "Эл-во": {}
};
OWNER_MAP={"122":[353],"128":[354]};
DEFAULT_DATA=[
  {
    "id": 3,
    "type": "shape",
    "name": "Алтарь_Покоя",
    "shape": "custom",
    "color": "#930000",
    "x": 1858.52,
    "y": 680.85,
    "width": 80,
    "height": 80,
    "curr_hp": 3,
    "endedTurn": false,
    "disabled": true
  },
  {
    "id": 5,
    "type": "shape",
    "name": "Движетель",
    "shape": "custom",
    "color": "#d3d3d3",
    "x": 4784.91,
    "y": 879.4,
    "width": 80,
    "height": 80,
    "curr_hp": 3,
    "endedTurn": false
  },
  {
    "id": 6,
    "type": "shape",
    "name": "Движетель",
    "shape": "custom",
    "color": "#d3d3d3",
    "x": 4787.28,
    "y": 2082.54,
    "width": 80,
    "height": 80,
    "curr_hp": 3,
    "endedTurn": false
  },
  {
    "id": 7,
    "type": "shape",
    "name": "Цепи_движетеля",
    "shape": "custom",
    "color": "#d3d3d3",
    "x": 4680.27,
    "y": 806.43,
    "width": 60,
    "height": 60,
    "curr_hp": 3,
    "endedTurn": false
  },
  {
    "id": 8,
    "type": "shape",
    "name": "Цепи_движетеля",
    "shape": "custom",
    "color": "#d3d3d3",
    "x": 4593.745457720724,
    "y": 683.3927495639743,
    "width": 60,
    "height": 60,
    "curr_hp": 3,
    "endedTurn": false
  },
  {
    "id": 9,
    "type": "shape",
    "name": "Цепи_движетеля",
    "shape": "custom",
    "color": "#d3d3d3",
    "x": 4794.38,
    "y": 984.62,
    "width": 60,
    "height": 60,
    "curr_hp": 3,
    "endedTurn": false
  },
  {
    "id": 10,
    "type": "shape",
    "name": "Цепи_движетеля",
    "shape": "custom",
    "color": "#d3d3d3",
    "x": 4794.24,
    "y": 1099.53,
    "width": 60,
    "height": 60,
    "curr_hp": 3,
    "endedTurn": false
  },
  {
    "id": 11,
    "type": "shape",
    "name": "Цепи_движетеля",
    "shape": "custom",
    "color": "#d3d3d3",
    "x": 4903.54,
    "y": 792.96,
    "width": 60,
    "height": 60,
    "curr_hp": 3,
    "endedTurn": false
  },
  {
    "id": 12,
    "type": "shape",
    "name": "Цепи_движетеля",
    "shape": "custom",
    "color": "#d3d3d3",
    "x": 5006.66,
    "y": 685.08,
    "width": 60,
    "height": 60,
    "curr_hp": 3,
    "endedTurn": false
  },
  {
    "id": 13,
    "type": "shape",
    "name": "Цепи_движетеля",
    "shape": "custom",
    "color": "#d3d3d3",
    "x": 4791.43,
    "y": 1991.75,
    "width": 60,
    "height": 60,
    "curr_hp": 3,
    "endedTurn": false
  },
  {
    "id": 14,
    "type": "shape",
    "name": "Цепи_движетеля",
    "shape": "custom",
    "color": "#d3d3d3",
    "x": 4795.79,
    "y": 1903.77,
    "width": 60,
    "height": 60,
    "curr_hp": 3,
    "endedTurn": false
  },
  {
    "id": 15,
    "type": "shape",
    "name": "Цепи_движетеля",
    "shape": "custom",
    "color": "#d3d3d3",
    "x": 4902.14,
    "y": 2196.88,
    "width": 60,
    "height": 60,
    "curr_hp": 3,
    "endedTurn": false
  },
  {
    "id": 16,
    "type": "shape",
    "name": "Цепи_движетеля",
    "shape": "custom",
    "color": "#d3d3d3",
    "x": 5000.63,
    "y": 2300.99,
    "width": 60,
    "height": 60,
    "curr_hp": 3,
    "endedTurn": false
  },
  {
    "id": 17,
    "type": "shape",
    "name": "Цепи_движетеля",
    "shape": "custom",
    "color": "#d3d3d3",
    "x": 4696.87,
    "y": 2194.92,
    "width": 60,
    "height": 60,
    "curr_hp": 3,
    "endedTurn": false
  },
  {
    "id": 18,
    "type": "shape",
    "name": "Цепи_движетеля",
    "shape": "custom",
    "color": "#d3d3d3",
    "x": 4604.4,
    "y": 2299.86,
    "width": 60,
    "height": 60,
    "curr_hp": 3,
    "endedTurn": false
  },
  {
    "id": 19,
    "type": "shape",
    "name": "Центр_управления",
    "shape": "custom",
    "color": "#930000",
    "x": 955.48,
    "y": 1488.01,
    "width": 80,
    "height": 80,
    "curr_hp": 3,
    "endedTurn": false,
    "disabled": true
  },
  {
    "id": 21,
    "type": "shape",
    "name": "Центр_связи",
    "shape": "custom",
    "color": "#930000",
    "x": 1453.96,
    "y": 767.19,
    "width": 80,
    "height": 80,
    "curr_hp": 1,
    "endedTurn": false,
    "lvl": 1,
    "disabled": true,
    "src": ""
  },
  {
    "id": 31,
    "type": "shape",
    "name": "Пульсар_Душ",
    "shape": "custom",
    "color": "#930000",
    "x": 1857.7,
    "y": 1681.03,
    "width": 80,
    "height": 80,
    "curr_hp": 3,
    "endedTurn": false,
    "disabled": true
  },
  {
    "id": 34,
    "type": "shape",
    "name": "Чертог_Скрижалей",
    "shape": "custom",
    "color": "#930000",
    "x": 3769.72,
    "y": 676.39,
    "width": 80,
    "height": 80,
    "curr_hp": 3,
    "endedTurn": false,
    "disabled": true
  },
  {
    "id": 39,
    "type": "shape",
    "name": "Оранжерея",
    "shape": "custom",
    "color": "#930000",
    "x": 2368.12,
    "y": 1181.08,
    "width": 80,
    "height": 80,
    "curr_hp": 3,
    "endedTurn": false
  },
  {
    "id": 43,
    "type": "shape",
    "name": "Обсерватория_Пустоты",
    "shape": "custom",
    "color": "#930000",
    "x": 2871.7,
    "y": 1685.87,
    "width": 80,
    "height": 80,
    "curr_hp": 3,
    "endedTurn": false,
    "disabled": true
  },
  {
    "id": 46,
    "type": "shape",
    "name": "Алтарь_Покоя",
    "shape": "custom",
    "color": "#930000",
    "x": 3270.84,
    "y": 1584.96,
    "width": 80,
    "height": 80,
    "curr_hp": 3,
    "endedTurn": false,
    "disabled": true
  },
  {
    "id": 47,
    "type": "shape",
    "name": "Кровоточащий_Колодец",
    "shape": "custom",
    "color": "#d3d3d3",
    "x": 3780.64,
    "y": 2288.17,
    "width": 80,
    "height": 80,
    "curr_hp": 3,
    "endedTurn": false
  },
  {
    "id": 63,
    "type": "shape",
    "name": "Пульсар_Душ",
    "shape": "custom",
    "color": "#930000",
    "x": 3276.27,
    "y": 777.9,
    "width": 80,
    "height": 80,
    "curr_hp": 3,
    "endedTurn": false,
    "disabled": true
  },
  {
    "id": 67,
    "type": "shape",
    "name": "Портальный_чертог",
    "shape": "custom",
    "color": "#930000",
    "x": 2869.3,
    "y": 1183.78,
    "width": 80,
    "height": 80,
    "curr_hp": 3,
    "endedTurn": false,
    "disabled": true
  },
  {
    "id": 68,
    "type": "shape",
    "name": "Звёздная_Арка",
    "shape": "custom",
    "color": "#d3d3d3",
    "x": 2776.48,
    "y": 992.51,
    "width": 60,
    "height": 60,
    "curr_hp": 3,
    "endedTurn": false
  },
  {
    "id": 69,
    "type": "shape",
    "name": "Звёздная_Арка",
    "shape": "custom",
    "color": "#d3d3d3",
    "x": 2983.37,
    "y": 993.04,
    "width": 60,
    "height": 60,
    "curr_hp": 3,
    "endedTurn": false
  },
  {
    "id": 70,
    "type": "shape",
    "name": "Звёздная_Арка",
    "shape": "custom",
    "color": "#d3d3d3",
    "x": 2779.1,
    "y": 1393.98,
    "width": 60,
    "height": 60,
    "curr_hp": 3,
    "endedTurn": false
  },
  {
    "id": 74,
    "type": "shape",
    "name": "Звёздная_Арка",
    "shape": "custom",
    "color": "#d3d3d3",
    "x": 1978.49,
    "y": 1799.41,
    "width": 60,
    "height": 60,
    "curr_hp": 3,
    "endedTurn": false
  },
  {
    "id": 75,
    "type": "shape",
    "name": "Звёздная_Арка",
    "shape": "custom",
    "color": "#d3d3d3",
    "x": 3170.74,
    "y": 683.36,
    "width": 60,
    "height": 60,
    "curr_hp": 3,
    "endedTurn": false
  },
  {
    "id": 77,
    "type": "shape",
    "name": "Звёздная_Арка",
    "shape": "custom",
    "color": "#d3d3d3",
    "x": 3589.69,
    "y": 2204.73,
    "width": 60,
    "height": 60,
    "curr_hp": 3,
    "endedTurn": false
  },
  {
    "id": 79,
    "type": "shape",
    "name": "Целительная",
    "shape": "custom",
    "color": "#930000",
    "x": 2863.49,
    "y": 675.26,
    "width": 80,
    "height": 80,
    "curr_hp": 3,
    "endedTurn": false,
    "disabled": true
  },
  {
    "id": 80,
    "type": "shape",
    "name": "Карта_корабля",
    "shape": "custom",
    "color": "#d3d3d3",
    "x": 1063.75,
    "y": 1498.07,
    "width": 60,
    "height": 60,
    "curr_hp": 3,
    "endedTurn": false
  },
  {
    "id": 88,
    "type": "shape",
    "name": "Звёздная_Арка",
    "shape": "custom",
    "color": "#d3d3d3",
    "x": 4597.23,
    "y": 787.73,
    "width": 60,
    "height": 60,
    "curr_hp": 3,
    "endedTurn": false
  },
  {
    "id": 89,
    "type": "shape",
    "name": "Звёздная_Арка",
    "shape": "custom",
    "color": "#d3d3d3",
    "x": 2986.16,
    "y": 1390.09,
    "width": 60,
    "height": 60,
    "curr_hp": 3,
    "endedTurn": false
  },
  {
    "id": 90,
    "type": "shape",
    "name": "Жилая_секция",
    "shape": "custom",
    "color": "#930000",
    "x": 1855.14,
    "y": 1190.32,
    "width": 80,
    "height": 80,
    "curr_hp": 3,
    "endedTurn": false,
    "disabled": true
  },
  {
    "id": 93,
    "type": "shape",
    "name": "Кровать",
    "shape": "custom",
    "color": "#d3d3d3",
    "x": 1757.7,
    "y": 1406.66,
    "width": 60,
    "height": 60,
    "curr_hp": 3,
    "endedTurn": false
  },
  {
    "id": 94,
    "type": "shape",
    "name": "Кровать",
    "shape": "custom",
    "color": "#d3d3d3",
    "x": 1757.7,
    "y": 1301.43,
    "width": 60,
    "height": 60,
    "curr_hp": 3,
    "endedTurn": false
  },
  {
    "id": 95,
    "type": "shape",
    "name": "Кровать",
    "shape": "custom",
    "color": "#d3d3d3",
    "x": 1760.26,
    "y": 1105.08,
    "width": 60,
    "height": 60,
    "curr_hp": 3,
    "endedTurn": false
  },
  {
    "id": 96,
    "type": "shape",
    "name": "Кровать",
    "shape": "custom",
    "color": "#d3d3d3",
    "x": 1762.83,
    "y": 1007.55,
    "width": 60,
    "height": 60,
    "curr_hp": 3,
    "endedTurn": false
  },
  {
    "id": 97,
    "type": "shape",
    "name": "Кровать",
    "shape": "custom",
    "color": "#d3d3d3",
    "x": 1991.26,
    "y": 1012.68,
    "width": 60,
    "height": 60,
    "curr_hp": 3,
    "endedTurn": false
  },
  {
    "id": 98,
    "type": "shape",
    "name": "Кровать",
    "shape": "custom",
    "color": "#d3d3d3",
    "x": 1989.98,
    "y": 1103.8,
    "width": 60,
    "height": 60,
    "curr_hp": 3,
    "endedTurn": false
  },
  {
    "id": 100,
    "type": "shape",
    "name": "Кровать",
    "shape": "custom",
    "color": "#d3d3d3",
    "x": 1987.41,
    "y": 1402.81,
    "width": 60,
    "height": 60,
    "curr_hp": 3,
    "endedTurn": false
  },
  {
    "id": 101,
    "type": "shape",
    "name": "Кровать",
    "shape": "custom",
    "color": "#d3d3d3",
    "x": 2863.31,
    "y": 603.31,
    "width": 60,
    "height": 60,
    "curr_hp": 3,
    "endedTurn": false
  },
  {
    "id": 102,
    "type": "shape",
    "name": "Кровать",
    "shape": "custom",
    "color": "#d3d3d3",
    "x": 2964.16,
    "y": 606.25,
    "width": 60,
    "height": 60,
    "curr_hp": 3,
    "endedTurn": false
  },
  {
    "id": 103,
    "type": "shape",
    "name": "Скрижаль",
    "shape": "custom",
    "color": "#d3d3d3",
    "x": 870.71,
    "y": 1606.28,
    "width": 60,
    "height": 60,
    "curr_hp": 3,
    "endedTurn": false,
    "title": "Отвод глаз"
  },
  {
    "id": 104,
    "type": "shape",
    "name": "Кровать",
    "shape": "custom",
    "color": "#d3d3d3",
    "x": 2765.64,
    "y": 601.88,
    "width": 60,
    "height": 60,
    "curr_hp": 3,
    "endedTurn": false
  },
  {
    "id": 115,
    "type": "shape",
    "name": "Звёздная_Арка",
    "shape": "custom",
    "color": "#d3d3d3",
    "x": 4599.79,
    "y": 2199.31,
    "width": 60,
    "height": 60,
    "curr_hp": 3,
    "endedTurn": false
  },
  {
    "id": 116,
    "type": "shape",
    "name": "_могила",
    "shape": "custom",
    "color": "#d3d3d3",
    "x": 1309.56,
    "y": 1775.52,
    "width": 60,
    "height": 60,
    "curr_hp": 0,
    "endedTurn": false,
    "title": "Связь1",
    "src": ""
  },
  {
    "id": 117,
    "type": "shape",
    "name": "_могила",
    "shape": "custom",
    "color": "#d3d3d3",
    "x": 1519.79,
    "y": 1800.95,
    "width": 60,
    "height": 60,
    "curr_hp": 0,
    "endedTurn": false,
    "title": "Капитан",
    "src": ""
  },
  {
    "id": 119,
    "type": "shape",
    "name": "_могила",
    "shape": "custom",
    "color": "#930000",
    "x": 935.68,
    "y": 1575.82,
    "width": 60,
    "height": 60,
    "curr_hp": 0,
    "endedTurn": false,
    "title": "Навигатор",
    "src": ""
  },
  {
    "id": 120,
    "type": "shape",
    "name": "Звёздный_зомби",
    "shape": "custom",
    "color": "#930000",
    "x": 3175.29,
    "y": 841.41,
    "width": 60,
    "height": 60,
    "curr_hp": 3,
    "endedTurn": false,
    "title": "Врач",
    "src": ""
  },
  {
    "id": 121,
    "type": "shape",
    "name": "Кровавый_змей",
    "shape": "custom",
    "color": "#d3d3d3",
    "x": 3991.3,
    "y": 2342.07,
    "width": 60,
    "height": 60,
    "curr_hp": 3,
    "endedTurn": false,
    "title": "Двиг1",
    "lvl": 1,
    "src": ""
  },
  {
    "id": 122,
    "type": "shape",
    "name": "Хранитель",
    "shape": "custom",
    "color": "#930000",
    "x": 3670.96,
    "y": 802.15,
    "width": 60,
    "height": 60,
    "curr_hp": 1,
    "endedTurn": false,
    "title": "Наука"
  },
  {
    "id": 124,
    "type": "shape",
    "name": "_могила",
    "shape": "custom",
    "color": "#d3d3d3",
    "x": 1755.19,
    "y": 1065.75,
    "width": 60,
    "height": 60,
    "curr_hp": 0,
    "endedTurn": false,
    "title": "Свящ1"
  },
  {
    "id": 125,
    "type": "shape",
    "name": "_могила",
    "shape": "custom",
    "color": "#930000",
    "x": 3575.93,
    "y": 2095.86,
    "width": 60,
    "height": 60,
    "curr_hp": 0,
    "endedTurn": false,
    "title": "Свящ2",
    "src": ""
  },
  {
    "id": 126,
    "type": "shape",
    "name": "_могила",
    "shape": "custom",
    "color": "#930000",
    "x": 3854.56,
    "y": 1985.5,
    "width": 60,
    "height": 60,
    "curr_hp": 0,
    "endedTurn": false,
    "title": "Инж2",
    "src": ""
  },
  {
    "id": 127,
    "type": "shape",
    "name": "_могила",
    "shape": "custom",
    "color": "#d3d3d3",
    "x": 1537.08,
    "y": 1534.18,
    "width": 60,
    "height": 60,
    "curr_hp": 0,
    "endedTurn": false,
    "title": "Связь2"
  },
  {
    "id": 128,
    "type": "shape",
    "name": "Око_Аннигиляции",
    "shape": "custom",
    "color": "#930000",
    "x": 2791.16,
    "y": 1807.8,
    "width": 60,
    "height": 60,
    "curr_hp": 3,
    "endedTurn": false,
    "title": "Астроном",
    "disabled": true,
    "src": ""
  },
  {
    "id": 130,
    "type": "shape",
    "name": "Звёздный_зомби",
    "shape": "custom",
    "color": "#930000",
    "x": 1042.84,
    "y": 1465.39,
    "width": 60,
    "height": 60,
    "curr_hp": 0,
    "endedTurn": false,
    "title": "Старпом",
    "src": ""
  },
  {
    "id": 131,
    "type": "shape",
    "name": "Кристалл_души",
    "shape": "custom",
    "color": "#d3d3d3",
    "x": 3611.93,
    "y": 1896.47,
    "width": 60,
    "height": 60,
    "curr_hp": 3,
    "endedTurn": false,
    "src": ""
  },
  {
    "id": 132,
    "type": "shape",
    "name": "Кристалл_души",
    "shape": "custom",
    "color": "#d3d3d3",
    "x": 4003.89,
    "y": 2092.09,
    "width": 60,
    "height": 60,
    "curr_hp": 3,
    "endedTurn": false,
    "src": ""
  },
  {
    "id": 133,
    "type": "shape",
    "name": "Кристалл_души",
    "shape": "custom",
    "color": "#d3d3d3",
    "x": 4104.7,
    "y": 1194.23,
    "width": 60,
    "height": 60,
    "curr_hp": 3,
    "endedTurn": false,
    "src": ""
  },
  {
    "id": 134,
    "type": "shape",
    "name": "Кристалл_души",
    "shape": "custom",
    "color": "#d3d3d3",
    "x": 3865.87,
    "y": 1100.09,
    "width": 60,
    "height": 60,
    "curr_hp": 3,
    "endedTurn": false,
    "src": ""
  },
  {
    "id": 135,
    "type": "shape",
    "name": "Обзор",
    "shape": "custom",
    "color": "#930000",
    "x": 4271.26,
    "y": 908.47,
    "width": 60,
    "height": 60,
    "curr_hp": 3,
    "endedTurn": false
  },
  {
    "id": 136,
    "type": "shape",
    "name": "Кристалл_души",
    "shape": "custom",
    "color": "#d3d3d3",
    "x": 4474.76,
    "y": 1272.36,
    "width": 60,
    "height": 60,
    "curr_hp": 3,
    "endedTurn": false,
    "src": ""
  },
  {
    "id": 137,
    "type": "shape",
    "name": "Кристалл_души",
    "shape": "custom",
    "color": "#d3d3d3",
    "x": 4072.24,
    "y": 1684.49,
    "width": 60,
    "height": 60,
    "curr_hp": 3,
    "endedTurn": false,
    "src": ""
  },
  {
    "id": 138,
    "type": "shape",
    "name": "Кристалл_души",
    "shape": "custom",
    "color": "#d3d3d3",
    "x": 3716.97,
    "y": 1325.87,
    "width": 60,
    "height": 60,
    "curr_hp": 3,
    "endedTurn": false,
    "src": ""
  },
  {
    "id": 139,
    "type": "shape",
    "name": "Кристалл_души",
    "shape": "custom",
    "color": "#d3d3d3",
    "x": 3266.01,
    "y": 1276.16,
    "width": 60,
    "height": 60,
    "curr_hp": 3,
    "endedTurn": false,
    "src": ""
  },
  {
    "id": 140,
    "type": "shape",
    "name": "Кристалл_души",
    "shape": "custom",
    "color": "#d3d3d3",
    "x": 3261.18,
    "y": 1062.23,
    "width": 60,
    "height": 60,
    "curr_hp": 3,
    "endedTurn": false,
    "src": ""
  },
  {
    "id": 141,
    "type": "shape",
    "name": "Кристалл_души",
    "shape": "custom",
    "color": "#d3d3d3",
    "x": 3202.11,
    "y": 1889.6,
    "width": 60,
    "height": 60,
    "curr_hp": 3,
    "endedTurn": false,
    "src": ""
  },
  {
    "id": 142,
    "type": "shape",
    "name": "Кристалл_души",
    "shape": "custom",
    "color": "#d3d3d3",
    "x": 3206.53,
    "y": 2099.62,
    "width": 60,
    "height": 60,
    "curr_hp": 3,
    "endedTurn": false,
    "src": ""
  },
  {
    "id": 143,
    "type": "shape",
    "name": "Кристалл_души",
    "shape": "custom",
    "color": "#d3d3d3",
    "x": 4263.3,
    "y": 2081.94,
    "width": 60,
    "height": 60,
    "curr_hp": 3,
    "endedTurn": false,
    "src": ""
  },
  {
    "id": 144,
    "type": "shape",
    "name": "Обзор",
    "shape": "custom",
    "color": "#d3d3d3",
    "x": 4570.86,
    "y": 1986.73,
    "width": 60,
    "height": 60,
    "curr_hp": 3,
    "endedTurn": false
  },
  {
    "id": 146,
    "type": "shape",
    "name": "Обзор",
    "shape": "custom",
    "color": "#d3d3d3",
    "x": 4579.44,
    "y": 974.33,
    "width": 60,
    "height": 60,
    "curr_hp": 3,
    "endedTurn": false
  },
  {
    "id": 147,
    "type": "shape",
    "name": "Кристалл_души",
    "shape": "custom",
    "color": "#d3d3d3",
    "x": 2359.18,
    "y": 1063.99,
    "width": 60,
    "height": 60,
    "curr_hp": 3,
    "endedTurn": false,
    "src": ""
  },
  {
    "id": 148,
    "type": "shape",
    "name": "Кристалл_души",
    "shape": "custom",
    "color": "#d3d3d3",
    "x": 1552.85,
    "y": 1183,
    "width": 60,
    "height": 60,
    "curr_hp": 3,
    "endedTurn": false,
    "src": ""
  },
  {
    "id": 149,
    "type": "shape",
    "name": "Кристалл_души",
    "shape": "custom",
    "color": "#d3d3d3",
    "x": 1544.12,
    "y": 1634.15,
    "width": 60,
    "height": 60,
    "curr_hp": 3,
    "endedTurn": false,
    "src": ""
  },
  {
    "id": 150,
    "type": "shape",
    "name": "Кристалл_души",
    "shape": "custom",
    "color": "#d3d3d3",
    "x": 1336.84,
    "y": 1476.43,
    "width": 60,
    "height": 60,
    "curr_hp": 3,
    "endedTurn": false,
    "src": ""
  },
  {
    "id": 151,
    "type": "shape",
    "name": "Кристалл_души",
    "shape": "custom",
    "color": "#d3d3d3",
    "x": 1541.59,
    "y": 1751.07,
    "width": 60,
    "height": 60,
    "curr_hp": 3,
    "endedTurn": false,
    "src": ""
  },
  {
    "id": 152,
    "type": "shape",
    "name": "Кристалл_души",
    "shape": "custom",
    "color": "#d3d3d3",
    "x": 1039.58,
    "y": 1777.89,
    "width": 60,
    "height": 60,
    "curr_hp": 3,
    "endedTurn": false,
    "src": ""
  },
  {
    "id": 153,
    "type": "shape",
    "name": "Кристалл_души",
    "shape": "custom",
    "color": "#d3d3d3",
    "x": 2372.38,
    "y": 1391.85,
    "width": 60,
    "height": 60,
    "curr_hp": 3,
    "endedTurn": false,
    "src": ""
  },
  {
    "id": 154,
    "type": "shape",
    "name": "Кровать",
    "shape": "custom",
    "color": "#d3d3d3",
    "x": 3364.51,
    "y": 1914.56,
    "width": 60,
    "height": 60,
    "curr_hp": 3,
    "endedTurn": false
  },
  {
    "id": 155,
    "type": "shape",
    "name": "Кровать",
    "shape": "custom",
    "color": "#d3d3d3",
    "x": 3266.95,
    "y": 1916.6,
    "width": 60,
    "height": 60,
    "curr_hp": 3,
    "endedTurn": false
  },
  {
    "id": 156,
    "type": "shape",
    "name": "Кровать",
    "shape": "custom",
    "color": "#d3d3d3",
    "x": 3359.47,
    "y": 1114.07,
    "width": 60,
    "height": 60,
    "curr_hp": 3,
    "endedTurn": false
  },
  {
    "id": 157,
    "type": "shape",
    "name": "Кровать",
    "shape": "custom",
    "color": "#d3d3d3",
    "x": 3461.27,
    "y": 1117.66,
    "width": 60,
    "height": 60,
    "curr_hp": 3,
    "endedTurn": false
  },
  {
    "id": 159,
    "type": "shape",
    "name": "Демон-диверсант",
    "shape": "custom",
    "color": "#d3d3d3",
    "x": 3763.96,
    "y": 2165.7,
    "width": 60,
    "height": 60,
    "curr_hp": 4,
    "endedTurn": false,
    "title": "Двиг2",
    "src": ""
  },
  {
    "id": 160,
    "type": "shape",
    "name": "Звёздный_зомби",
    "shape": "custom",
    "color": "#930000",
    "x": 2283.86,
    "y": 1289.96,
    "width": 60,
    "height": 60,
    "curr_hp": 3,
    "endedTurn": false,
    "title": "Биомант",
    "src": ""
  },
  {
    "id": 161,
    "type": "shape",
    "name": "_могила",
    "shape": "custom",
    "color": "#930000",
    "x": 3650.35,
    "y": 1271.41,
    "width": 60,
    "height": 60,
    "curr_hp": 0,
    "endedTurn": false,
    "title": "Кровь"
  },
  {
    "id": 162,
    "type": "shape",
    "name": "Кровать",
    "shape": "custom",
    "color": "#d3d3d3",
    "x": 3560.47,
    "y": 1114.89,
    "width": 60,
    "height": 60,
    "curr_hp": 3,
    "endedTurn": false
  },
  {
    "id": 163,
    "type": "shape",
    "name": "Кровать",
    "shape": "custom",
    "color": "#d3d3d3",
    "x": 3466.95,
    "y": 1917.25,
    "width": 60,
    "height": 60,
    "curr_hp": 3,
    "endedTurn": false
  },
  {
    "id": 164,
    "type": "shape",
    "name": "Контрольное_кресло",
    "shape": "custom",
    "color": "#d3d3d3",
    "x": 888.33,
    "y": 1509.94,
    "width": 60,
    "height": 60,
    "curr_hp": 3,
    "endedTurn": false,
    "title": "Капитан"
  },
  {
    "id": 165,
    "type": "shape",
    "name": "Контрольное_кресло",
    "shape": "custom",
    "color": "#d3d3d3",
    "x": 983.58,
    "y": 1409.76,
    "width": 60,
    "height": 60,
    "curr_hp": 3,
    "endedTurn": false,
    "title": "Старпом"
  },
  {
    "id": 166,
    "type": "shape",
    "name": "Контрольное_кресло",
    "shape": "custom",
    "color": "#d3d3d3",
    "x": 1080.65,
    "y": 1407.86,
    "width": 60,
    "height": 60,
    "curr_hp": 3,
    "endedTurn": false,
    "title": "Начтех"
  },
  {
    "id": 167,
    "type": "shape",
    "name": "Контрольное_кресло",
    "shape": "custom",
    "color": "#d3d3d3",
    "x": 979.46,
    "y": 1606.97,
    "width": 60,
    "height": 60,
    "curr_hp": 3,
    "endedTurn": false,
    "title": "Навигатор"
  },
  {
    "id": 168,
    "type": "shape",
    "name": "Контрольное_кресло",
    "shape": "custom",
    "color": "#d3d3d3",
    "x": 1983.9,
    "y": 1710.57,
    "width": 60,
    "height": 60,
    "curr_hp": 3,
    "endedTurn": false,
    "title": "Контроль"
  },
  {
    "id": 169,
    "type": "shape",
    "name": "Контрольное_кресло",
    "shape": "custom",
    "color": "#d3d3d3",
    "x": 1987.15,
    "y": 698.37,
    "width": 60,
    "height": 60,
    "curr_hp": 3,
    "endedTurn": false,
    "title": "Контроль"
  },
  {
    "id": 170,
    "type": "shape",
    "name": "Контрольное_кресло",
    "shape": "custom",
    "color": "#d3d3d3",
    "x": 1487.51,
    "y": 697.25,
    "width": 60,
    "height": 60,
    "curr_hp": 3,
    "endedTurn": false
  },
  {
    "id": 171,
    "type": "shape",
    "name": "Контрольное_кресло",
    "shape": "custom",
    "color": "#d3d3d3",
    "x": 1484.99,
    "y": 902.82,
    "width": 60,
    "height": 60,
    "curr_hp": 3,
    "endedTurn": false
  },
  {
    "id": 172,
    "type": "shape",
    "name": "Контрольное_кресло",
    "shape": "custom",
    "color": "#d3d3d3",
    "x": 1995.03,
    "y": 608.6,
    "width": 60,
    "height": 60,
    "curr_hp": 3,
    "endedTurn": false
  },
  {
    "id": 173,
    "type": "shape",
    "name": "Контрольное_кресло",
    "shape": "custom",
    "color": "#d3d3d3",
    "x": 3402.14,
    "y": 1605.83,
    "width": 60,
    "height": 60,
    "curr_hp": 3,
    "endedTurn": false,
    "title": "Контроль"
  },
  {
    "id": 174,
    "type": "shape",
    "name": "Контрольное_кресло",
    "shape": "custom",
    "color": "#d3d3d3",
    "x": 3398.73,
    "y": 1712.41,
    "width": 60,
    "height": 60,
    "curr_hp": 3,
    "endedTurn": false
  },
  {
    "id": 175,
    "type": "shape",
    "name": "Контрольное_кресло",
    "shape": "custom",
    "color": "#d3d3d3",
    "x": 2992.82,
    "y": 1202.62,
    "width": 60,
    "height": 60,
    "curr_hp": 3,
    "endedTurn": false,
    "title": "Контроль"
  },
  {
    "id": 176,
    "type": "shape",
    "name": "Контрольное_кресло",
    "shape": "custom",
    "color": "#d3d3d3",
    "x": 2391.59,
    "y": 1306.02,
    "width": 60,
    "height": 60,
    "curr_hp": 3,
    "endedTurn": false,
    "title": "Биомант"
  },
  {
    "id": 177,
    "type": "shape",
    "name": "Контрольное_кресло",
    "shape": "custom",
    "color": "#d3d3d3",
    "x": 2991.96,
    "y": 1714.01,
    "width": 60,
    "height": 60,
    "curr_hp": 3,
    "endedTurn": false,
    "title": "Астроном"
  },
  {
    "id": 178,
    "type": "shape",
    "name": "Контрольное_кресло",
    "shape": "custom",
    "color": "#d3d3d3",
    "x": 2796.64,
    "y": 1711.68,
    "width": 60,
    "height": 60,
    "curr_hp": 3,
    "endedTurn": false
  },
  {
    "id": 179,
    "type": "shape",
    "name": "Контрольное_кресло",
    "shape": "custom",
    "color": "#d3d3d3",
    "x": 2991.46,
    "y": 700.38,
    "width": 60,
    "height": 60,
    "curr_hp": 3,
    "endedTurn": false,
    "title": "Контроль"
  },
  {
    "id": 180,
    "type": "shape",
    "name": "Контрольное_кресло",
    "shape": "custom",
    "color": "#d3d3d3",
    "x": 3398.38,
    "y": 802.11,
    "width": 60,
    "height": 60,
    "curr_hp": 3,
    "endedTurn": false,
    "title": "Контроль"
  },
  {
    "id": 181,
    "type": "shape",
    "name": "Контрольное_кресло",
    "shape": "custom",
    "color": "#d3d3d3",
    "x": 4816.01,
    "y": 805.35,
    "width": 60,
    "height": 60,
    "curr_hp": 3,
    "endedTurn": false,
    "title": "Главный"
  },
  {
    "id": 182,
    "type": "shape",
    "name": "Контрольное_кресло",
    "shape": "custom",
    "color": "#d3d3d3",
    "x": 4711.85,
    "y": 1102.04,
    "width": 60,
    "height": 60,
    "curr_hp": 3,
    "endedTurn": false,
    "title": "Резервный"
  },
  {
    "id": 183,
    "type": "shape",
    "name": "Контрольное_кресло",
    "shape": "custom",
    "color": "#d3d3d3",
    "x": 4815.96,
    "y": 2202.55,
    "width": 60,
    "height": 60,
    "curr_hp": 3,
    "endedTurn": false,
    "title": "Главный"
  },
  {
    "id": 184,
    "type": "shape",
    "name": "Контрольное_кресло",
    "shape": "custom",
    "color": "#d3d3d3",
    "x": 4715.38,
    "y": 1915.35,
    "width": 60,
    "height": 60,
    "curr_hp": 3,
    "endedTurn": false,
    "title": "Резервный"
  },
  {
    "id": 186,
    "type": "shape",
    "name": "Контрольное_кресло",
    "shape": "custom",
    "color": "#d3d3d3",
    "x": 3796.84,
    "y": 2218.19,
    "width": 60,
    "height": 60,
    "curr_hp": 3,
    "endedTurn": false,
    "title": "Контроль"
  },
  {
    "id": 187,
    "type": "shape",
    "name": "Контрольное_кресло",
    "shape": "custom",
    "color": "#d3d3d3",
    "x": 3803.22,
    "y": 803.18,
    "width": 60,
    "height": 60,
    "curr_hp": 3,
    "endedTurn": false,
    "title": "Контроль"
  },
  {
    "id": 188,
    "type": "shape",
    "name": "Контур_ответчик",
    "shape": "custom",
    "color": "#d3d3d3",
    "x": 1361.45,
    "y": 788.87,
    "width": 60,
    "height": 60,
    "curr_hp": 3,
    "endedTurn": false
  },
  {
    "id": 189,
    "type": "shape",
    "name": "Кровь_колодца",
    "shape": "custom",
    "color": "#d3d3d3",
    "x": 3788.15,
    "y": 2006.2,
    "width": 60,
    "height": 60,
    "curr_hp": 3,
    "endedTurn": false,
    "src": ""
  },
  {
    "id": 190,
    "type": "shape",
    "name": "Кровь_колодца",
    "shape": "custom",
    "color": "#d3d3d3",
    "x": 3685.49,
    "y": 2202.6,
    "width": 60,
    "height": 60,
    "curr_hp": 3,
    "endedTurn": false
  },
  {
    "id": 191,
    "type": "shape",
    "name": "Кровь_колодца",
    "shape": "custom",
    "color": "#d3d3d3",
    "x": 3884.71,
    "y": 2298.84,
    "width": 60,
    "height": 60,
    "curr_hp": 3,
    "endedTurn": false,
    "src": ""
  },
  {
    "id": 192,
    "type": "shape",
    "name": "Кровь_колодца",
    "shape": "custom",
    "color": "#d3d3d3",
    "x": 3684.53,
    "y": 2300.77,
    "width": 60,
    "height": 60,
    "curr_hp": 3,
    "endedTurn": false
  },
  {
    "id": 193,
    "type": "shape",
    "name": "Кровь_колодца",
    "shape": "custom",
    "color": "#d3d3d3",
    "x": 3688.38,
    "y": 2402.78,
    "width": 60,
    "height": 60,
    "curr_hp": 3,
    "endedTurn": false
  },
  {
    "id": 194,
    "type": "shape",
    "name": "Кровь_колодца",
    "shape": "custom",
    "color": "#d3d3d3",
    "x": 3787.5085798984846,
    "y": 2399.8957015353426,
    "width": 60,
    "height": 60,
    "curr_hp": 3,
    "endedTurn": false
  },
  {
    "id": 195,
    "type": "shape",
    "name": "Кровь_колодца",
    "shape": "custom",
    "color": "#d3d3d3",
    "x": 3887.6,
    "y": 2398.93,
    "width": 60,
    "height": 60,
    "curr_hp": 3,
    "endedTurn": false
  },
  {
    "id": 197,
    "type": "shape",
    "name": "Душевидец",
    "shape": "custom",
    "color": "#d3d3d3",
    "x": 3991.98,
    "y": 685.63,
    "width": 60,
    "height": 60,
    "curr_hp": 3,
    "endedTurn": false
  },
  {
    "id": 198,
    "type": "shape",
    "name": "Контрольное_кресло",
    "shape": "custom",
    "color": "#d3d3d3",
    "x": 4005.12,
    "y": 800.08,
    "width": 60,
    "height": 60,
    "curr_hp": 3,
    "endedTurn": false,
    "title": "Душевидец"
  },
  {
    "id": 200,
    "type": "shape",
    "name": "Кристалл_души",
    "shape": "custom",
    "color": "#d3d3d3",
    "x": 3563.57,
    "y": 868.03,
    "width": 60,
    "height": 60,
    "curr_hp": 3,
    "endedTurn": false,
    "src": ""
  },
  {
    "id": 201,
    "type": "shape",
    "name": "Кристалл_души",
    "shape": "custom",
    "color": "#d3d3d3",
    "x": 1736.8,
    "y": 1675.62,
    "width": 60,
    "height": 60,
    "curr_hp": 3,
    "endedTurn": false,
    "src": ""
  },
  {
    "id": 202,
    "type": "shape",
    "name": "Кристалл_души",
    "shape": "custom",
    "color": "#d3d3d3",
    "x": 3159.78,
    "y": 761.25,
    "width": 60,
    "height": 60,
    "curr_hp": 3,
    "endedTurn": false,
    "src": ""
  },
  {
    "id": 203,
    "type": "shape",
    "name": "Кристалл_души",
    "shape": "custom",
    "color": "#d3d3d3",
    "x": 2753.99,
    "y": 1166.68,
    "width": 60,
    "height": 60,
    "curr_hp": 3,
    "endedTurn": false,
    "src": ""
  },
  {
    "id": 204,
    "type": "shape",
    "name": "Кровать",
    "shape": "custom",
    "color": "#d3d3d3",
    "x": 1256.65,
    "y": 1816.11,
    "width": 60,
    "height": 60,
    "curr_hp": 3,
    "endedTurn": false
  },
  {
    "id": 205,
    "type": "shape",
    "name": "Кровать",
    "shape": "custom",
    "color": "#d3d3d3",
    "x": 1354.83,
    "y": 1812.18,
    "width": 60,
    "height": 60,
    "curr_hp": 3,
    "endedTurn": false
  },
  {
    "id": 206,
    "type": "shape",
    "name": "Кровать",
    "shape": "custom",
    "color": "#d3d3d3",
    "x": 1445.55,
    "y": 1816.18,
    "width": 60,
    "height": 60,
    "curr_hp": 3,
    "endedTurn": false
  },
  {
    "id": 207,
    "type": "shape",
    "name": "Контрольное_кресло",
    "shape": "custom",
    "color": "#d3d3d3",
    "x": 2996.6,
    "y": 1313.19,
    "width": 60,
    "height": 60,
    "curr_hp": 3,
    "endedTurn": false
  },
  {
    "id": 208,
    "type": "shape",
    "name": "Контрольное_кресло",
    "shape": "custom",
    "color": "#d3d3d3",
    "x": 2797.27,
    "y": 1112.65,
    "width": 60,
    "height": 60,
    "curr_hp": 3,
    "endedTurn": false
  },
  {
    "id": 209,
    "type": "shape",
    "name": "_могила",
    "shape": "custom",
    "color": "#930000",
    "x": 4457.41,
    "y": 833.54,
    "width": 60,
    "height": 60,
    "src": "",
    "curr_hp": 0,
    "endedTurn": false,
    "title": "Штурм2"
  },
  {
    "id": 210,
    "type": "shape",
    "name": "_могила",
    "shape": "custom",
    "color": "#930000",
    "x": 4197.66,
    "y": 902.72,
    "width": 60,
    "height": 60,
    "curr_hp": 0,
    "endedTurn": false,
    "title": "НачБез"
  },
  {
    "id": 211,
    "type": "shape",
    "name": "Звёздный_зомби",
    "shape": "custom",
    "color": "#930000",
    "x": 2658.16,
    "y": 1192.49,
    "width": 60,
    "height": 60,
    "curr_hp": 3,
    "endedTurn": false,
    "title": "Штурм3",
    "src": ""
  },
  {
    "id": 213,
    "type": "shape",
    "name": "Кровать",
    "shape": "custom",
    "color": "#d3d3d3",
    "x": 3669.91,
    "y": 1112.37,
    "width": 60,
    "height": 60,
    "curr_hp": 3,
    "endedTurn": false
  },
  {
    "id": 214,
    "type": "shape",
    "name": "Контрольное_кресло",
    "shape": "custom",
    "color": "#d3d3d3",
    "x": 1093.86,
    "y": 1610.47,
    "width": 60,
    "height": 60,
    "curr_hp": 3,
    "endedTurn": false,
    "title": "НачБез"
  },
  {
    "id": 215,
    "type": "shape",
    "name": "Звёздный_зомби",
    "shape": "custom",
    "color": "#930000",
    "x": 1778.85,
    "y": 1221.11,
    "width": 60,
    "height": 60,
    "curr_hp": 3,
    "endedTurn": false,
    "title": "Штурм1",
    "src": ""
  },
  {
    "id": 216,
    "type": "shape",
    "name": "Звёздный_зомби",
    "shape": "custom",
    "color": "#930000",
    "x": 2947.41,
    "y": 1272.73,
    "width": 60,
    "height": 60,
    "curr_hp": 3,
    "endedTurn": false,
    "title": "Штурм4",
    "src": ""
  },
  {
    "id": 218,
    "type": "shape",
    "name": "Дерево",
    "shape": "custom",
    "color": "#d3d3d3",
    "x": 2279.42,
    "y": 1186.85,
    "width": 60,
    "height": 60,
    "curr_hp": 3,
    "endedTurn": false
  },
  {
    "id": 219,
    "type": "shape",
    "name": "Дерево",
    "shape": "custom",
    "color": "#d3d3d3",
    "x": 2178.3,
    "y": 1100.97,
    "width": 60,
    "height": 60,
    "curr_hp": 3,
    "endedTurn": false
  },
  {
    "id": 220,
    "type": "shape",
    "name": "Дерево",
    "shape": "custom",
    "color": "#d3d3d3",
    "x": 2179.69,
    "y": 1286.59,
    "width": 60,
    "height": 60,
    "curr_hp": 3,
    "endedTurn": false
  },
  {
    "id": 221,
    "type": "shape",
    "name": "Дерево",
    "shape": "custom",
    "color": "#d3d3d3",
    "x": 2182.46,
    "y": 1393.25,
    "width": 60,
    "height": 60,
    "curr_hp": 3,
    "endedTurn": false
  },
  {
    "id": 222,
    "type": "shape",
    "name": "Дерево",
    "shape": "custom",
    "color": "#d3d3d3",
    "x": 2577.24,
    "y": 1195.16,
    "width": 60,
    "height": 60,
    "curr_hp": 3,
    "endedTurn": false
  },
  {
    "id": 223,
    "type": "shape",
    "name": "Дерево",
    "shape": "custom",
    "color": "#d3d3d3",
    "x": 2578.62,
    "y": 1393.25,
    "width": 60,
    "height": 60,
    "curr_hp": 3,
    "endedTurn": false
  },
  {
    "id": 224,
    "type": "shape",
    "name": "Дерево",
    "shape": "custom",
    "color": "#d3d3d3",
    "x": 2581.39,
    "y": 1091.28,
    "width": 60,
    "height": 60,
    "curr_hp": 3,
    "endedTurn": false
  },
  {
    "id": 225,
    "type": "shape",
    "name": "Дерево",
    "shape": "custom",
    "color": "#d3d3d3",
    "x": 2477.5,
    "y": 1103.74,
    "width": 60,
    "height": 60,
    "curr_hp": 3,
    "endedTurn": false
  },
  {
    "id": 226,
    "type": "shape",
    "name": "Голем_паук",
    "shape": "custom",
    "color": "#930000",
    "x": 2465.49,
    "y": 1294.02,
    "width": 80,
    "height": 80,
    "curr_hp": 3,
    "endedTurn": false
  },
  {
    "id": 229,
    "type": "shape",
    "name": "Дыхательная_маска",
    "shape": "custom",
    "color": "#d3d3d3",
    "x": 2355.78,
    "y": 975.36,
    "width": 40,
    "height": 40,
    "curr_hp": 1,
    "endedTurn": false
  },
  {
    "id": 230,
    "type": "shape",
    "name": "Дыхательная_маска",
    "shape": "custom",
    "color": "#d3d3d3",
    "x": 2355.03,
    "y": 1021.67,
    "width": 40,
    "height": 40,
    "curr_hp": 1,
    "endedTurn": false
  },
  {
    "id": 235,
    "type": "shape",
    "name": "Инъектор_подавления",
    "shape": "custom",
    "color": "#d3d3d3",
    "x": 3822.74,
    "y": 2078.57,
    "width": 40,
    "height": 40,
    "curr_hp": 1,
    "endedTurn": false
  },
  {
    "id": 238,
    "type": "shape",
    "name": "Инъектор_подавления",
    "shape": "custom",
    "color": "#d3d3d3",
    "x": 2767.25,
    "y": 822.18,
    "width": 40,
    "height": 40,
    "curr_hp": 1,
    "endedTurn": false
  },
  {
    "id": 240,
    "type": "shape",
    "name": "Аварийный_накопитель",
    "shape": "custom",
    "color": "#d3d3d3",
    "x": 3418.22,
    "y": 880.94,
    "width": 40,
    "height": 40,
    "curr_hp": 1,
    "endedTurn": false
  },
  {
    "id": 241,
    "type": "shape",
    "name": "Ремонтный_набор",
    "shape": "custom",
    "color": "#d3d3d3",
    "x": 3414.96,
    "y": 926.04,
    "width": 40,
    "height": 40,
    "curr_hp": 1,
    "endedTurn": false
  },
  {
    "id": 242,
    "type": "shape",
    "name": "Кровемёт",
    "shape": "custom",
    "color": "#d3d3d3",
    "x": 4005.52,
    "y": 2197.41,
    "width": 40,
    "height": 40,
    "curr_hp": 1,
    "endedTurn": false,
    "lvl": 5
  },
  {
    "id": 246,
    "type": "shape",
    "name": "Кровемёт",
    "shape": "custom",
    "color": "#d3d3d3",
    "x": 4261.38,
    "y": 867.3,
    "width": 40,
    "height": 40,
    "curr_hp": 1,
    "endedTurn": false,
    "lvl": 5
  },
  {
    "id": 247,
    "type": "shape",
    "name": "Кровемёт",
    "shape": "custom",
    "color": "#d3d3d3",
    "x": 4006.23,
    "y": 2280.15,
    "width": 40,
    "height": 40,
    "curr_hp": 1,
    "endedTurn": false,
    "lvl": 5
  },
  {
    "id": 248,
    "type": "shape",
    "name": "Кровемёт",
    "shape": "custom",
    "color": "#d3d3d3",
    "x": 3821.19,
    "y": 2119.21,
    "width": 40,
    "height": 40,
    "curr_hp": 1,
    "endedTurn": false,
    "lvl": 3
  },
  {
    "id": 250,
    "type": "shape",
    "name": "Спиритический_микрофон",
    "shape": "custom",
    "color": "#d3d3d3",
    "x": 3070.5,
    "y": 792.89,
    "width": 40,
    "height": 40,
    "curr_hp": 1,
    "endedTurn": false
  },
  {
    "id": 251,
    "type": "shape",
    "name": "Кристалл_души",
    "shape": "custom",
    "color": "#d3d3d3",
    "x": 3216.35,
    "y": 785.34,
    "width": 40,
    "height": 40,
    "curr_hp": 1,
    "endedTurn": false
  },
  {
    "id": 256,
    "type": "shape",
    "name": "Ремонтный_набор",
    "shape": "custom",
    "color": "#d3d3d3",
    "x": 4682.96,
    "y": 706.49,
    "width": 40,
    "height": 40,
    "curr_hp": 1,
    "endedTurn": false
  },
  {
    "id": 257,
    "type": "shape",
    "name": "Коагулянт-гель",
    "shape": "custom",
    "color": "#d3d3d3",
    "x": 3778.2,
    "y": 2057.98,
    "width": 40,
    "height": 40,
    "curr_hp": 1,
    "endedTurn": false
  },
  {
    "id": 258,
    "type": "shape",
    "name": "Коагулянт-гель",
    "shape": "custom",
    "color": "#d3d3d3",
    "x": 3970.98,
    "y": 1078.45,
    "width": 40,
    "height": 40,
    "curr_hp": 1,
    "endedTurn": false
  },
  {
    "id": 263,
    "type": "shape",
    "name": "Скрижаль",
    "shape": "custom",
    "color": "#d3d3d3",
    "x": 3888.33,
    "y": 580.3,
    "width": 60,
    "height": 60,
    "curr_hp": 1,
    "endedTurn": false,
    "title": "Имя"
  },
  {
    "id": 264,
    "type": "shape",
    "name": "Скрижаль",
    "shape": "custom",
    "color": "#d3d3d3",
    "x": 3684,
    "y": 581.45,
    "width": 60,
    "height": 60,
    "curr_hp": 1,
    "endedTurn": false,
    "title": "Стасис"
  },
  {
    "id": 265,
    "type": "shape",
    "name": "Скрижаль",
    "shape": "custom",
    "color": "#d3d3d3",
    "x": 3612.92,
    "y": 595.28,
    "width": 60,
    "height": 60,
    "curr_hp": 1,
    "endedTurn": false,
    "title": "Увядание"
  },
  {
    "id": 266,
    "type": "shape",
    "name": "Скрижаль",
    "shape": "custom",
    "color": "#d3d3d3",
    "x": 3565.53,
    "y": 559.84,
    "width": 60,
    "height": 60,
    "curr_hp": 1,
    "endedTurn": false,
    "title": "Разряд"
  },
  {
    "id": 269,
    "type": "shape",
    "name": "Кристалл_души",
    "shape": "custom",
    "color": "#d3d3d3",
    "x": 4050.96,
    "y": 888.4,
    "width": 40,
    "height": 40,
    "curr_hp": 1,
    "endedTurn": false
  },
  {
    "id": 270,
    "type": "shape",
    "name": "Парализующий_амулет",
    "shape": "custom",
    "color": "#d3d3d3",
    "x": 4067.62,
    "y": 928.45,
    "width": 40,
    "height": 40,
    "curr_hp": 1,
    "endedTurn": false
  },
  {
    "id": 273,
    "type": "shape",
    "name": "Ремонтный_набор",
    "shape": "custom",
    "color": "#d3d3d3",
    "x": 3257.6,
    "y": 1680.82,
    "width": 40,
    "height": 40,
    "curr_hp": 1,
    "endedTurn": false
  },
  {
    "id": 274,
    "type": "shape",
    "name": "Аварийный_накопитель",
    "shape": "custom",
    "color": "#d3d3d3",
    "x": 3690.63,
    "y": 2119.62,
    "width": 40,
    "height": 40,
    "curr_hp": 1,
    "endedTurn": false
  },
  {
    "id": 277,
    "type": "shape",
    "name": "Инъектор_подавления",
    "shape": "custom",
    "color": "#d3d3d3",
    "x": 2005.79,
    "y": 777.76,
    "width": 40,
    "height": 40,
    "curr_hp": 1,
    "endedTurn": false
  },
  {
    "id": 278,
    "type": "shape",
    "name": "Скрижаль",
    "shape": "custom",
    "color": "#d3d3d3",
    "x": 2276.62,
    "y": 1386.51,
    "width": 60,
    "height": 60,
    "curr_hp": 1,
    "endedTurn": false,
    "title": "Увядание"
  },
  {
    "id": 280,
    "type": "shape",
    "name": "Инъектор_подавления",
    "shape": "custom",
    "color": "#d3d3d3",
    "x": 1603.73,
    "y": 726.03,
    "width": 40,
    "height": 40,
    "curr_hp": 1,
    "endedTurn": false
  },
  {
    "id": 282,
    "type": "shape",
    "name": "Коагулянт-гель",
    "shape": "custom",
    "color": "#d3d3d3",
    "x": 2758.4892993017465,
    "y": 1581.2877170607464,
    "width": 40,
    "height": 40,
    "curr_hp": 1,
    "endedTurn": false
  },
  {
    "id": 285,
    "type": "shape",
    "name": "Коагулянт-гель",
    "shape": "custom",
    "color": "#d3d3d3",
    "x": 1870.45,
    "y": 1372.46,
    "width": 40,
    "height": 40,
    "curr_hp": 1,
    "endedTurn": false
  },
  {
    "id": 289,
    "type": "shape",
    "name": "Переносной_Алтарь",
    "shape": "custom",
    "color": "#d3d3d3",
    "x": 3372.256840434497,
    "y": 922.7169762486143,
    "width": 40,
    "height": 40,
    "curr_hp": 1,
    "endedTurn": false
  },
  {
    "id": 290,
    "type": "shape",
    "name": "Аварийный_накопитель",
    "shape": "custom",
    "color": "#d3d3d3",
    "x": 3739.59,
    "y": 2125.2,
    "width": 40,
    "height": 40,
    "curr_hp": 1,
    "endedTurn": false
  },
  {
    "id": 291,
    "type": "shape",
    "name": "Аварийный_накопитель",
    "shape": "custom",
    "color": "#d3d3d3",
    "x": 1604.31,
    "y": 1541.64,
    "width": 40,
    "height": 40,
    "curr_hp": 1,
    "endedTurn": false,
    "src": ""
  },
  {
    "id": 292,
    "type": "shape",
    "name": "Дыхательная_маска",
    "shape": "custom",
    "color": "#d3d3d3",
    "x": 2007.26,
    "y": 1286.09,
    "width": 40,
    "height": 40,
    "curr_hp": 1,
    "endedTurn": false
  },
  {
    "id": 293,
    "type": "shape",
    "name": "Дыхательная_маска",
    "shape": "custom",
    "color": "#d3d3d3",
    "x": 2815.75,
    "y": 1331.19,
    "width": 40,
    "height": 40,
    "curr_hp": 1,
    "endedTurn": false
  },
  {
    "id": 294,
    "type": "shape",
    "name": "Парализующий_амулет",
    "shape": "custom",
    "color": "#d3d3d3",
    "x": 2771.82,
    "y": 1286.58,
    "width": 40,
    "height": 40,
    "curr_hp": 1,
    "endedTurn": false
  },
  {
    "id": 295,
    "type": "shape",
    "name": "Коагулянт-гель",
    "shape": "custom",
    "color": "#d3d3d3",
    "x": 2774.58,
    "y": 1329.28,
    "width": 40,
    "height": 40,
    "curr_hp": 1,
    "endedTurn": false
  },
  {
    "id": 296,
    "type": "shape",
    "name": "Инъектор_подавления",
    "shape": "custom",
    "color": "#d3d3d3",
    "x": 2417.26,
    "y": 1027.22,
    "width": 40,
    "height": 40,
    "curr_hp": 1,
    "endedTurn": false
  },
  {
    "id": 300,
    "type": "shape",
    "name": "Спиритический_микрофон",
    "shape": "custom",
    "color": "#d3d3d3",
    "x": 1591.2,
    "y": 1829.64,
    "width": 40,
    "height": 40,
    "curr_hp": 1,
    "endedTurn": false
  },
  {
    "id": 303,
    "type": "shape",
    "name": "Кровемёт",
    "shape": "custom",
    "color": "#d3d3d3",
    "x": 3727.57,
    "y": 2077.04,
    "width": 40,
    "height": 40,
    "curr_hp": 1,
    "endedTurn": false,
    "lvl": 3
  },
  {
    "id": 304,
    "type": "shape",
    "name": "Кровемёт",
    "shape": "custom",
    "color": "#d3d3d3",
    "x": 3959.37,
    "y": 2131.24,
    "width": 40,
    "height": 40,
    "curr_hp": 1,
    "endedTurn": false,
    "lvl": 2
  },
  {
    "id": 309,
    "type": "shape",
    "name": "Копир-скрижаль",
    "shape": "custom",
    "color": "#d3d3d3",
    "x": 3561.55,
    "y": 809.14,
    "width": 60,
    "height": 60,
    "curr_hp": 1,
    "endedTurn": false
  },
  {
    "id": 310,
    "type": "shape",
    "name": "Копир-скрижаль",
    "shape": "custom",
    "color": "#d3d3d3",
    "x": 3910.16,
    "y": 872.34,
    "width": 60,
    "height": 60,
    "curr_hp": 1,
    "endedTurn": false
  },
  {
    "id": 312,
    "type": "shape",
    "name": "Копир-скрижаль",
    "shape": "custom",
    "color": "#d3d3d3",
    "x": 3666.28,
    "y": 910.91,
    "width": 60,
    "height": 60,
    "curr_hp": 1,
    "endedTurn": false
  },
  {
    "id": 313,
    "type": "shape",
    "name": "Копир-скрижаль",
    "shape": "custom",
    "color": "#d3d3d3",
    "x": 3708.56,
    "y": 870.06,
    "width": 60,
    "height": 60,
    "curr_hp": 1,
    "endedTurn": false
  },
  {
    "id": 314,
    "type": "shape",
    "name": "Копир-скрижаль",
    "shape": "custom",
    "color": "#d3d3d3",
    "x": 3863.62,
    "y": 912.86,
    "width": 60,
    "height": 60,
    "curr_hp": 1,
    "endedTurn": false
  },
  {
    "id": 315,
    "type": "shape",
    "name": "Скрижаль",
    "shape": "custom",
    "color": "#d3d3d3",
    "x": 3794.23,
    "y": 579.18,
    "width": 60,
    "height": 60,
    "curr_hp": 1,
    "endedTurn": false,
    "title": "Отвод глаз"
  },
  {
    "id": 316,
    "type": "shape",
    "name": "Копир-скрижаль",
    "shape": "custom",
    "color": "#d3d3d3",
    "x": 3609.03,
    "y": 768.37,
    "width": 60,
    "height": 60,
    "curr_hp": 1,
    "endedTurn": false
  },
  {
    "id": 317,
    "type": "shape",
    "name": "Обзор",
    "shape": "custom",
    "color": "#d3d3d3",
    "x": 3920.01,
    "y": 657.25,
    "width": 60,
    "height": 60,
    "curr_hp": 3,
    "endedTurn": false,
    "src": ""
  },
  {
    "id": 322,
    "type": "shape",
    "name": "Тень_Усопшего",
    "shape": "custom",
    "color": "#930000",
    "x": 1764.06,
    "y": 585.48,
    "width": 60,
    "height": 60,
    "src": "",
    "curr_hp": 2,
    "endedTurn": false
  },
  {
    "id": 325,
    "type": "shape",
    "name": "Тень_Усопшего",
    "shape": "custom",
    "color": "#930000",
    "x": 1585.26,
    "y": 1119.21,
    "width": 60,
    "height": 60,
    "src": "",
    "curr_hp": 3,
    "endedTurn": false
  },
  {
    "id": 326,
    "type": "shape",
    "name": "Тень_Усопшего",
    "shape": "custom",
    "color": "#930000",
    "x": 3806.94,
    "y": 1306.63,
    "width": 60,
    "height": 60,
    "src": "",
    "curr_hp": 3,
    "endedTurn": false
  },
  {
    "id": 329,
    "type": "shape",
    "name": "Тень_Усопшего",
    "shape": "custom",
    "color": "#930000",
    "x": 1985.9,
    "y": 1650.87,
    "width": 60,
    "height": 60,
    "src": "",
    "curr_hp": 3,
    "endedTurn": false
  },
  {
    "id": 332,
    "type": "shape",
    "name": "Тень_Усопшего",
    "shape": "custom",
    "color": "#930000",
    "x": 3545.34,
    "y": 1305.26,
    "width": 60,
    "height": 60,
    "src": "",
    "curr_hp": 3,
    "endedTurn": false
  },
  {
    "id": 334,
    "type": "shape",
    "name": "Тень_Усопшего",
    "shape": "custom",
    "color": "#930000",
    "x": 2401.15,
    "y": 1112.24,
    "width": 60,
    "height": 60,
    "curr_hp": 3,
    "endedTurn": false,
    "src": ""
  },
  {
    "id": 335,
    "type": "shape",
    "name": "Тень_Усопшего",
    "shape": "custom",
    "color": "#930000",
    "x": 1103.36,
    "y": 1507.3,
    "width": 60,
    "height": 60,
    "src": "",
    "curr_hp": 3,
    "endedTurn": false
  },
  {
    "id": 336,
    "type": "shape",
    "name": "Тень_Усопшего",
    "shape": "custom",
    "color": "#930000",
    "x": 1393.34,
    "y": 866.21,
    "width": 60,
    "height": 60,
    "curr_hp": 3,
    "endedTurn": false
  },
  {
    "id": 339,
    "type": "shape",
    "name": "Тень_Усопшего",
    "shape": "custom",
    "color": "#930000",
    "x": 2763.06,
    "y": 1081.84,
    "width": 60,
    "height": 60,
    "curr_hp": 3,
    "endedTurn": false,
    "src": ""
  },
  {
    "id": 340,
    "type": "shape",
    "name": "Тень_Усопшего",
    "shape": "custom",
    "color": "#930000",
    "x": 4212.06,
    "y": 1303.1,
    "width": 60,
    "height": 60,
    "curr_hp": 3,
    "endedTurn": false,
    "src": ""
  },
  {
    "id": 341,
    "type": "shape",
    "name": "Тень_Усопшего",
    "shape": "custom",
    "color": "#930000",
    "x": 1809.32,
    "y": 1378.68,
    "width": 60,
    "height": 60,
    "src": "",
    "curr_hp": 3,
    "endedTurn": false
  },
  {
    "id": 343,
    "type": "shape",
    "name": "Тень_Усопшего",
    "shape": "custom",
    "color": "#930000",
    "x": 1597.96,
    "y": 1466.27,
    "width": 60,
    "height": 60,
    "curr_hp": 3,
    "endedTurn": false
  },
  {
    "id": 344,
    "type": "shape",
    "name": "Тень_Усопшего",
    "shape": "custom",
    "color": "#930000",
    "x": 1418.21,
    "y": 1535.79,
    "width": 60,
    "height": 60,
    "curr_hp": 3,
    "endedTurn": false
  },
  {
    "id": 345,
    "type": "shape",
    "name": "Кристалл_души",
    "shape": "custom",
    "color": "#930000",
    "x": 1604.54,
    "y": 1166.87,
    "width": 60,
    "height": 60,
    "src": "",
    "curr_hp": 0,
    "endedTurn": false
  },
  {
    "id": 347,
    "type": "shape",
    "name": "Тень_Усопшего",
    "shape": "custom",
    "color": "#930000",
    "x": 3560,
    "y": 1888.48,
    "width": 60,
    "height": 60,
    "curr_hp": 3,
    "endedTurn": false,
    "src": ""
  },
  {
    "id": 349,
    "type": "shape",
    "name": "Тень_Усопшего",
    "shape": "custom",
    "color": "#930000",
    "x": 1574.48,
    "y": 1592.1,
    "width": 60,
    "height": 60,
    "curr_hp": 3,
    "endedTurn": false,
    "src": ""
  },
  {
    "id": 350,
    "type": "shape",
    "name": "Закрытая_дверь",
    "shape": "custom",
    "color": "#d3d3d3",
    "x": 1563.76,
    "y": 989.95,
    "width": 60,
    "height": 60,
    "curr_hp": 6,
    "endedTurn": false,
    "src": ""
  },
  {
    "id": 351,
    "type": "shape",
    "name": "Тень_Усопшего",
    "shape": "custom",
    "color": "#930000",
    "x": 3300.85,
    "y": 857.6,
    "width": 60,
    "height": 60,
    "src": "",
    "curr_hp": 3,
    "endedTurn": false
  },
  {
    "id": 352,
    "type": "shape",
    "name": "Тень_Усопшего",
    "shape": "custom",
    "color": "#930000",
    "x": 3420.01,
    "y": 1051,
    "width": 60,
    "height": 60,
    "curr_hp": 3,
    "endedTurn": false
  },
  {
    "id": 353,
    "type": "shape",
    "name": "Холодный_свет",
    "shape": "custom",
    "color": "#930000",
    "x": 3705.29,
    "y": 744.18,
    "width": 60,
    "height": 60,
    "curr_hp": 3,
    "endedTurn": false,
    "src": ""
  },
  {
    "id": 354,
    "type": "shape",
    "name": "Холодный_свет",
    "shape": "custom",
    "color": "#930000",
    "x": 2756.91,
    "y": 1762.75,
    "width": 60,
    "height": 60,
    "src": "",
    "curr_hp": 3,
    "endedTurn": false
  },
  {
    "id": 356,
    "type": "shape",
    "name": "Тень_Усопшего",
    "shape": "custom",
    "color": "#930000",
    "x": 3578.25,
    "y": 2280.29,
    "width": 60,
    "height": 60,
    "curr_hp": 3,
    "endedTurn": false
  },
  {
    "id": 358,
    "type": "shape",
    "name": "Тень_Усопшего",
    "shape": "custom",
    "color": "#930000",
    "x": 3582.49,
    "y": 640.5,
    "width": 60,
    "height": 60,
    "curr_hp": 3,
    "endedTurn": false
  },
  {
    "id": 359,
    "type": "shape",
    "name": "Тень_Усопшего",
    "shape": "custom",
    "color": "#930000",
    "x": 2793.48,
    "y": 680.6,
    "width": 60,
    "height": 60,
    "curr_hp": 3,
    "endedTurn": false
  },
  {
    "id": 360,
    "type": "shape",
    "name": "Тень_Усопшего",
    "shape": "custom",
    "color": "#930000",
    "x": 3066.49,
    "y": 1112.3,
    "width": 60,
    "height": 60,
    "curr_hp": 3,
    "endedTurn": false
  },
  {
    "id": 361,
    "type": "shape",
    "name": "Тень_Усопшего",
    "shape": "custom",
    "color": "#930000",
    "x": 4123.91,
    "y": 1020.69,
    "width": 60,
    "height": 60,
    "curr_hp": 3,
    "endedTurn": false
  },
  {
    "id": 365,
    "type": "shape",
    "name": "Тень_Усопшего",
    "shape": "custom",
    "color": "#930000",
    "x": 4613.82,
    "y": 1080.73,
    "width": 60,
    "height": 60,
    "curr_hp": 3,
    "endedTurn": false
  },
  {
    "id": 366,
    "type": "shape",
    "name": "Тень_Усопшего",
    "shape": "custom",
    "color": "#930000",
    "x": 4306.96,
    "y": 2109.78,
    "width": 60,
    "height": 60,
    "curr_hp": 3,
    "endedTurn": false,
    "src": ""
  },
  {
    "id": 367,
    "type": "shape",
    "name": "Тень_Усопшего",
    "shape": "custom",
    "color": "#930000",
    "x": 1944.74,
    "y": 1391.21,
    "width": 60,
    "height": 60,
    "curr_hp": 3,
    "endedTurn": false
  },
  {
    "id": 368,
    "type": "shape",
    "name": "Тень_Усопшего",
    "shape": "custom",
    "color": "#930000",
    "x": 1759.8,
    "y": 1370.04,
    "width": 60,
    "height": 60,
    "curr_hp": 3,
    "endedTurn": false
  },
  {
    "id": 369,
    "type": "shape",
    "name": "Тень_Усопшего",
    "shape": "custom",
    "color": "#930000",
    "x": 1039.65,
    "y": 1829.82,
    "width": 60,
    "height": 60,
    "curr_hp": 3,
    "endedTurn": false
  },
  {
    "id": 370,
    "type": "shape",
    "name": "Тень_Усопшего",
    "shape": "custom",
    "color": "#930000",
    "x": 1977.05,
    "y": 1335.27,
    "width": 60,
    "height": 60,
    "curr_hp": 3,
    "endedTurn": false
  },
  {
    "id": 372,
    "type": "shape",
    "name": "Коагулянт-гель",
    "shape": "custom",
    "color": "#d3d3d3",
    "x": 3116.8,
    "y": 799.21,
    "width": 40,
    "height": 40,
    "curr_hp": 1,
    "endedTurn": false
  },
  {
    "id": 385,
    "type": "shape",
    "name": "Закрытая_дверь",
    "shape": "custom",
    "color": "#d3d3d3",
    "x": 4493.47,
    "y": 2098.07,
    "width": 60,
    "height": 60,
    "curr_hp": 6,
    "endedTurn": false
  },
  {
    "id": 387,
    "type": "shape",
    "name": "Тень_Усопшего",
    "shape": "custom",
    "color": "#930000",
    "x": 1986.04,
    "y": 1404.3,
    "width": 60,
    "height": 60,
    "curr_hp": 3,
    "endedTurn": false
  },
  {
    "id": 388,
    "type": "shape",
    "name": "Тень_Усопшего",
    "shape": "custom",
    "color": "#930000",
    "x": 1641.26,
    "y": 1869.87,
    "width": 60,
    "height": 60,
    "curr_hp": 3,
    "endedTurn": false
  },
  {
    "id": 389,
    "type": "shape",
    "name": "Тень_Усопшего",
    "shape": "custom",
    "color": "#930000",
    "x": 1630.71,
    "y": 1600.59,
    "width": 60,
    "height": 60,
    "curr_hp": 3,
    "endedTurn": false
  },
  {
    "id": 390,
    "type": "shape",
    "name": "Тень_Усопшего",
    "shape": "custom",
    "color": "#930000",
    "x": 1483.21,
    "y": 1558.81,
    "width": 60,
    "height": 60,
    "curr_hp": 3,
    "endedTurn": false
  },
  {
    "id": 391,
    "type": "shape",
    "name": "Тень_Усопшего",
    "shape": "custom",
    "color": "#930000",
    "x": 3602.4,
    "y": 912.5,
    "width": 60,
    "height": 60,
    "curr_hp": 3,
    "endedTurn": false
  },
  {
    "id": 395,
    "type": "shape",
    "name": "Тень_Усопшего",
    "shape": "custom",
    "color": "#930000",
    "x": 2348.69,
    "y": 1128.07,
    "width": 60,
    "height": 60,
    "curr_hp": 3,
    "endedTurn": false
  },
  {
    "id": 396,
    "type": "shape",
    "name": "Закрытая_дверь",
    "shape": "custom",
    "color": "#d3d3d3",
    "x": 1693.88,
    "y": 1599.32,
    "width": 60,
    "height": 60,
    "src": "",
    "curr_hp": 6,
    "endedTurn": false
  },
  {
    "id": 398,
    "type": "shape",
    "name": "Закрытая_дверь",
    "shape": "custom",
    "color": "#d3d3d3",
    "x": 4593.21,
    "y": 1197.56,
    "width": 60,
    "height": 60,
    "curr_hp": 6,
    "endedTurn": false
  },
  {
    "id": 399,
    "type": "shape",
    "name": "Закрытая_дверь",
    "shape": "custom",
    "color": "#d3d3d3",
    "x": 3086.27,
    "y": 1597.27,
    "width": 60,
    "height": 60,
    "curr_hp": 6,
    "endedTurn": false
  },
  {
    "id": 410,
    "type": "shape",
    "name": "Тень_Усопшего",
    "shape": "custom",
    "color": "#930000",
    "x": 3878.7,
    "y": 1904.01,
    "width": 60,
    "height": 60,
    "curr_hp": 3,
    "endedTurn": false
  },
  {
    "id": 411,
    "type": "shape",
    "name": "Тень_Усопшего",
    "shape": "custom",
    "color": "#930000",
    "x": 3906.67,
    "y": 2139.91,
    "width": 60,
    "height": 60,
    "curr_hp": 3,
    "endedTurn": false
  },
  {
    "id": 412,
    "type": "shape",
    "name": "_могила",
    "shape": "custom",
    "color": "#930000",
    "x": 3391.88,
    "y": 1299.77,
    "width": 60,
    "height": 60,
    "curr_hp": 0,
    "endedTurn": false
  },
  {
    "id": 413,
    "type": "shape",
    "name": "Кристалл_души",
    "shape": "custom",
    "color": "#930000",
    "x": 3199.49,
    "y": 1334.05,
    "width": 60,
    "height": 60,
    "src": "",
    "curr_hp": 0,
    "endedTurn": false
  },
  {
    "id": 414,
    "type": "shape",
    "name": "Тень_Усопшего",
    "shape": "custom",
    "color": "#930000",
    "x": 4220.27,
    "y": 2105.35,
    "width": 60,
    "height": 60,
    "curr_hp": 3,
    "endedTurn": false
  },
  {
    "id": 418,
    "type": "shape",
    "name": "Закрытая_дверь",
    "shape": "custom",
    "color": "#d3d3d3",
    "x": 3181.27,
    "y": 1802.73,
    "width": 60,
    "height": 60,
    "curr_hp": 6,
    "endedTurn": false
  },
  {
    "id": 423,
    "type": "shape",
    "name": "Обзор",
    "shape": "custom",
    "color": "#930000",
    "x": 3960.78,
    "y": 1076.09,
    "width": 60,
    "height": 60,
    "curr_hp": 3,
    "endedTurn": false
  },
  {
    "id": 429,
    "type": "shape",
    "name": "_могила",
    "shape": "custom",
    "color": "#d3d3d3",
    "x": 4083.45,
    "y": 1901.9,
    "width": 60,
    "height": 60,
    "curr_hp": 1,
    "endedTurn": false
  },
  {
    "id": 430,
    "type": "shape",
    "name": "Закрытая_дверь",
    "shape": "custom",
    "color": "#d3d3d3",
    "x": 959.81,
    "y": 1694.92,
    "width": 60,
    "height": 60,
    "src": "",
    "curr_hp": 6,
    "endedTurn": false
  },
  {
    "id": 432,
    "type": "shape",
    "name": "Кровавый_змей",
    "shape": "custom",
    "color": "#d3d3d3",
    "x": 3583.73,
    "y": 2349.93,
    "width": 60,
    "height": 60,
    "curr_hp": 3,
    "endedTurn": false,
    "title": "Инж1",
    "src": ""
  },
  {
    "id": 434,
    "type": "shape",
    "name": "_обломки",
    "shape": "custom",
    "color": "#d3d3d3",
    "x": 3482.12,
    "y": 2166.88,
    "width": 60,
    "height": 60,
    "curr_hp": 0,
    "endedTurn": false
  },
  {
    "id": 435,
    "type": "shape",
    "name": "Кристалл_души",
    "shape": "custom",
    "color": "#930000",
    "x": 3480.45,
    "y": 1319.56,
    "width": 60,
    "height": 60,
    "src": "",
    "curr_hp": 0,
    "endedTurn": false
  },
  {
    "id": 442,
    "type": "shape",
    "name": "Кровь_колодца",
    "shape": "custom",
    "color": "#d3d3d3",
    "x": 3486.68,
    "y": 2100.66,
    "width": 60,
    "height": 60,
    "curr_hp": 1,
    "endedTurn": false
  },
  {
    "id": 443,
    "type": "shape",
    "name": "Кровь_колодца",
    "shape": "custom",
    "color": "#d3d3d3",
    "x": 3880.21,
    "y": 2214.62,
    "width": 60,
    "height": 60,
    "src": "",
    "curr_hp": 1,
    "endedTurn": false
  },
  {
    "id": 444,
    "type": "shape",
    "name": "Кровь_колодца",
    "shape": "custom",
    "color": "#d3d3d3",
    "x": 4095.39,
    "y": 2102.61,
    "width": 60,
    "height": 60,
    "curr_hp": 1,
    "endedTurn": false
  },
  {
    "id": 445,
    "type": "shape",
    "name": "_обломки",
    "shape": "custom",
    "color": "#d3d3d3",
    "x": 1939.15,
    "y": 1495.07,
    "width": 60,
    "height": 60,
    "curr_hp": 1,
    "endedTurn": false
  },
  {
    "id": 446,
    "type": "shape",
    "name": "_обломки",
    "shape": "custom",
    "color": "#d3d3d3",
    "x": 1960.23,
    "y": 892.17,
    "width": 60,
    "height": 60,
    "curr_hp": 1,
    "endedTurn": false
  },
  {
    "id": 447,
    "type": "shape",
    "name": "_обломки",
    "shape": "custom",
    "color": "#d3d3d3",
    "x": 1666.38,
    "y": 697.84,
    "width": 60,
    "height": 60,
    "curr_hp": 1,
    "endedTurn": false
  },
  {
    "id": 448,
    "type": "shape",
    "name": "_обломки",
    "shape": "custom",
    "color": "#d3d3d3",
    "x": 1680.43,
    "y": 1278.49,
    "width": 60,
    "height": 60,
    "curr_hp": 1,
    "endedTurn": false
  },
  {
    "id": 449,
    "type": "shape",
    "name": "_обломки",
    "shape": "custom",
    "color": "#d3d3d3",
    "x": 1677.54,
    "y": 1709.43,
    "width": 60,
    "height": 60,
    "curr_hp": 1,
    "endedTurn": false
  },
  {
    "id": 450,
    "type": "shape",
    "name": "_обломки",
    "shape": "custom",
    "color": "#d3d3d3",
    "x": 3269.33,
    "y": 1404.66,
    "width": 60,
    "height": 60,
    "curr_hp": 1,
    "endedTurn": false
  },
  {
    "id": 451,
    "type": "shape",
    "name": "_обломки",
    "shape": "custom",
    "color": "#d3d3d3",
    "x": 4502.5,
    "y": 979.2,
    "width": 60,
    "height": 60,
    "curr_hp": 1,
    "endedTurn": false
  },
  {
    "id": 452,
    "type": "shape",
    "name": "_info_",
    "shape": "custom",
    "color": "#d3d3d3",
    "x": 1295.37,
    "y": 1577.91,
    "width": 60,
    "height": 60,
    "curr_hp": 3,
    "endedTurn": false,
    "title": "Коридор обожжен лучистым ударом"
  },
  {
    "id": 453,
    "type": "shape",
    "name": "_могила",
    "shape": "custom",
    "color": "#930000",
    "x": 1255.8,
    "y": 1477.3,
    "width": 60,
    "height": 60,
    "curr_hp": 1,
    "endedTurn": false,
    "title": "Голем-паук"
  }
]