CURRENT_TURN=1;
OTHER_SAVE_DATA={
  "scale": 1.017886545917552,
  "canvasOffsetX": -4317.852200494332,
  "canvasOffsetY": -581.6882601360641,
  "shapeColor": "#0000ff"
};
USER_RESOURCES={
  "Нейтралы": {},
  "Враги": {},
  "Десант": {},
  "Эл-во": {}
};
OWNER_MAP={"122":[353],"491":[524,526,523,525],"519":[542,544,543],"520":[536,535,534,533,532],"521":[539,538,537,540],"541":[545,546,547,548]};
DEFAULT_DATA=[
  {
    "id": 5,
    "type": "shape",
    "name": "Движетель",
    "shape": "custom",
    "color": "#0000ff",
    "x": 4784.91,
    "y": 879.4,
    "width": 80,
    "height": 80,
    "curr_hp": 3,
    "endedTurn": false
  },
  {
    "id": 7,
    "type": "shape",
    "name": "Цепи_движетеля",
    "shape": "custom",
    "color": "#d3d3d3",
    "x": 4721.54,
    "y": 801.05,
    "width": 60,
    "height": 60,
    "curr_hp": 3,
    "endedTurn": false
  },
  {
    "id": 8,
    "type": "shape",
    "name": "Цепи_движетеля",
    "shape": "custom",
    "color": "#d3d3d3",
    "x": 4593.745457720724,
    "y": 683.3927495639743,
    "width": 60,
    "height": 60,
    "curr_hp": 3,
    "endedTurn": false
  },
  {
    "id": 9,
    "type": "shape",
    "name": "Цепи_движетеля",
    "shape": "custom",
    "color": "#d3d3d3",
    "x": 4794.38,
    "y": 984.62,
    "width": 60,
    "height": 60,
    "curr_hp": 3,
    "endedTurn": false
  },
  {
    "id": 10,
    "type": "shape",
    "name": "Цепи_движетеля",
    "shape": "custom",
    "color": "#d3d3d3",
    "x": 4794.24,
    "y": 1099.53,
    "width": 60,
    "height": 60,
    "curr_hp": 3,
    "endedTurn": false
  },
  {
    "id": 11,
    "type": "shape",
    "name": "Цепи_движетеля",
    "shape": "custom",
    "color": "#d3d3d3",
    "x": 4903.54,
    "y": 792.96,
    "width": 60,
    "height": 60,
    "curr_hp": 3,
    "endedTurn": false
  },
  {
    "id": 12,
    "type": "shape",
    "name": "Цепи_движетеля",
    "shape": "custom",
    "color": "#d3d3d3",
    "x": 5006.66,
    "y": 685.08,
    "width": 60,
    "height": 60,
    "curr_hp": 3,
    "endedTurn": false
  },
  {
    "id": 13,
    "type": "shape",
    "name": "Цепи_движетеля",
    "shape": "custom",
    "color": "#d3d3d3",
    "x": 4791.43,
    "y": 1991.75,
    "width": 60,
    "height": 60,
    "curr_hp": 3,
    "endedTurn": false
  },
  {
    "id": 14,
    "type": "shape",
    "name": "Цепи_движетеля",
    "shape": "custom",
    "color": "#d3d3d3",
    "x": 4795.79,
    "y": 1903.77,
    "width": 60,
    "height": 60,
    "curr_hp": 3,
    "endedTurn": false
  },
  {
    "id": 15,
    "type": "shape",
    "name": "Цепи_движетеля",
    "shape": "custom",
    "color": "#d3d3d3",
    "x": 4902.14,
    "y": 2196.88,
    "width": 60,
    "height": 60,
    "curr_hp": 3,
    "endedTurn": false
  },
  {
    "id": 16,
    "type": "shape",
    "name": "Цепи_движетеля",
    "shape": "custom",
    "color": "#d3d3d3",
    "x": 5000.63,
    "y": 2300.99,
    "width": 60,
    "height": 60,
    "curr_hp": 3,
    "endedTurn": false
  },
  {
    "id": 17,
    "type": "shape",
    "name": "Цепи_движетеля",
    "shape": "custom",
    "color": "#d3d3d3",
    "x": 4696.87,
    "y": 2194.92,
    "width": 60,
    "height": 60,
    "curr_hp": 3,
    "endedTurn": false
  },
  {
    "id": 18,
    "type": "shape",
    "name": "Цепи_движетеля",
    "shape": "custom",
    "color": "#d3d3d3",
    "x": 4604.4,
    "y": 2299.86,
    "width": 60,
    "height": 60,
    "curr_hp": 3,
    "endedTurn": false
  },
  {
    "id": 19,
    "type": "shape",
    "name": "Центр_управления",
    "shape": "custom",
    "color": "#d3d3d3",
    "x": 955.48,
    "y": 1488.01,
    "width": 80,
    "height": 80,
    "curr_hp": 3,
    "endedTurn": false,
    "disabled": true
  },
  {
    "id": 47,
    "type": "shape",
    "name": "Кровоточащий_Колодец",
    "shape": "custom",
    "color": "#d3d3d3",
    "x": 3780.64,
    "y": 2288.17,
    "width": 80,
    "height": 80,
    "curr_hp": 3,
    "endedTurn": false
  },
  {
    "id": 74,
    "type": "shape",
    "name": "Звёздная_Арка",
    "shape": "custom",
    "color": "#d3d3d3",
    "x": 2475.28,
    "y": 1295.34,
    "width": 60,
    "height": 60,
    "curr_hp": 3,
    "endedTurn": false,
    "src": ""
  },
  {
    "id": 75,
    "type": "shape",
    "name": "Звёздная_Арка",
    "shape": "custom",
    "color": "#d3d3d3",
    "x": 3170.74,
    "y": 683.36,
    "width": 60,
    "height": 60,
    "curr_hp": 3,
    "endedTurn": false
  },
  {
    "id": 77,
    "type": "shape",
    "name": "Звёздная_Арка",
    "shape": "custom",
    "color": "#d3d3d3",
    "x": 3589.69,
    "y": 2204.73,
    "width": 60,
    "height": 60,
    "curr_hp": 3,
    "endedTurn": false
  },
  {
    "id": 80,
    "type": "shape",
    "name": "Карта_корабля",
    "shape": "custom",
    "color": "#d3d3d3",
    "x": 1063.75,
    "y": 1498.07,
    "width": 60,
    "height": 60,
    "curr_hp": 3,
    "endedTurn": false
  },
  {
    "id": 88,
    "type": "shape",
    "name": "Звёздная_Арка",
    "shape": "custom",
    "color": "#d3d3d3",
    "x": 4597.23,
    "y": 787.73,
    "width": 60,
    "height": 60,
    "curr_hp": 3,
    "endedTurn": false
  },
  {
    "id": 101,
    "type": "shape",
    "name": "Кровать",
    "shape": "custom",
    "color": "#d3d3d3",
    "x": 2863.31,
    "y": 603.31,
    "width": 60,
    "height": 60,
    "curr_hp": 3,
    "endedTurn": false
  },
  {
    "id": 102,
    "type": "shape",
    "name": "Кровать",
    "shape": "custom",
    "color": "#d3d3d3",
    "x": 2964.16,
    "y": 606.25,
    "width": 60,
    "height": 60,
    "curr_hp": 3,
    "endedTurn": false
  },
  {
    "id": 103,
    "type": "shape",
    "name": "Скрижаль",
    "shape": "custom",
    "color": "#d3d3d3",
    "x": 870.71,
    "y": 1606.28,
    "width": 60,
    "height": 60,
    "curr_hp": 3,
    "endedTurn": false,
    "title": "Отвод глаз"
  },
  {
    "id": 104,
    "type": "shape",
    "name": "Кровать",
    "shape": "custom",
    "color": "#d3d3d3",
    "x": 2765.64,
    "y": 601.88,
    "width": 60,
    "height": 60,
    "curr_hp": 3,
    "endedTurn": false
  },
  {
    "id": 115,
    "type": "shape",
    "name": "Звёздная_Арка",
    "shape": "custom",
    "color": "#d3d3d3",
    "x": 4599.79,
    "y": 2199.31,
    "width": 60,
    "height": 60,
    "curr_hp": 3,
    "endedTurn": false
  },
  {
    "id": 116,
    "type": "shape",
    "name": "_могила",
    "shape": "custom",
    "color": "#d3d3d3",
    "x": 1309.56,
    "y": 1775.52,
    "width": 60,
    "height": 60,
    "curr_hp": 0,
    "endedTurn": false,
    "title": "Связь1",
    "src": ""
  },
  {
    "id": 117,
    "type": "shape",
    "name": "_могила",
    "shape": "custom",
    "color": "#d3d3d3",
    "x": 1519.79,
    "y": 1800.95,
    "width": 60,
    "height": 60,
    "curr_hp": 0,
    "endedTurn": false,
    "title": "Капитан",
    "src": ""
  },
  {
    "id": 119,
    "type": "shape",
    "name": "_могила",
    "shape": "custom",
    "color": "#930000",
    "x": 935.68,
    "y": 1575.82,
    "width": 60,
    "height": 60,
    "curr_hp": 0,
    "endedTurn": false,
    "title": "Навигатор",
    "src": ""
  },
  {
    "id": 120,
    "type": "shape",
    "name": "Звёздный_зомби",
    "shape": "custom",
    "color": "#930000",
    "x": 3175.29,
    "y": 841.41,
    "width": 60,
    "height": 60,
    "curr_hp": 3,
    "endedTurn": false,
    "title": "Врач",
    "src": ""
  },
  {
    "id": 121,
    "type": "shape",
    "name": "Кровавый_змей",
    "shape": "custom",
    "color": "#d3d3d3",
    "x": 3995.32,
    "y": 2327.61,
    "width": 60,
    "height": 60,
    "curr_hp": 3,
    "endedTurn": false,
    "title": "Двиг1",
    "lvl": 1,
    "src": ""
  },
  {
    "id": 122,
    "type": "shape",
    "name": "Хранитель",
    "shape": "custom",
    "color": "#930000",
    "x": 3670.96,
    "y": 802.15,
    "width": 60,
    "height": 60,
    "curr_hp": 1,
    "endedTurn": false,
    "title": "Наука"
  },
  {
    "id": 125,
    "type": "shape",
    "name": "_могила",
    "shape": "custom",
    "color": "#930000",
    "x": 3575.93,
    "y": 2095.86,
    "width": 60,
    "height": 60,
    "curr_hp": 0,
    "endedTurn": false,
    "title": "Свящ2",
    "src": ""
  },
  {
    "id": 126,
    "type": "shape",
    "name": "_могила",
    "shape": "custom",
    "color": "#930000",
    "x": 3854.56,
    "y": 1985.5,
    "width": 60,
    "height": 60,
    "curr_hp": 0,
    "endedTurn": false,
    "title": "Инж2",
    "src": ""
  },
  {
    "id": 127,
    "type": "shape",
    "name": "_могила",
    "shape": "custom",
    "color": "#d3d3d3",
    "x": 1537.08,
    "y": 1534.18,
    "width": 60,
    "height": 60,
    "curr_hp": 0,
    "endedTurn": false,
    "title": "Связь2"
  },
  {
    "id": 130,
    "type": "shape",
    "name": "Звёздный_зомби",
    "shape": "custom",
    "color": "#930000",
    "x": 1042.84,
    "y": 1465.39,
    "width": 60,
    "height": 60,
    "curr_hp": 3,
    "endedTurn": false,
    "title": "Старпом",
    "src": "",
    "lvl": 1
  },
  {
    "id": 131,
    "type": "shape",
    "name": "Кристалл_души",
    "shape": "custom",
    "color": "#d3d3d3",
    "x": 3611.93,
    "y": 1896.47,
    "width": 60,
    "height": 60,
    "curr_hp": 3,
    "endedTurn": false,
    "src": ""
  },
  {
    "id": 132,
    "type": "shape",
    "name": "Кристалл_души",
    "shape": "custom",
    "color": "#d3d3d3",
    "x": 4003.89,
    "y": 2092.09,
    "width": 60,
    "height": 60,
    "curr_hp": 3,
    "endedTurn": false,
    "src": ""
  },
  {
    "id": 133,
    "type": "shape",
    "name": "Кристалл_души",
    "shape": "custom",
    "color": "#d3d3d3",
    "x": 4104.7,
    "y": 1194.23,
    "width": 60,
    "height": 60,
    "curr_hp": 3,
    "endedTurn": false,
    "src": ""
  },
  {
    "id": 134,
    "type": "shape",
    "name": "Кристалл_души",
    "shape": "custom",
    "color": "#d3d3d3",
    "x": 3865.87,
    "y": 1100.09,
    "width": 60,
    "height": 60,
    "curr_hp": 3,
    "endedTurn": false,
    "src": ""
  },
  {
    "id": 136,
    "type": "shape",
    "name": "Кристалл_души",
    "shape": "custom",
    "color": "#d3d3d3",
    "x": 4474.76,
    "y": 1272.36,
    "width": 60,
    "height": 60,
    "curr_hp": 3,
    "endedTurn": false,
    "src": ""
  },
  {
    "id": 137,
    "type": "shape",
    "name": "Кристалл_души",
    "shape": "custom",
    "color": "#d3d3d3",
    "x": 4072.24,
    "y": 1684.49,
    "width": 60,
    "height": 60,
    "curr_hp": 3,
    "endedTurn": false,
    "src": ""
  },
  {
    "id": 138,
    "type": "shape",
    "name": "Кристалл_души",
    "shape": "custom",
    "color": "#d3d3d3",
    "x": 3716.97,
    "y": 1325.87,
    "width": 60,
    "height": 60,
    "curr_hp": 3,
    "endedTurn": false,
    "src": ""
  },
  {
    "id": 139,
    "type": "shape",
    "name": "Кристалл_души",
    "shape": "custom",
    "color": "#d3d3d3",
    "x": 3266.01,
    "y": 1276.16,
    "width": 60,
    "height": 60,
    "curr_hp": 3,
    "endedTurn": false,
    "src": ""
  },
  {
    "id": 140,
    "type": "shape",
    "name": "Кристалл_души",
    "shape": "custom",
    "color": "#d3d3d3",
    "x": 3261.18,
    "y": 1062.23,
    "width": 60,
    "height": 60,
    "curr_hp": 3,
    "endedTurn": false,
    "src": ""
  },
  {
    "id": 143,
    "type": "shape",
    "name": "Кристалл_души",
    "shape": "custom",
    "color": "#d3d3d3",
    "x": 4263.3,
    "y": 2081.94,
    "width": 60,
    "height": 60,
    "curr_hp": 3,
    "endedTurn": false,
    "src": ""
  },
  {
    "id": 148,
    "type": "shape",
    "name": "Кристалл_души",
    "shape": "custom",
    "color": "#d3d3d3",
    "x": 1552.85,
    "y": 1183,
    "width": 60,
    "height": 60,
    "curr_hp": 3,
    "endedTurn": false,
    "src": ""
  },
  {
    "id": 149,
    "type": "shape",
    "name": "Кристалл_души",
    "shape": "custom",
    "color": "#d3d3d3",
    "x": 1544.12,
    "y": 1634.15,
    "width": 60,
    "height": 60,
    "curr_hp": 3,
    "endedTurn": false,
    "src": ""
  },
  {
    "id": 150,
    "type": "shape",
    "name": "Кристалл_души",
    "shape": "custom",
    "color": "#d3d3d3",
    "x": 1336.84,
    "y": 1476.43,
    "width": 60,
    "height": 60,
    "curr_hp": 3,
    "endedTurn": false,
    "src": ""
  },
  {
    "id": 151,
    "type": "shape",
    "name": "Кристалл_души",
    "shape": "custom",
    "color": "#d3d3d3",
    "x": 1541.59,
    "y": 1751.07,
    "width": 60,
    "height": 60,
    "curr_hp": 3,
    "endedTurn": false,
    "src": ""
  },
  {
    "id": 152,
    "type": "shape",
    "name": "Кристалл_души",
    "shape": "custom",
    "color": "#d3d3d3",
    "x": 1039.58,
    "y": 1777.89,
    "width": 60,
    "height": 60,
    "curr_hp": 3,
    "endedTurn": false,
    "src": ""
  },
  {
    "id": 154,
    "type": "shape",
    "name": "Кровать",
    "shape": "custom",
    "color": "#d3d3d3",
    "x": 3364.51,
    "y": 1914.56,
    "width": 60,
    "height": 60,
    "curr_hp": 3,
    "endedTurn": false
  },
  {
    "id": 155,
    "type": "shape",
    "name": "Кровать",
    "shape": "custom",
    "color": "#d3d3d3",
    "x": 3266.95,
    "y": 1916.6,
    "width": 60,
    "height": 60,
    "curr_hp": 3,
    "endedTurn": false
  },
  {
    "id": 156,
    "type": "shape",
    "name": "Кровать",
    "shape": "custom",
    "color": "#d3d3d3",
    "x": 3359.47,
    "y": 1114.07,
    "width": 60,
    "height": 60,
    "curr_hp": 3,
    "endedTurn": false
  },
  {
    "id": 157,
    "type": "shape",
    "name": "Кровать",
    "shape": "custom",
    "color": "#d3d3d3",
    "x": 3461.27,
    "y": 1117.66,
    "width": 60,
    "height": 60,
    "curr_hp": 3,
    "endedTurn": false
  },
  {
    "id": 159,
    "type": "shape",
    "name": "Хранитель",
    "shape": "custom",
    "color": "#d3d3d3",
    "x": 3763.96,
    "y": 2165.7,
    "width": 60,
    "height": 60,
    "curr_hp": 4,
    "endedTurn": false,
    "title": "Двиг2"
  },
  {
    "id": 161,
    "type": "shape",
    "name": "_могила",
    "shape": "custom",
    "color": "#930000",
    "x": 3650.35,
    "y": 1271.41,
    "width": 60,
    "height": 60,
    "curr_hp": 0,
    "endedTurn": false,
    "title": "Кровь"
  },
  {
    "id": 162,
    "type": "shape",
    "name": "Кровать",
    "shape": "custom",
    "color": "#d3d3d3",
    "x": 3560.47,
    "y": 1114.89,
    "width": 60,
    "height": 60,
    "curr_hp": 3,
    "endedTurn": false
  },
  {
    "id": 163,
    "type": "shape",
    "name": "Кровать",
    "shape": "custom",
    "color": "#d3d3d3",
    "x": 3466.95,
    "y": 1917.25,
    "width": 60,
    "height": 60,
    "curr_hp": 3,
    "endedTurn": false
  },
  {
    "id": 164,
    "type": "shape",
    "name": "Контрольное_кресло",
    "shape": "custom",
    "color": "#d3d3d3",
    "x": 888.33,
    "y": 1509.94,
    "width": 60,
    "height": 60,
    "curr_hp": 3,
    "endedTurn": false,
    "title": "Капитан"
  },
  {
    "id": 165,
    "type": "shape",
    "name": "Контрольное_кресло",
    "shape": "custom",
    "color": "#d3d3d3",
    "x": 983.58,
    "y": 1409.76,
    "width": 60,
    "height": 60,
    "curr_hp": 3,
    "endedTurn": false,
    "title": "Старпом"
  },
  {
    "id": 166,
    "type": "shape",
    "name": "Контрольное_кресло",
    "shape": "custom",
    "color": "#d3d3d3",
    "x": 1080.65,
    "y": 1407.86,
    "width": 60,
    "height": 60,
    "curr_hp": 3,
    "endedTurn": false,
    "title": "Начтех"
  },
  {
    "id": 167,
    "type": "shape",
    "name": "Контрольное_кресло",
    "shape": "custom",
    "color": "#d3d3d3",
    "x": 979.46,
    "y": 1606.97,
    "width": 60,
    "height": 60,
    "curr_hp": 3,
    "endedTurn": false,
    "title": "Навигатор"
  },
  {
    "id": 168,
    "type": "shape",
    "name": "Контрольное_кресло",
    "shape": "custom",
    "color": "#d3d3d3",
    "x": 2394.07,
    "y": 1411.18,
    "width": 60,
    "height": 60,
    "curr_hp": 3,
    "endedTurn": false,
    "title": "Контроль",
    "src": ""
  },
  {
    "id": 169,
    "type": "shape",
    "name": "Контрольное_кресло",
    "shape": "custom",
    "color": "#d3d3d3",
    "x": 1987.15,
    "y": 698.37,
    "width": 60,
    "height": 60,
    "curr_hp": 3,
    "endedTurn": false,
    "title": "Контроль"
  },
  {
    "id": 170,
    "type": "shape",
    "name": "Контрольное_кресло",
    "shape": "custom",
    "color": "#d3d3d3",
    "x": 1487.51,
    "y": 697.25,
    "width": 60,
    "height": 60,
    "curr_hp": 3,
    "endedTurn": false
  },
  {
    "id": 171,
    "type": "shape",
    "name": "Контрольное_кресло",
    "shape": "custom",
    "color": "#d3d3d3",
    "x": 1484.99,
    "y": 902.82,
    "width": 60,
    "height": 60,
    "curr_hp": 3,
    "endedTurn": false
  },
  {
    "id": 172,
    "type": "shape",
    "name": "Контрольное_кресло",
    "shape": "custom",
    "color": "#d3d3d3",
    "x": 1995.03,
    "y": 608.6,
    "width": 60,
    "height": 60,
    "curr_hp": 3,
    "endedTurn": false
  },
  {
    "id": 173,
    "type": "shape",
    "name": "Контрольное_кресло",
    "shape": "custom",
    "color": "#d3d3d3",
    "x": 3402.14,
    "y": 1605.83,
    "width": 60,
    "height": 60,
    "curr_hp": 3,
    "endedTurn": false,
    "title": "Контроль"
  },
  {
    "id": 174,
    "type": "shape",
    "name": "Контрольное_кресло",
    "shape": "custom",
    "color": "#d3d3d3",
    "x": 3398.73,
    "y": 1712.41,
    "width": 60,
    "height": 60,
    "curr_hp": 3,
    "endedTurn": false
  },
  {
    "id": 175,
    "type": "shape",
    "name": "Контрольное_кресло",
    "shape": "custom",
    "color": "#d3d3d3",
    "x": 3182.74,
    "y": 1275.28,
    "width": 60,
    "height": 60,
    "curr_hp": 3,
    "endedTurn": false,
    "title": "Контроль"
  },
  {
    "id": 179,
    "type": "shape",
    "name": "Контрольное_кресло",
    "shape": "custom",
    "color": "#d3d3d3",
    "x": 2991.46,
    "y": 700.38,
    "width": 60,
    "height": 60,
    "curr_hp": 3,
    "endedTurn": false,
    "title": "Контроль"
  },
  {
    "id": 180,
    "type": "shape",
    "name": "Контрольное_кресло",
    "shape": "custom",
    "color": "#d3d3d3",
    "x": 3398.38,
    "y": 802.11,
    "width": 60,
    "height": 60,
    "curr_hp": 3,
    "endedTurn": false,
    "title": "Контроль"
  },
  {
    "id": 181,
    "type": "shape",
    "name": "Контрольное_кресло",
    "shape": "custom",
    "color": "#d3d3d3",
    "x": 4816.01,
    "y": 805.35,
    "width": 60,
    "height": 60,
    "curr_hp": 3,
    "endedTurn": false,
    "title": "Главный"
  },
  {
    "id": 182,
    "type": "shape",
    "name": "Контрольное_кресло",
    "shape": "custom",
    "color": "#d3d3d3",
    "x": 4711.85,
    "y": 1102.04,
    "width": 60,
    "height": 60,
    "curr_hp": 3,
    "endedTurn": false,
    "title": "Резервный"
  },
  {
    "id": 183,
    "type": "shape",
    "name": "Контрольное_кресло",
    "shape": "custom",
    "color": "#d3d3d3",
    "x": 4815.96,
    "y": 2202.55,
    "width": 60,
    "height": 60,
    "curr_hp": 3,
    "endedTurn": false,
    "title": "Главный"
  },
  {
    "id": 184,
    "type": "shape",
    "name": "Контрольное_кресло",
    "shape": "custom",
    "color": "#d3d3d3",
    "x": 4715.38,
    "y": 1915.35,
    "width": 60,
    "height": 60,
    "curr_hp": 3,
    "endedTurn": false,
    "title": "Резервный"
  },
  {
    "id": 186,
    "type": "shape",
    "name": "Контрольное_кресло",
    "shape": "custom",
    "color": "#d3d3d3",
    "x": 3796.84,
    "y": 2218.19,
    "width": 60,
    "height": 60,
    "curr_hp": 3,
    "endedTurn": false,
    "title": "Контроль"
  },
  {
    "id": 187,
    "type": "shape",
    "name": "Контрольное_кресло",
    "shape": "custom",
    "color": "#d3d3d3",
    "x": 3803.22,
    "y": 803.18,
    "width": 60,
    "height": 60,
    "curr_hp": 3,
    "endedTurn": false,
    "title": "Контроль"
  },
  {
    "id": 188,
    "type": "shape",
    "name": "Контур_ответчик",
    "shape": "custom",
    "color": "#d3d3d3",
    "x": 1361.45,
    "y": 788.87,
    "width": 60,
    "height": 60,
    "curr_hp": 3,
    "endedTurn": false
  },
  {
    "id": 189,
    "type": "shape",
    "name": "Кровь_колодца",
    "shape": "custom",
    "color": "#d3d3d3",
    "x": 3788.15,
    "y": 2006.2,
    "width": 60,
    "height": 60,
    "curr_hp": 3,
    "endedTurn": false,
    "src": ""
  },
  {
    "id": 190,
    "type": "shape",
    "name": "Кровь_колодца",
    "shape": "custom",
    "color": "#d3d3d3",
    "x": 3685.49,
    "y": 2202.6,
    "width": 60,
    "height": 60,
    "curr_hp": 3,
    "endedTurn": false
  },
  {
    "id": 191,
    "type": "shape",
    "name": "Кровь_колодца",
    "shape": "custom",
    "color": "#d3d3d3",
    "x": 3884.71,
    "y": 2298.84,
    "width": 60,
    "height": 60,
    "curr_hp": 3,
    "endedTurn": false,
    "src": ""
  },
  {
    "id": 192,
    "type": "shape",
    "name": "Кровь_колодца",
    "shape": "custom",
    "color": "#d3d3d3",
    "x": 3684.53,
    "y": 2300.77,
    "width": 60,
    "height": 60,
    "curr_hp": 3,
    "endedTurn": false
  },
  {
    "id": 193,
    "type": "shape",
    "name": "Кровь_колодца",
    "shape": "custom",
    "color": "#d3d3d3",
    "x": 3688.38,
    "y": 2402.78,
    "width": 60,
    "height": 60,
    "curr_hp": 3,
    "endedTurn": false
  },
  {
    "id": 194,
    "type": "shape",
    "name": "Кровь_колодца",
    "shape": "custom",
    "color": "#d3d3d3",
    "x": 3787.5085798984846,
    "y": 2399.8957015353426,
    "width": 60,
    "height": 60,
    "curr_hp": 3,
    "endedTurn": false
  },
  {
    "id": 195,
    "type": "shape",
    "name": "Кровь_колодца",
    "shape": "custom",
    "color": "#d3d3d3",
    "x": 3887.6,
    "y": 2398.93,
    "width": 60,
    "height": 60,
    "curr_hp": 3,
    "endedTurn": false
  },
  {
    "id": 197,
    "type": "shape",
    "name": "Душевидец",
    "shape": "custom",
    "color": "#d3d3d3",
    "x": 3991.98,
    "y": 685.63,
    "width": 60,
    "height": 60,
    "curr_hp": 3,
    "endedTurn": false
  },
  {
    "id": 198,
    "type": "shape",
    "name": "Контрольное_кресло",
    "shape": "custom",
    "color": "#d3d3d3",
    "x": 4005.12,
    "y": 800.08,
    "width": 60,
    "height": 60,
    "curr_hp": 3,
    "endedTurn": false,
    "title": "Душевидец"
  },
  {
    "id": 200,
    "type": "shape",
    "name": "Кристалл_души",
    "shape": "custom",
    "color": "#d3d3d3",
    "x": 3563.57,
    "y": 868.03,
    "width": 60,
    "height": 60,
    "curr_hp": 3,
    "endedTurn": false,
    "src": ""
  },
  {
    "id": 202,
    "type": "shape",
    "name": "Кристалл_души",
    "shape": "custom",
    "color": "#d3d3d3",
    "x": 3159.78,
    "y": 761.25,
    "width": 60,
    "height": 60,
    "curr_hp": 3,
    "endedTurn": false,
    "src": ""
  },
  {
    "id": 204,
    "type": "shape",
    "name": "Кровать",
    "shape": "custom",
    "color": "#d3d3d3",
    "x": 1256.65,
    "y": 1816.11,
    "width": 60,
    "height": 60,
    "curr_hp": 3,
    "endedTurn": false
  },
  {
    "id": 205,
    "type": "shape",
    "name": "Кровать",
    "shape": "custom",
    "color": "#d3d3d3",
    "x": 1354.83,
    "y": 1812.18,
    "width": 60,
    "height": 60,
    "curr_hp": 3,
    "endedTurn": false
  },
  {
    "id": 206,
    "type": "shape",
    "name": "Кровать",
    "shape": "custom",
    "color": "#d3d3d3",
    "x": 1445.55,
    "y": 1816.18,
    "width": 60,
    "height": 60,
    "curr_hp": 3,
    "endedTurn": false
  },
  {
    "id": 207,
    "type": "shape",
    "name": "Контрольное_кресло",
    "shape": "custom",
    "color": "#d3d3d3",
    "x": 3271.52,
    "y": 1496.07,
    "width": 60,
    "height": 60,
    "curr_hp": 3,
    "endedTurn": false
  },
  {
    "id": 213,
    "type": "shape",
    "name": "Кровать",
    "shape": "custom",
    "color": "#d3d3d3",
    "x": 3669.91,
    "y": 1112.37,
    "width": 60,
    "height": 60,
    "curr_hp": 3,
    "endedTurn": false
  },
  {
    "id": 214,
    "type": "shape",
    "name": "Контрольное_кресло",
    "shape": "custom",
    "color": "#d3d3d3",
    "x": 1093.86,
    "y": 1610.47,
    "width": 60,
    "height": 60,
    "curr_hp": 3,
    "endedTurn": false,
    "title": "НачБез"
  },
  {
    "id": 216,
    "type": "shape",
    "name": "Звёздный_зомби",
    "shape": "custom",
    "color": "#930000",
    "x": 3313.43,
    "y": 1412.63,
    "width": 60,
    "height": 60,
    "curr_hp": 3,
    "endedTurn": false,
    "title": "Штурм4",
    "src": ""
  },
  {
    "id": 235,
    "type": "shape",
    "name": "Инъектор_подавления",
    "shape": "custom",
    "color": "#d3d3d3",
    "x": 3822.74,
    "y": 2078.57,
    "width": 40,
    "height": 40,
    "curr_hp": 1,
    "endedTurn": false
  },
  {
    "id": 238,
    "type": "shape",
    "name": "Инъектор_подавления",
    "shape": "custom",
    "color": "#d3d3d3",
    "x": 2767.25,
    "y": 822.18,
    "width": 40,
    "height": 40,
    "curr_hp": 1,
    "endedTurn": false
  },
  {
    "id": 240,
    "type": "shape",
    "name": "Аварийный_накопитель",
    "shape": "custom",
    "color": "#d3d3d3",
    "x": 3418.22,
    "y": 880.94,
    "width": 40,
    "height": 40,
    "curr_hp": 1,
    "endedTurn": false
  },
  {
    "id": 241,
    "type": "shape",
    "name": "Ремонтный_набор",
    "shape": "custom",
    "color": "#d3d3d3",
    "x": 3414.96,
    "y": 926.04,
    "width": 40,
    "height": 40,
    "curr_hp": 1,
    "endedTurn": false
  },
  {
    "id": 242,
    "type": "shape",
    "name": "Кровемёт",
    "shape": "custom",
    "color": "#d3d3d3",
    "x": 4005.52,
    "y": 2197.41,
    "width": 40,
    "height": 40,
    "curr_hp": 1,
    "endedTurn": false,
    "lvl": 5
  },
  {
    "id": 247,
    "type": "shape",
    "name": "Кровемёт",
    "shape": "custom",
    "color": "#d3d3d3",
    "x": 4006.23,
    "y": 2280.15,
    "width": 40,
    "height": 40,
    "curr_hp": 1,
    "endedTurn": false,
    "lvl": 5
  },
  {
    "id": 248,
    "type": "shape",
    "name": "Кровемёт",
    "shape": "custom",
    "color": "#d3d3d3",
    "x": 3821.19,
    "y": 2119.21,
    "width": 40,
    "height": 40,
    "curr_hp": 1,
    "endedTurn": false,
    "lvl": 3
  },
  {
    "id": 250,
    "type": "shape",
    "name": "Спиритический_микрофон",
    "shape": "custom",
    "color": "#d3d3d3",
    "x": 3070.5,
    "y": 792.89,
    "width": 40,
    "height": 40,
    "curr_hp": 1,
    "endedTurn": false
  },
  {
    "id": 251,
    "type": "shape",
    "name": "Кристалл_души",
    "shape": "custom",
    "color": "#d3d3d3",
    "x": 3216.35,
    "y": 785.34,
    "width": 40,
    "height": 40,
    "curr_hp": 1,
    "endedTurn": false
  },
  {
    "id": 257,
    "type": "shape",
    "name": "Коагулянт-гель",
    "shape": "custom",
    "color": "#d3d3d3",
    "x": 3778.2,
    "y": 2057.98,
    "width": 40,
    "height": 40,
    "curr_hp": 1,
    "endedTurn": false
  },
  {
    "id": 258,
    "type": "shape",
    "name": "Коагулянт-гель",
    "shape": "custom",
    "color": "#d3d3d3",
    "x": 3970.98,
    "y": 1078.45,
    "width": 40,
    "height": 40,
    "curr_hp": 1,
    "endedTurn": false
  },
  {
    "id": 263,
    "type": "shape",
    "name": "Скрижаль",
    "shape": "custom",
    "color": "#d3d3d3",
    "x": 3888.33,
    "y": 580.3,
    "width": 60,
    "height": 60,
    "curr_hp": 1,
    "endedTurn": false,
    "title": "Имя"
  },
  {
    "id": 264,
    "type": "shape",
    "name": "Скрижаль",
    "shape": "custom",
    "color": "#d3d3d3",
    "x": 3684,
    "y": 581.45,
    "width": 60,
    "height": 60,
    "curr_hp": 1,
    "endedTurn": false,
    "title": "Стасис"
  },
  {
    "id": 265,
    "type": "shape",
    "name": "Скрижаль",
    "shape": "custom",
    "color": "#d3d3d3",
    "x": 3612.92,
    "y": 595.28,
    "width": 60,
    "height": 60,
    "curr_hp": 1,
    "endedTurn": false,
    "title": "Увядание"
  },
  {
    "id": 266,
    "type": "shape",
    "name": "Скрижаль",
    "shape": "custom",
    "color": "#d3d3d3",
    "x": 3565.53,
    "y": 559.84,
    "width": 60,
    "height": 60,
    "curr_hp": 1,
    "endedTurn": false,
    "title": "Разряд"
  },
  {
    "id": 273,
    "type": "shape",
    "name": "Ремонтный_набор",
    "shape": "custom",
    "color": "#d3d3d3",
    "x": 3257.6,
    "y": 1680.82,
    "width": 40,
    "height": 40,
    "curr_hp": 1,
    "endedTurn": false
  },
  {
    "id": 274,
    "type": "shape",
    "name": "Аварийный_накопитель",
    "shape": "custom",
    "color": "#d3d3d3",
    "x": 3690.63,
    "y": 2119.62,
    "width": 40,
    "height": 40,
    "curr_hp": 1,
    "endedTurn": false
  },
  {
    "id": 277,
    "type": "shape",
    "name": "Инъектор_подавления",
    "shape": "custom",
    "color": "#d3d3d3",
    "x": 2005.79,
    "y": 777.76,
    "width": 40,
    "height": 40,
    "curr_hp": 1,
    "endedTurn": false
  },
  {
    "id": 280,
    "type": "shape",
    "name": "Инъектор_подавления",
    "shape": "custom",
    "color": "#d3d3d3",
    "x": 1603.73,
    "y": 726.03,
    "width": 40,
    "height": 40,
    "curr_hp": 1,
    "endedTurn": false
  },
  {
    "id": 289,
    "type": "shape",
    "name": "Переносной_Алтарь",
    "shape": "custom",
    "color": "#d3d3d3",
    "x": 3372.256840434497,
    "y": 922.7169762486143,
    "width": 40,
    "height": 40,
    "curr_hp": 1,
    "endedTurn": false
  },
  {
    "id": 290,
    "type": "shape",
    "name": "Аварийный_накопитель",
    "shape": "custom",
    "color": "#d3d3d3",
    "x": 3739.59,
    "y": 2125.2,
    "width": 40,
    "height": 40,
    "curr_hp": 1,
    "endedTurn": false
  },
  {
    "id": 291,
    "type": "shape",
    "name": "Аварийный_накопитель",
    "shape": "custom",
    "color": "#d3d3d3",
    "x": 1604.31,
    "y": 1541.64,
    "width": 40,
    "height": 40,
    "curr_hp": 1,
    "endedTurn": false,
    "src": ""
  },
  {
    "id": 300,
    "type": "shape",
    "name": "Спиритический_микрофон",
    "shape": "custom",
    "color": "#d3d3d3",
    "x": 1591.2,
    "y": 1829.64,
    "width": 40,
    "height": 40,
    "curr_hp": 1,
    "endedTurn": false
  },
  {
    "id": 303,
    "type": "shape",
    "name": "Кровемёт",
    "shape": "custom",
    "color": "#d3d3d3",
    "x": 3727.57,
    "y": 2077.04,
    "width": 40,
    "height": 40,
    "curr_hp": 1,
    "endedTurn": false,
    "lvl": 3
  },
  {
    "id": 304,
    "type": "shape",
    "name": "Кровемёт",
    "shape": "custom",
    "color": "#d3d3d3",
    "x": 3959.37,
    "y": 2131.24,
    "width": 40,
    "height": 40,
    "curr_hp": 1,
    "endedTurn": false,
    "lvl": 2
  },
  {
    "id": 309,
    "type": "shape",
    "name": "Копир-скрижаль",
    "shape": "custom",
    "color": "#d3d3d3",
    "x": 3561.55,
    "y": 809.14,
    "width": 60,
    "height": 60,
    "curr_hp": 1,
    "endedTurn": false
  },
  {
    "id": 310,
    "type": "shape",
    "name": "Копир-скрижаль",
    "shape": "custom",
    "color": "#d3d3d3",
    "x": 3910.16,
    "y": 872.34,
    "width": 60,
    "height": 60,
    "curr_hp": 1,
    "endedTurn": false
  },
  {
    "id": 312,
    "type": "shape",
    "name": "Копир-скрижаль",
    "shape": "custom",
    "color": "#d3d3d3",
    "x": 3666.28,
    "y": 910.91,
    "width": 60,
    "height": 60,
    "curr_hp": 1,
    "endedTurn": false
  },
  {
    "id": 313,
    "type": "shape",
    "name": "Копир-скрижаль",
    "shape": "custom",
    "color": "#d3d3d3",
    "x": 3708.56,
    "y": 870.06,
    "width": 60,
    "height": 60,
    "curr_hp": 1,
    "endedTurn": false
  },
  {
    "id": 314,
    "type": "shape",
    "name": "Копир-скрижаль",
    "shape": "custom",
    "color": "#d3d3d3",
    "x": 3863.62,
    "y": 912.86,
    "width": 60,
    "height": 60,
    "curr_hp": 1,
    "endedTurn": false
  },
  {
    "id": 315,
    "type": "shape",
    "name": "Скрижаль",
    "shape": "custom",
    "color": "#d3d3d3",
    "x": 3794.23,
    "y": 579.18,
    "width": 60,
    "height": 60,
    "curr_hp": 1,
    "endedTurn": false,
    "title": "Отвод глаз"
  },
  {
    "id": 316,
    "type": "shape",
    "name": "Копир-скрижаль",
    "shape": "custom",
    "color": "#d3d3d3",
    "x": 3609.03,
    "y": 768.37,
    "width": 60,
    "height": 60,
    "curr_hp": 1,
    "endedTurn": false
  },
  {
    "id": 322,
    "type": "shape",
    "name": "Тень_Усопшего",
    "shape": "custom",
    "color": "#930000",
    "x": 1764.06,
    "y": 585.48,
    "width": 60,
    "height": 60,
    "src": "",
    "curr_hp": 2,
    "endedTurn": false
  },
  {
    "id": 325,
    "type": "shape",
    "name": "Тень_Усопшего",
    "shape": "custom",
    "color": "#930000",
    "x": 1585.26,
    "y": 1119.21,
    "width": 60,
    "height": 60,
    "src": "",
    "curr_hp": 3,
    "endedTurn": false
  },
  {
    "id": 326,
    "type": "shape",
    "name": "Тень_Усопшего",
    "shape": "custom",
    "color": "#930000",
    "x": 3806.94,
    "y": 1306.63,
    "width": 60,
    "height": 60,
    "src": "",
    "curr_hp": 3,
    "endedTurn": false
  },
  {
    "id": 332,
    "type": "shape",
    "name": "Тень_Усопшего",
    "shape": "custom",
    "color": "#930000",
    "x": 3545.34,
    "y": 1305.26,
    "width": 60,
    "height": 60,
    "src": "",
    "curr_hp": 3,
    "endedTurn": false
  },
  {
    "id": 335,
    "type": "shape",
    "name": "Тень_Усопшего",
    "shape": "custom",
    "color": "#930000",
    "x": 1103.36,
    "y": 1507.3,
    "width": 60,
    "height": 60,
    "src": "",
    "curr_hp": 3,
    "endedTurn": false
  },
  {
    "id": 336,
    "type": "shape",
    "name": "Тень_Усопшего",
    "shape": "custom",
    "color": "#930000",
    "x": 1393.34,
    "y": 866.21,
    "width": 60,
    "height": 60,
    "curr_hp": 3,
    "endedTurn": false
  },
  {
    "id": 340,
    "type": "shape",
    "name": "Тень_Усопшего",
    "shape": "custom",
    "color": "#930000",
    "x": 4212.06,
    "y": 1303.1,
    "width": 60,
    "height": 60,
    "curr_hp": 3,
    "endedTurn": false,
    "src": ""
  },
  {
    "id": 343,
    "type": "shape",
    "name": "Тень_Усопшего",
    "shape": "custom",
    "color": "#930000",
    "x": 1597.96,
    "y": 1466.27,
    "width": 60,
    "height": 60,
    "curr_hp": 3,
    "endedTurn": false
  },
  {
    "id": 344,
    "type": "shape",
    "name": "Тень_Усопшего",
    "shape": "custom",
    "color": "#930000",
    "x": 1418.21,
    "y": 1535.79,
    "width": 60,
    "height": 60,
    "curr_hp": 3,
    "endedTurn": false
  },
  {
    "id": 345,
    "type": "shape",
    "name": "Кристалл_души",
    "shape": "custom",
    "color": "#930000",
    "x": 1604.54,
    "y": 1166.87,
    "width": 60,
    "height": 60,
    "src": "",
    "curr_hp": 0,
    "endedTurn": false
  },
  {
    "id": 347,
    "type": "shape",
    "name": "Тень_Усопшего",
    "shape": "custom",
    "color": "#930000",
    "x": 3560,
    "y": 1888.48,
    "width": 60,
    "height": 60,
    "curr_hp": 3,
    "endedTurn": false,
    "src": ""
  },
  {
    "id": 349,
    "type": "shape",
    "name": "Тень_Усопшего",
    "shape": "custom",
    "color": "#930000",
    "x": 1574.48,
    "y": 1592.1,
    "width": 60,
    "height": 60,
    "curr_hp": 3,
    "endedTurn": false,
    "src": ""
  },
  {
    "id": 350,
    "type": "shape",
    "name": "Закрытая_дверь",
    "shape": "custom",
    "color": "#d3d3d3",
    "x": 2076.63,
    "y": 1191.76,
    "width": 60,
    "height": 60,
    "curr_hp": 6,
    "endedTurn": false,
    "src": ""
  },
  {
    "id": 351,
    "type": "shape",
    "name": "Тень_Усопшего",
    "shape": "custom",
    "color": "#930000",
    "x": 3300.85,
    "y": 857.6,
    "width": 60,
    "height": 60,
    "src": "",
    "curr_hp": 3,
    "endedTurn": false
  },
  {
    "id": 352,
    "type": "shape",
    "name": "Тень_Усопшего",
    "shape": "custom",
    "color": "#930000",
    "x": 3420.01,
    "y": 1051,
    "width": 60,
    "height": 60,
    "curr_hp": 3,
    "endedTurn": false
  },
  {
    "id": 353,
    "type": "shape",
    "name": "Холодный_свет",
    "shape": "custom",
    "color": "#930000",
    "x": 3705.29,
    "y": 744.18,
    "width": 60,
    "height": 60,
    "curr_hp": 3,
    "endedTurn": false,
    "src": ""
  },
  {
    "id": 356,
    "type": "shape",
    "name": "Тень_Усопшего",
    "shape": "custom",
    "color": "#930000",
    "x": 3578.25,
    "y": 2280.29,
    "width": 60,
    "height": 60,
    "curr_hp": 3,
    "endedTurn": false
  },
  {
    "id": 358,
    "type": "shape",
    "name": "Тень_Усопшего",
    "shape": "custom",
    "color": "#930000",
    "x": 3582.49,
    "y": 640.5,
    "width": 60,
    "height": 60,
    "curr_hp": 3,
    "endedTurn": false
  },
  {
    "id": 359,
    "type": "shape",
    "name": "Тень_Усопшего",
    "shape": "custom",
    "color": "#930000",
    "x": 2793.48,
    "y": 680.6,
    "width": 60,
    "height": 60,
    "curr_hp": 3,
    "endedTurn": false
  },
  {
    "id": 366,
    "type": "shape",
    "name": "Тень_Усопшего",
    "shape": "custom",
    "color": "#930000",
    "x": 4306.96,
    "y": 2109.78,
    "width": 60,
    "height": 60,
    "curr_hp": 3,
    "endedTurn": false,
    "src": ""
  },
  {
    "id": 369,
    "type": "shape",
    "name": "Тень_Усопшего",
    "shape": "custom",
    "color": "#930000",
    "x": 1039.65,
    "y": 1829.82,
    "width": 60,
    "height": 60,
    "curr_hp": 3,
    "endedTurn": false
  },
  {
    "id": 372,
    "type": "shape",
    "name": "Коагулянт-гель",
    "shape": "custom",
    "color": "#d3d3d3",
    "x": 3116.8,
    "y": 799.21,
    "width": 40,
    "height": 40,
    "curr_hp": 1,
    "endedTurn": false
  },
  {
    "id": 385,
    "type": "shape",
    "name": "Закрытая_дверь",
    "shape": "custom",
    "color": "#d3d3d3",
    "x": 4493.47,
    "y": 2098.07,
    "width": 60,
    "height": 60,
    "curr_hp": 6,
    "endedTurn": false
  },
  {
    "id": 388,
    "type": "shape",
    "name": "Тень_Усопшего",
    "shape": "custom",
    "color": "#930000",
    "x": 1641.26,
    "y": 1869.87,
    "width": 60,
    "height": 60,
    "curr_hp": 3,
    "endedTurn": false
  },
  {
    "id": 389,
    "type": "shape",
    "name": "Тень_Усопшего",
    "shape": "custom",
    "color": "#930000",
    "x": 1630.71,
    "y": 1600.59,
    "width": 60,
    "height": 60,
    "curr_hp": 3,
    "endedTurn": false
  },
  {
    "id": 390,
    "type": "shape",
    "name": "Тень_Усопшего",
    "shape": "custom",
    "color": "#930000",
    "x": 1483.21,
    "y": 1558.81,
    "width": 60,
    "height": 60,
    "curr_hp": 3,
    "endedTurn": false
  },
  {
    "id": 391,
    "type": "shape",
    "name": "Тень_Усопшего",
    "shape": "custom",
    "color": "#930000",
    "x": 3602.4,
    "y": 912.5,
    "width": 60,
    "height": 60,
    "curr_hp": 3,
    "endedTurn": false
  },
  {
    "id": 398,
    "type": "shape",
    "name": "Закрытая_дверь",
    "shape": "custom",
    "color": "#d3d3d3",
    "x": 4593.21,
    "y": 1197.56,
    "width": 60,
    "height": 60,
    "curr_hp": 6,
    "endedTurn": false
  },
  {
    "id": 399,
    "type": "shape",
    "name": "Закрытая_дверь",
    "shape": "custom",
    "color": "#d3d3d3",
    "x": 2684.98,
    "y": 1123.97,
    "width": 60,
    "height": 60,
    "curr_hp": 6,
    "endedTurn": false,
    "src": ""
  },
  {
    "id": 410,
    "type": "shape",
    "name": "Тень_Усопшего",
    "shape": "custom",
    "color": "#930000",
    "x": 3878.7,
    "y": 1904.01,
    "width": 60,
    "height": 60,
    "curr_hp": 3,
    "endedTurn": false
  },
  {
    "id": 411,
    "type": "shape",
    "name": "Тень_Усопшего",
    "shape": "custom",
    "color": "#930000",
    "x": 3906.67,
    "y": 2139.91,
    "width": 60,
    "height": 60,
    "curr_hp": 3,
    "endedTurn": false
  },
  {
    "id": 412,
    "type": "shape",
    "name": "_могила",
    "shape": "custom",
    "color": "#930000",
    "x": 3393.08,
    "y": 1314.15,
    "width": 60,
    "height": 60,
    "curr_hp": 0,
    "endedTurn": false
  },
  {
    "id": 413,
    "type": "shape",
    "name": "Кристалл_души",
    "shape": "custom",
    "color": "#930000",
    "x": 3199.49,
    "y": 1334.05,
    "width": 60,
    "height": 60,
    "src": "",
    "curr_hp": 0,
    "endedTurn": false
  },
  {
    "id": 414,
    "type": "shape",
    "name": "Тень_Усопшего",
    "shape": "custom",
    "color": "#930000",
    "x": 4220.27,
    "y": 2105.35,
    "width": 60,
    "height": 60,
    "curr_hp": 3,
    "endedTurn": false
  },
  {
    "id": 418,
    "type": "shape",
    "name": "Закрытая_дверь",
    "shape": "custom",
    "color": "#d3d3d3",
    "x": 3181.27,
    "y": 1802.73,
    "width": 60,
    "height": 60,
    "curr_hp": 6,
    "endedTurn": false
  },
  {
    "id": 429,
    "type": "shape",
    "name": "_могила",
    "shape": "custom",
    "color": "#d3d3d3",
    "x": 4083.45,
    "y": 1901.9,
    "width": 60,
    "height": 60,
    "curr_hp": 1,
    "endedTurn": false
  },
  {
    "id": 430,
    "type": "shape",
    "name": "Закрытая_дверь",
    "shape": "custom",
    "color": "#d3d3d3",
    "x": 959.81,
    "y": 1694.92,
    "width": 60,
    "height": 60,
    "src": "",
    "curr_hp": 6,
    "endedTurn": false
  },
  {
    "id": 432,
    "type": "shape",
    "name": "Кровавый_змей",
    "shape": "custom",
    "color": "#d3d3d3",
    "x": 3583.73,
    "y": 2349.93,
    "width": 60,
    "height": 60,
    "curr_hp": 3,
    "endedTurn": false,
    "title": "Инж1",
    "src": ""
  },
  {
    "id": 434,
    "type": "shape",
    "name": "_обломки",
    "shape": "custom",
    "color": "#d3d3d3",
    "x": 3482.12,
    "y": 2166.88,
    "width": 60,
    "height": 60,
    "curr_hp": 0,
    "endedTurn": false
  },
  {
    "id": 435,
    "type": "shape",
    "name": "Кристалл_души",
    "shape": "custom",
    "color": "#930000",
    "x": 3480.45,
    "y": 1319.56,
    "width": 60,
    "height": 60,
    "src": "",
    "curr_hp": 0,
    "endedTurn": false
  },
  {
    "id": 442,
    "type": "shape",
    "name": "Кровь_колодца",
    "shape": "custom",
    "color": "#d3d3d3",
    "x": 3486.68,
    "y": 2100.66,
    "width": 60,
    "height": 60,
    "curr_hp": 1,
    "endedTurn": false
  },
  {
    "id": 443,
    "type": "shape",
    "name": "Кровь_колодца",
    "shape": "custom",
    "color": "#d3d3d3",
    "x": 3880.21,
    "y": 2214.62,
    "width": 60,
    "height": 60,
    "src": "",
    "curr_hp": 1,
    "endedTurn": false
  },
  {
    "id": 444,
    "type": "shape",
    "name": "Кровь_колодца",
    "shape": "custom",
    "color": "#d3d3d3",
    "x": 4095.39,
    "y": 2102.61,
    "width": 60,
    "height": 60,
    "curr_hp": 1,
    "endedTurn": false
  },
  {
    "id": 447,
    "type": "shape",
    "name": "_обломки",
    "shape": "custom",
    "color": "#d3d3d3",
    "x": 1666.38,
    "y": 697.84,
    "width": 60,
    "height": 60,
    "curr_hp": 1,
    "endedTurn": false
  },
  {
    "id": 450,
    "type": "shape",
    "name": "_обломки",
    "shape": "custom",
    "color": "#d3d3d3",
    "x": 3269.33,
    "y": 1404.66,
    "width": 60,
    "height": 60,
    "curr_hp": 1,
    "endedTurn": false
  },
  {
    "id": 452,
    "type": "shape",
    "name": "_info_",
    "shape": "custom",
    "color": "#d3d3d3",
    "x": 1295.37,
    "y": 1577.91,
    "width": 60,
    "height": 60,
    "curr_hp": 3,
    "endedTurn": false,
    "title": "Коридор обожжен лучистым ударом"
  },
  {
    "id": 453,
    "type": "shape",
    "name": "_могила",
    "shape": "custom",
    "color": "#930000",
    "x": 1255.8,
    "y": 1477.3,
    "width": 60,
    "height": 60,
    "curr_hp": 1,
    "endedTurn": false,
    "title": "Голем-паук"
  },
  {
    "id": 457,
    "type": "shape",
    "name": "Движетель",
    "shape": "custom",
    "color": "#d3d3d3",
    "x": 1859.81,
    "y": 1685.35,
    "width": 80,
    "height": 80,
    "curr_hp": 3,
    "endedTurn": false
  },
  {
    "id": 458,
    "type": "shape",
    "name": "Движетель",
    "shape": "custom",
    "color": "#d3d3d3",
    "x": 2870.61,
    "y": 1689.64,
    "width": 80,
    "height": 80,
    "curr_hp": 3,
    "endedTurn": false
  },
  {
    "id": 462,
    "type": "shape",
    "name": "Цепи_движетеля",
    "shape": "custom",
    "color": "#d3d3d3",
    "x": 1770.02,
    "y": 1597.7,
    "width": 60,
    "height": 60,
    "curr_hp": 1,
    "endedTurn": false
  },
  {
    "id": 463,
    "type": "shape",
    "name": "Цепи_движетеля",
    "shape": "custom",
    "color": "#d3d3d3",
    "x": 1971.75,
    "y": 1600.92,
    "width": 60,
    "height": 60,
    "curr_hp": 1,
    "endedTurn": false
  },
  {
    "id": 464,
    "type": "shape",
    "name": "Цепи_движетеля",
    "shape": "custom",
    "color": "#d3d3d3",
    "x": 1866.59,
    "y": 1793,
    "width": 60,
    "height": 60,
    "curr_hp": 1,
    "endedTurn": false
  },
  {
    "id": 465,
    "type": "shape",
    "name": "Цепи_движетеля",
    "shape": "custom",
    "color": "#d3d3d3",
    "x": 2779.75,
    "y": 1603.07,
    "width": 60,
    "height": 60,
    "curr_hp": 1,
    "endedTurn": false
  },
  {
    "id": 466,
    "type": "shape",
    "name": "Цепи_движетеля",
    "shape": "custom",
    "color": "#d3d3d3",
    "x": 2983.62218652915,
    "y": 1595.5578161436044,
    "width": 60,
    "height": 60,
    "curr_hp": 1,
    "endedTurn": false
  },
  {
    "id": 467,
    "type": "shape",
    "name": "Цепи_движетеля",
    "shape": "custom",
    "color": "#d3d3d3",
    "x": 2876.32,
    "y": 1790.85,
    "width": 60,
    "height": 60,
    "curr_hp": 1,
    "endedTurn": false
  },
  {
    "id": 468,
    "type": "shape",
    "name": "Закрытая_дверь",
    "shape": "custom",
    "color": "#d3d3d3",
    "x": 2357.81,
    "y": 974.97,
    "width": 100,
    "height": 100,
    "curr_hp": 6,
    "endedTurn": false
  },
  {
    "id": 470,
    "type": "shape",
    "name": "Портальный_чертог",
    "shape": "custom",
    "color": "#d3d3d3",
    "x": 2364.28,
    "y": 1285.8,
    "width": 80,
    "height": 80,
    "curr_hp": 3,
    "endedTurn": false
  },
  {
    "id": 471,
    "type": "shape",
    "name": "Звёздная_Арка",
    "shape": "custom",
    "color": "#d3d3d3",
    "x": 2283.2,
    "y": 1298.26,
    "width": 60,
    "height": 60,
    "curr_hp": 3,
    "endedTurn": false
  },
  {
    "id": 473,
    "type": "shape",
    "name": "Дыхательная_маска",
    "shape": "custom",
    "color": "#d3d3d3",
    "x": 2503.26,
    "y": 1126.5,
    "width": 40,
    "height": 40,
    "curr_hp": 1,
    "endedTurn": false
  },
  {
    "id": 475,
    "type": "shape",
    "name": "Коагулянт-гель",
    "shape": "custom",
    "color": "#d3d3d3",
    "x": 2462.03,
    "y": 1081.69,
    "width": 40,
    "height": 40,
    "curr_hp": 1,
    "endedTurn": false,
    "src": ""
  },
  {
    "id": 476,
    "type": "shape",
    "name": "Ремонтный_набор",
    "shape": "custom",
    "color": "#d3d3d3",
    "x": 2308.3,
    "y": 1083.28,
    "width": 40,
    "height": 40,
    "curr_hp": 1,
    "endedTurn": false,
    "src": ""
  },
  {
    "id": 477,
    "type": "shape",
    "name": "Инъектор_подавления",
    "shape": "custom",
    "color": "#d3d3d3",
    "x": 2506.23,
    "y": 1084.01,
    "width": 40,
    "height": 40,
    "curr_hp": 1,
    "endedTurn": false,
    "src": ""
  },
  {
    "id": 478,
    "type": "shape",
    "name": "Соляная_граната",
    "shape": "custom",
    "color": "#d3d3d3",
    "x": 2616.92,
    "y": 1121,
    "width": 40,
    "height": 40,
    "curr_hp": 1,
    "endedTurn": false
  },
  {
    "id": 479,
    "type": "shape",
    "name": "Аварийный_накопитель",
    "shape": "custom",
    "color": "#d3d3d3",
    "x": 2310.7,
    "y": 1128.39,
    "width": 40,
    "height": 40,
    "curr_hp": 1,
    "endedTurn": false,
    "src": ""
  },
  {
    "id": 480,
    "type": "shape",
    "name": "Переносной_Алтарь",
    "shape": "custom",
    "color": "#d3d3d3",
    "x": 2574.03,
    "y": 1081.74,
    "width": 40,
    "height": 40,
    "curr_hp": 1,
    "endedTurn": false
  },
  {
    "id": 481,
    "type": "shape",
    "name": "Кристалл_души",
    "shape": "custom",
    "color": "#d3d3d3",
    "x": 2616.64,
    "y": 1078.64,
    "width": 40,
    "height": 40,
    "curr_hp": 1,
    "endedTurn": false
  },
  {
    "id": 482,
    "type": "shape",
    "name": "Пси-сканер",
    "shape": "custom",
    "color": "#d3d3d3",
    "x": 2268.97,
    "y": 1079.6,
    "width": 40,
    "height": 40,
    "curr_hp": 1,
    "endedTurn": false,
    "src": ""
  },
  {
    "id": 484,
    "type": "shape",
    "name": "Пси-клинок",
    "shape": "custom",
    "color": "#0000ff",
    "x": 4764.06,
    "y": 579.63,
    "width": 60,
    "height": 60,
    "curr_hp": 3,
    "endedTurn": false,
    "title": "Квартермейстер"
  },
  {
    "id": 485,
    "type": "shape",
    "name": "Обзор",
    "shape": "custom",
    "color": "#d3d3d3",
    "x": 2164.96,
    "y": 1082.43,
    "width": 40,
    "height": 40,
    "curr_hp": 3,
    "endedTurn": false
  },
  {
    "id": 486,
    "type": "shape",
    "name": "Обзор",
    "shape": "custom",
    "color": "#d3d3d3",
    "x": 2607.34,
    "y": 1422.31,
    "width": 40,
    "height": 40,
    "curr_hp": 3,
    "endedTurn": false
  },
  {
    "id": 489,
    "type": "shape",
    "name": "Контрольное_кресло",
    "shape": "custom",
    "color": "#d3d3d3",
    "x": 1990.08,
    "y": 1714.02,
    "width": 60,
    "height": 60,
    "src": "",
    "curr_hp": 1,
    "endedTurn": false,
    "title": "Контроль"
  },
  {
    "id": 490,
    "type": "shape",
    "name": "Контрольное_кресло",
    "shape": "custom",
    "color": "#d3d3d3",
    "x": 2804.24,
    "y": 1712.9,
    "width": 60,
    "height": 60,
    "curr_hp": 1,
    "endedTurn": false,
    "title": "Контроль"
  },
  {
    "id": 491,
    "type": "shape",
    "name": "И_Эктор",
    "shape": "custom",
    "color": "#0000ff",
    "x": 4607.51,
    "y": 979.28,
    "width": 60,
    "height": 60,
    "src": "",
    "curr_hp": 3,
    "endedTurn": false,
    "title": "Эктор"
  },
  {
    "id": 492,
    "type": "shape",
    "name": "Хранитель",
    "shape": "custom",
    "color": "#d3d3d3",
    "x": 2366.18,
    "y": 1373.71,
    "width": 60,
    "height": 60,
    "curr_hp": 3,
    "endedTurn": false
  },
  {
    "id": 493,
    "type": "shape",
    "name": "Пси-клинок",
    "shape": "custom",
    "color": "#d3d3d3",
    "x": 2753.82,
    "y": 1221.14,
    "width": 60,
    "height": 60,
    "curr_hp": 3,
    "endedTurn": false
  },
  {
    "id": 494,
    "type": "shape",
    "name": "Кровать",
    "shape": "custom",
    "color": "#d3d3d3",
    "x": 2797.76,
    "y": 1407.43,
    "width": 60,
    "height": 60,
    "curr_hp": 1,
    "endedTurn": false
  },
  {
    "id": 495,
    "type": "shape",
    "name": "Кровать",
    "shape": "custom",
    "color": "#d3d3d3",
    "x": 2802.01,
    "y": 1314.95,
    "width": 60,
    "height": 60,
    "curr_hp": 1,
    "endedTurn": false
  },
  {
    "id": 496,
    "type": "shape",
    "name": "Кровать",
    "shape": "custom",
    "color": "#d3d3d3",
    "x": 2803.07,
    "y": 1111.91,
    "width": 60,
    "height": 60,
    "curr_hp": 1,
    "endedTurn": false
  },
  {
    "id": 497,
    "type": "shape",
    "name": "Кровать",
    "shape": "custom",
    "color": "#d3d3d3",
    "x": 2802.01,
    "y": 1013.05,
    "width": 60,
    "height": 60,
    "curr_hp": 1,
    "endedTurn": false
  },
  {
    "id": 502,
    "type": "shape",
    "name": "Кровемёт",
    "shape": "custom",
    "color": "#d3d3d3",
    "x": 2166.59,
    "y": 1126.61,
    "width": 40,
    "height": 40,
    "curr_hp": 1,
    "endedTurn": false,
    "lvl": 4
  },
  {
    "id": 503,
    "type": "shape",
    "name": "Кровемёт",
    "shape": "custom",
    "color": "#d3d3d3",
    "x": 2209.19,
    "y": 1124.23,
    "width": 40,
    "height": 40,
    "curr_hp": 1,
    "endedTurn": false,
    "lvl": 4
  },
  {
    "id": 505,
    "type": "shape",
    "name": "Хранитель",
    "shape": "custom",
    "color": "#d3d3d3",
    "x": 2766.68,
    "y": 1681.15,
    "width": 60,
    "height": 60,
    "curr_hp": 3,
    "endedTurn": false
  },
  {
    "id": 507,
    "type": "shape",
    "name": "Копир-скрижаль",
    "shape": "custom",
    "color": "#d3d3d3",
    "x": 2768.86,
    "y": 1835.09,
    "width": 40,
    "height": 40,
    "src": "",
    "curr_hp": 1,
    "endedTurn": false
  },
  {
    "id": 508,
    "type": "shape",
    "name": "Ремонтный_набор",
    "shape": "custom",
    "color": "#d3d3d3",
    "x": 2817.36,
    "y": 1786.58,
    "width": 40,
    "height": 40,
    "src": "",
    "curr_hp": 1,
    "endedTurn": false
  },
  {
    "id": 509,
    "type": "shape",
    "name": "Коагулянт-гель",
    "shape": "custom",
    "color": "#d3d3d3",
    "x": 2818.92,
    "y": 1830.39,
    "width": 40,
    "height": 40,
    "src": "",
    "curr_hp": 1,
    "endedTurn": false
  },
  {
    "id": 510,
    "type": "shape",
    "name": "Копир-скрижаль",
    "shape": "custom",
    "color": "#d3d3d3",
    "x": 1955.07,
    "y": 1832.47,
    "width": 40,
    "height": 40,
    "curr_hp": 1,
    "endedTurn": false
  },
  {
    "id": 511,
    "type": "shape",
    "name": "Ремонтный_набор",
    "shape": "custom",
    "color": "#d3d3d3",
    "x": 2008.64,
    "y": 1789.78,
    "width": 40,
    "height": 40,
    "curr_hp": 1,
    "endedTurn": false
  },
  {
    "id": 512,
    "type": "shape",
    "name": "Коагулянт-гель",
    "shape": "custom",
    "color": "#d3d3d3",
    "x": 2004.11,
    "y": 1833.37,
    "width": 40,
    "height": 40,
    "curr_hp": 1,
    "endedTurn": false
  },
  {
    "id": 514,
    "type": "shape",
    "name": "Закрытая_дверь",
    "shape": "custom",
    "color": "#d3d3d3",
    "x": 1875.23,
    "y": 1495.33,
    "width": 60,
    "height": 60,
    "curr_hp": 6,
    "endedTurn": false
  },
  {
    "id": 515,
    "type": "shape",
    "name": "Закрытая_дверь",
    "shape": "custom",
    "color": "#d3d3d3",
    "x": 2800.77,
    "y": 1497.63,
    "width": 60,
    "height": 60,
    "curr_hp": 6,
    "endedTurn": false
  },
  {
    "id": 517,
    "type": "shape",
    "name": "Карта_корабля",
    "shape": "custom",
    "color": "#d3d3d3",
    "x": 1976.6,
    "y": 989.68,
    "width": 60,
    "height": 60,
    "curr_hp": 3,
    "endedTurn": false
  },
  {
    "id": 518,
    "type": "shape",
    "name": "Контрольное_кресло",
    "shape": "custom",
    "color": "#d3d3d3",
    "x": 1989.79,
    "y": 1111.05,
    "width": 60,
    "height": 60,
    "curr_hp": 1,
    "endedTurn": false
  },
  {
    "id": 519,
    "type": "shape",
    "name": "NPC_Си",
    "shape": "custom",
    "color": "#0000ff",
    "x": 4601.87,
    "y": 878.05,
    "width": 60,
    "height": 60,
    "src": "",
    "curr_hp": 4,
    "endedTurn": false,
    "lvl": 1,
    "title": "Си"
  },
  {
    "id": 520,
    "type": "shape",
    "name": "И_ТТ",
    "shape": "custom",
    "color": "#0000ff",
    "x": 4713.61,
    "y": 1002.26,
    "width": 60,
    "height": 60,
    "src": "",
    "curr_hp": 4,
    "endedTurn": false,
    "lvl": 1,
    "title": "ТэТэ"
  },
  {
    "id": 521,
    "type": "shape",
    "name": "И_SUN",
    "shape": "custom",
    "color": "#0000ff",
    "x": 4703.54,
    "y": 886.44,
    "width": 60,
    "height": 60,
    "curr_hp": 3,
    "endedTurn": false,
    "src": "",
    "title": "SUN"
  },
  {
    "id": 523,
    "type": "shape",
    "name": "Кровемёт",
    "shape": "custom",
    "color": "#d3d3d3",
    "x": 4574.91,
    "y": 964.25,
    "width": 40,
    "height": 40,
    "curr_hp": 1,
    "endedTurn": false,
    "lvl": 4
  },
  {
    "id": 524,
    "type": "shape",
    "name": "Дыхательная_маска",
    "shape": "custom",
    "color": "#d3d3d3",
    "x": 4642.84,
    "y": 950.92,
    "width": 40,
    "height": 40,
    "curr_hp": 1,
    "endedTurn": false,
    "src": ""
  },
  {
    "id": 525,
    "type": "shape",
    "name": "Парализующий_амулет",
    "shape": "custom",
    "color": "#d3d3d3",
    "x": 4569.83,
    "y": 1009.92,
    "width": 40,
    "height": 40,
    "curr_hp": 1,
    "endedTurn": false,
    "lvl": 3,
    "src": ""
  },
  {
    "id": 526,
    "type": "shape",
    "name": "Соляная_граната",
    "shape": "custom",
    "color": "#d3d3d3",
    "x": 4606.63,
    "y": 938.86,
    "width": 40,
    "height": 40,
    "curr_hp": 1,
    "endedTurn": false,
    "src": ""
  },
  {
    "id": 527,
    "type": "shape",
    "name": "_обломки",
    "shape": "custom",
    "color": "#d3d3d3",
    "x": 4485.31,
    "y": 971.74,
    "width": 80,
    "height": 80,
    "curr_hp": 1,
    "endedTurn": false
  },
  {
    "id": 529,
    "type": "shape",
    "name": "Обзор",
    "shape": "custom",
    "color": "#0000ff",
    "x": 4592.73,
    "y": 1056.57,
    "width": 40,
    "height": 40,
    "src": "",
    "curr_hp": 3,
    "endedTurn": false
  },
  {
    "id": 530,
    "type": "shape",
    "name": "Обзор",
    "shape": "custom",
    "color": "#0000ff",
    "x": 4586.610872992588,
    "y": 811.3361994793903,
    "width": 40,
    "height": 40,
    "src": "",
    "curr_hp": 3,
    "endedTurn": false
  },
  {
    "id": 531,
    "type": "shape",
    "name": "Обзор",
    "shape": "custom",
    "color": "#0000ff",
    "x": 4951.58,
    "y": 1007.18,
    "width": 40,
    "height": 40,
    "curr_hp": 3,
    "endedTurn": false,
    "src": ""
  },
  {
    "id": 532,
    "type": "shape",
    "name": "Дыхательная_маска",
    "shape": "custom",
    "color": "#d3d3d3",
    "x": 4741.46,
    "y": 962.71,
    "width": 40,
    "height": 40,
    "src": "",
    "curr_hp": 1,
    "endedTurn": false
  },
  {
    "id": 533,
    "type": "shape",
    "name": "Коагулянт-гель",
    "shape": "custom",
    "color": "#d3d3d3",
    "x": 4721.7,
    "y": 963.16,
    "width": 40,
    "height": 40,
    "curr_hp": 1,
    "endedTurn": false,
    "lvl": 3,
    "src": ""
  },
  {
    "id": 534,
    "type": "shape",
    "name": "Инъектор_подавления",
    "shape": "custom",
    "color": "#d3d3d3",
    "x": 4696.37,
    "y": 970.51,
    "width": 40,
    "height": 40,
    "curr_hp": 1,
    "endedTurn": false,
    "src": ""
  },
  {
    "id": 535,
    "type": "shape",
    "name": "Пробник_Колодца",
    "shape": "custom",
    "color": "#d3d3d3",
    "x": 4679.78,
    "y": 1012.84,
    "width": 40,
    "height": 40,
    "curr_hp": 1,
    "endedTurn": false
  },
  {
    "id": 536,
    "type": "shape",
    "name": "Пробник_Колодца",
    "shape": "custom",
    "color": "#d3d3d3",
    "x": 4672.31,
    "y": 994.84,
    "width": 40,
    "height": 40,
    "curr_hp": 1,
    "endedTurn": false
  },
  {
    "id": 537,
    "type": "shape",
    "name": "Дыхательная_маска",
    "shape": "custom",
    "color": "#d3d3d3",
    "x": 4727.6,
    "y": 854.24,
    "width": 40,
    "height": 40,
    "curr_hp": 1,
    "endedTurn": false
  },
  {
    "id": 538,
    "type": "shape",
    "name": "Ремонтный_набор",
    "shape": "custom",
    "color": "#d3d3d3",
    "x": 4698.54,
    "y": 850.44,
    "width": 40,
    "height": 40,
    "curr_hp": 1,
    "endedTurn": false,
    "lvl": 2
  },
  {
    "id": 539,
    "type": "shape",
    "name": "Аварийный_накопитель",
    "shape": "custom",
    "color": "#d3d3d3",
    "x": 4679.37,
    "y": 861.01,
    "width": 40,
    "height": 40,
    "curr_hp": 1,
    "endedTurn": false
  },
  {
    "id": 540,
    "type": "shape",
    "name": "Пси-сканер",
    "shape": "custom",
    "color": "#d3d3d3",
    "x": 4670.89,
    "y": 894.6,
    "width": 40,
    "height": 40,
    "curr_hp": 1,
    "endedTurn": false,
    "lvl": 3
  },
  {
    "id": 541,
    "type": "shape",
    "name": "NPC_Ляо",
    "shape": "custom",
    "color": "#0000ff",
    "x": 4673.01,
    "y": 757.92,
    "width": 60,
    "height": 60,
    "src": "",
    "curr_hp": 3,
    "endedTurn": false,
    "title": "Ляо"
  },
  {
    "id": 542,
    "type": "shape",
    "name": "Парализующий_амулет",
    "shape": "custom",
    "color": "#d3d3d3",
    "x": 4566.12,
    "y": 883.8,
    "width": 40,
    "height": 40,
    "curr_hp": 1,
    "endedTurn": false,
    "lvl": 3
  },
  {
    "id": 543,
    "type": "shape",
    "name": "Соляная_граната",
    "shape": "custom",
    "color": "#d3d3d3",
    "x": 4586.3,
    "y": 843.72,
    "width": 40,
    "height": 40,
    "curr_hp": 1,
    "endedTurn": false
  },
  {
    "id": 544,
    "type": "shape",
    "name": "Дыхательная_маска",
    "shape": "custom",
    "color": "#d3d3d3",
    "x": 4616.76,
    "y": 836.86,
    "width": 40,
    "height": 40,
    "src": "",
    "curr_hp": 1,
    "endedTurn": false
  },
  {
    "id": 545,
    "type": "shape",
    "name": "Дыхательная_маска",
    "shape": "custom",
    "color": "#d3d3d3",
    "x": 4703.43,
    "y": 727.65,
    "width": 40,
    "height": 40,
    "curr_hp": 1,
    "endedTurn": false
  },
  {
    "id": 546,
    "type": "shape",
    "name": "Коагулянт-гель",
    "shape": "custom",
    "color": "#d3d3d3",
    "x": 4671.97,
    "y": 724.52,
    "width": 40,
    "height": 40,
    "curr_hp": 1,
    "endedTurn": false,
    "lvl": 3
  },
  {
    "id": 547,
    "type": "shape",
    "name": "Инъектор_подавления",
    "shape": "custom",
    "color": "#d3d3d3",
    "x": 4642.17,
    "y": 740.87,
    "width": 40,
    "height": 40,
    "curr_hp": 1,
    "endedTurn": false
  },
  {
    "id": 548,
    "type": "shape",
    "name": "Кристалл_души",
    "shape": "custom",
    "color": "#d3d3d3",
    "x": 4633.9,
    "y": 774.82,
    "width": 40,
    "height": 40,
    "curr_hp": 1,
    "endedTurn": false
  },
  {
    "id": 549,
    "type": "shape",
    "name": "Обзор",
    "shape": "custom",
    "color": "#0000ff",
    "x": 4930.31,
    "y": 732.54,
    "width": 40,
    "height": 40,
    "curr_hp": 3,
    "endedTurn": false
  }
]