CURRENT_TURN=2;
OTHER_SAVE_DATA={
  "scale": 0.5799842550423899,
  "canvasOffsetX": -330.0647547210773,
  "canvasOffsetY": -695.4585164933422,
  "shapeColor": "#008000"
};
USER_RESOURCES={
  "Нейтралы": {},
  "Враги": {
    "Еда": 0,
    "Металл": 0
  },
  "Десант": {
    "Еда": 0,
    "Металл": 32,
    "Кремний": 26,
    "Уран": 14.5,
    "Наука": 2
  },
  "Варвары": {},
  "Колорады": {
    "Металл": 28,
    "Кремний": 32,
    "Уран": 12.5,
    "Наука": 2
  }
};
USER_TECH_LVLS={
  "Десант": {
    "Энергетика": 0,
    "Двигатели": 0,
    "Социология": 0,
    "Биология": 0,
    "Оружие": 0,
    "Броня": 0,
    "Энерго-оружие": 0,
    "Щиты": 0
  },
  "Нейтралы": {},
  "Варвары": {},
  "Колорады": {
    "Энергетика": 0,
    "Двигатели": 0,
    "Социология": 0,
    "Биология": 0,
    "Оружие": 0,
    "Броня": 0,
    "Энерго-оружие": 0,
    "Щиты": 0
  }
};
OWNER_MAP={"16":[15],"23":[1]};
DEFAULT_DATA=[
  {
    "id": 1,
    "type": "shape",
    "name": "Холодный_мир",
    "shape": "custom",
    "color": "#0000ff",
    "x": 349.41,
    "y": 369.82,
    "width": 60,
    "height": 60,
    "src": "pokras-spc/images/buildings/Холодный_мир.png",
    "curr_hp": 1,
    "endedTurn": false,
    "lvl": 1
  },
  {
    "id": 6,
    "type": "shape",
    "name": "Столица",
    "shape": "custom",
    "color": "#0000ff",
    "x": 484.39,
    "y": 257.48,
    "width": 50,
    "height": 50,
    "curr_hp": 1,
    "endedTurn": false
  },
  {
    "id": 9,
    "type": "shape",
    "name": "Безжизненный_мир",
    "shape": "custom",
    "color": "#008000",
    "x": 1322.57,
    "y": 1801.97,
    "width": 50,
    "height": 50,
    "src": "pokras-spc/images/buildings/Безжизненный_мир.png",
    "curr_hp": 1,
    "disabled": 1,
    "endedTurn": false
  },
  {
    "id": 11,
    "type": "shape",
    "name": "Газовый_гигант",
    "shape": "custom",
    "color": "#008000",
    "x": 1541.39,
    "y": 1804.47,
    "width": 50,
    "height": 50,
    "src": "pokras-spc/images/buildings/Газовый_гигант.png",
    "curr_hp": 1,
    "disabled": 1,
    "endedTurn": false
  },
  {
    "id": 13,
    "type": "shape",
    "name": "Умеренный_мир",
    "shape": "custom",
    "color": "#008000",
    "x": 1541.39,
    "y": 2007.04,
    "width": 50,
    "height": 50,
    "src": "pokras-spc/images/buildings/Умеренный_мир.png",
    "curr_hp": 1,
    "disabled": 1,
    "endedTurn": false
  },
  {
    "id": 14,
    "type": "shape",
    "name": "Столица",
    "shape": "custom",
    "color": "#008000",
    "x": 1455.85,
    "y": 1890.14,
    "width": 50,
    "height": 50,
    "curr_hp": 1,
    "endedTurn": false
  },
  {
    "id": 15,
    "type": "shape",
    "name": "Горячий_мир",
    "shape": "custom",
    "color": "#008000",
    "x": 1328.54,
    "y": 2010.24,
    "width": 50,
    "height": 50,
    "src": "pokras-spc/images/buildings/Горячий_мир.png",
    "curr_hp": 1,
    "endedTurn": false
  },
  {
    "id": 16,
    "type": "shape",
    "name": "Развитая_колония",
    "shape": "custom",
    "color": "#008000",
    "x": 1335.19,
    "y": 2006.53,
    "width": 40,
    "height": 40,
    "curr_hp": 1,
    "endedTurn": false
  },
  {
    "id": 17,
    "type": "shape",
    "name": "Верфь",
    "shape": "custom",
    "color": "#008000",
    "x": 1329.91,
    "y": 1961.23,
    "width": 40,
    "height": 40,
    "curr_hp": 1,
    "endedTurn": false
  },
  {
    "id": 18,
    "type": "shape",
    "name": "Фрегат",
    "shape": "custom",
    "color": "#008000",
    "x": 1457.45,
    "y": 2189.55,
    "width": 40,
    "height": 40,
    "src": "pokras-spc/images/units/Фрегат.png",
    "curr_hp": 1,
    "endedTurn": false
  },
  {
    "id": 19,
    "type": "shape",
    "name": "Колонизатор",
    "shape": "custom",
    "color": "#008000",
    "x": 1892.19,
    "y": 1593.09,
    "width": 40,
    "height": 40,
    "curr_hp": 1,
    "endedTurn": false
  },
  {
    "id": 20,
    "type": "shape",
    "name": "Строитель",
    "shape": "custom",
    "color": "#008000",
    "x": 1789.33,
    "y": 1892.47,
    "width": 40,
    "height": 40,
    "curr_hp": 1,
    "endedTurn": false
  },
  {
    "id": 21,
    "type": "shape",
    "name": "Горячий_мир",
    "shape": "custom",
    "color": "#0000ff",
    "x": 351.99,
    "y": 173.48,
    "width": 50,
    "height": 50,
    "src": "pokras-spc/images/buildings/Горячий_мир.png",
    "curr_hp": 1,
    "disabled": 1,
    "endedTurn": false
  },
  {
    "id": 22,
    "type": "shape",
    "name": "Газовый_гигант",
    "shape": "custom",
    "color": "#0000ff",
    "x": 568.58,
    "y": 174.91,
    "width": 50,
    "height": 50,
    "src": "pokras-spc/images/buildings/Газовый_гигант.png",
    "curr_hp": 1,
    "disabled": 1,
    "endedTurn": false
  },
  {
    "id": 23,
    "type": "shape",
    "name": "Развитая_колония",
    "shape": "custom",
    "color": "#0000ff",
    "x": 355.93,
    "y": 380.75,
    "width": 40,
    "height": 40,
    "curr_hp": 1,
    "endedTurn": false
  },
  {
    "id": 24,
    "type": "shape",
    "name": "Верфь",
    "shape": "custom",
    "color": "#0000ff",
    "x": 350.35,
    "y": 327.73,
    "width": 40,
    "height": 40,
    "curr_hp": 1,
    "endedTurn": false
  },
  {
    "id": 25,
    "type": "shape",
    "name": "Колонизатор",
    "shape": "custom",
    "color": "#0000ff",
    "x": 169.9,
    "y": 167.76,
    "width": 40,
    "height": 40,
    "curr_hp": 1,
    "endedTurn": false
  },
  {
    "id": 26,
    "type": "shape",
    "name": "Строитель",
    "shape": "custom",
    "color": "#0000ff",
    "x": 1030.13,
    "y": 374.23,
    "width": 40,
    "height": 40,
    "curr_hp": 1,
    "endedTurn": false
  },
  {
    "id": 27,
    "type": "shape",
    "name": "Фрегат",
    "shape": "custom",
    "color": "#0000ff",
    "x": 510.96,
    "y": 850.11,
    "width": 40,
    "height": 40,
    "src": "pokras-spc/images/units/Фрегат.png",
    "curr_hp": 1,
    "endedTurn": false
  },
  {
    "id": 28,
    "type": "shape",
    "name": "Горячий_мир",
    "shape": "custom",
    "color": "#d3d3d3",
    "x": 24.55,
    "y": 171.95,
    "width": 50,
    "height": 50,
    "src": "pokras-spc/images/buildings/Горячий_мир.png",
    "curr_hp": 1,
    "disabled": 1,
    "endedTurn": false
  },
  {
    "id": 30,
    "type": "shape",
    "name": "Безжизненный_мир",
    "shape": "custom",
    "color": "#d3d3d3",
    "x": 179.35,
    "y": 63.87,
    "width": 50,
    "height": 50,
    "src": "pokras-spc/images/buildings/Безжизненный_мир.png",
    "curr_hp": 1,
    "disabled": 1,
    "endedTurn": false
  },
  {
    "id": 31,
    "type": "shape",
    "name": "Водный_мир",
    "shape": "custom",
    "color": "#d3d3d3",
    "x": 355.22,
    "y": 783.84,
    "width": 50,
    "height": 50,
    "src": "pokras-spc/images/buildings/Водный_мир.png",
    "curr_hp": 1,
    "disabled": 1,
    "endedTurn": false
  },
  {
    "id": 32,
    "type": "shape",
    "name": "Водный_мир",
    "shape": "custom",
    "color": "#d3d3d3",
    "x": 566.81,
    "y": 985.36,
    "width": 50,
    "height": 50,
    "src": "pokras-spc/images/buildings/Водный_мир.png",
    "curr_hp": 1,
    "disabled": 1,
    "endedTurn": false
  },
  {
    "id": 33,
    "type": "shape",
    "name": "Умеренный_мир",
    "shape": "custom",
    "color": "#d3d3d3",
    "x": 891.08,
    "y": 278.21,
    "width": 50,
    "height": 50,
    "src": "pokras-spc/images/buildings/Умеренный_мир.png",
    "curr_hp": 1,
    "disabled": 1,
    "endedTurn": false
  },
  {
    "id": 34,
    "type": "shape",
    "name": "Водный_мир",
    "shape": "custom",
    "color": "#d3d3d3",
    "x": 1109.08,
    "y": 279.12,
    "width": 50,
    "height": 50,
    "src": "pokras-spc/images/buildings/Водный_мир.png",
    "curr_hp": 1,
    "disabled": 1,
    "endedTurn": false
  },
  {
    "id": 35,
    "type": "shape",
    "name": "Холодный_мир",
    "shape": "custom",
    "color": "#d3d3d3",
    "x": 1107.25,
    "y": 480.64,
    "width": 50,
    "height": 50,
    "src": "pokras-spc/images/buildings/Холодный_мир.png",
    "curr_hp": 1,
    "disabled": 1,
    "endedTurn": false
  },
  {
    "id": 36,
    "type": "shape",
    "name": "Газовый_гигант",
    "shape": "custom",
    "color": "#d3d3d3",
    "x": 1327.52,
    "y": 2304.43,
    "width": 50,
    "height": 50,
    "src": "pokras-spc/images/buildings/Газовый_гигант.png",
    "curr_hp": 1,
    "disabled": 1,
    "endedTurn": false
  },
  {
    "id": 37,
    "type": "shape",
    "name": "Холодный_мир",
    "shape": "custom",
    "color": "#d3d3d3",
    "x": 1654.32,
    "y": 2007.8,
    "width": 50,
    "height": 50,
    "src": "pokras-spc/images/buildings/Холодный_мир.png",
    "curr_hp": 1,
    "disabled": 1,
    "endedTurn": false
  },
  {
    "id": 38,
    "type": "shape",
    "name": "Безжизненный_мир",
    "shape": "custom",
    "color": "#d3d3d3",
    "x": 1756.13,
    "y": 1506.28,
    "width": 50,
    "height": 50,
    "src": "pokras-spc/images/buildings/Безжизненный_мир.png",
    "curr_hp": 1,
    "disabled": 1,
    "endedTurn": false
  },
  {
    "id": 39,
    "type": "shape",
    "name": "Газовый_гигант",
    "shape": "custom",
    "color": "#d3d3d3",
    "x": 1971.07,
    "y": 1501.25,
    "width": 50,
    "height": 50,
    "src": "pokras-spc/images/buildings/Газовый_гигант.png",
    "curr_hp": 1,
    "disabled": 1,
    "endedTurn": false
  },
  {
    "id": 40,
    "type": "shape",
    "name": "Холодный_мир",
    "shape": "custom",
    "color": "#d3d3d3",
    "x": 1756.13,
    "y": 1706.13,
    "width": 50,
    "height": 50,
    "src": "pokras-spc/images/buildings/Холодный_мир.png",
    "curr_hp": 1,
    "disabled": 1,
    "endedTurn": false
  }
]