CURRENT_TURN=9;
OTHER_SAVE_DATA={
  "scale": 0.745265227006311,
  "canvasOffsetX": 189.70580795617093,
  "canvasOffsetY": -1033.9994244883655,
  "shapeColor": "#008000"
};
USER_RESOURCES={
  "Нейтралы": {},
  "Враги": {
    "Еда": 0,
    "Металл": 0
  },
  "Десант": {
    "Еда": 0,
    "Металл": 92,
    "Кремний": 44,
    "Уран": 89,
    "Наука": 9
  },
  "Варвары": {},
  "Колорады": {
    "Металл": 45,
    "Кремний": 98,
    "Уран": 70.5,
    "Наука": 9
  }
};
USER_TECH_LVLS={
  "Десант": {
    "Энергетика": 0,
    "Двигатели": 0,
    "Социология": 1,
    "Биология": 0,
    "Оружие": 0,
    "Металлургия": 0,
    "Энерго-оружие": 0,
    "Щиты": 0
  },
  "Нейтралы": {},
  "Варвары": {},
  "Колорады": {
    "Энергетика": 0,
    "Двигатели": 0,
    "Социология": 1,
    "Биология": 0,
    "Оружие": 0,
    "Металлургия": 0,
    "Энерго-оружие": 0,
    "Щиты": 0
  }
};
OWNER_MAP={"16":[15],"23":[1],"58":[35],"59":[47]};
DEFAULT_DATA=[
  {
    "id": 1,
    "type": "shape",
    "name": "Холодный_мир",
    "shape": "custom",
    "color": "#0000ff",
    "x": 349.41,
    "y": 369.82,
    "width": 60,
    "height": 60,
    "src": "pokras-spc/images/buildings/Холодный_мир.png",
    "curr_hp": 1,
    "endedTurn": false,
    "lvl": 1
  },
  {
    "id": 6,
    "type": "shape",
    "name": "Столица",
    "shape": "custom",
    "color": "#0000ff",
    "x": 484.39,
    "y": 257.48,
    "width": 50,
    "height": 50,
    "curr_hp": 1,
    "endedTurn": false
  },
  {
    "id": 9,
    "type": "shape",
    "name": "Безжизненный_мир",
    "shape": "custom",
    "color": "#008000",
    "x": 1322.57,
    "y": 1801.97,
    "width": 50,
    "height": 50,
    "src": "pokras-spc/images/buildings/Безжизненный_мир.png",
    "curr_hp": 1,
    "endedTurn": false
  },
  {
    "id": 11,
    "type": "shape",
    "name": "Газовый_гигант",
    "shape": "custom",
    "color": "#008000",
    "x": 1541.39,
    "y": 1804.47,
    "width": 50,
    "height": 50,
    "src": "pokras-spc/images/buildings/Газовый_гигант.png",
    "curr_hp": 1,
    "endedTurn": false
  },
  {
    "id": 13,
    "type": "shape",
    "name": "Умеренный_мир",
    "shape": "custom",
    "color": "#008000",
    "x": 1541.39,
    "y": 2007.04,
    "width": 50,
    "height": 50,
    "src": "pokras-spc/images/buildings/Умеренный_мир.png",
    "curr_hp": 1,
    "endedTurn": false
  },
  {
    "id": 14,
    "type": "shape",
    "name": "Столица",
    "shape": "custom",
    "color": "#008000",
    "x": 1455.85,
    "y": 1890.14,
    "width": 50,
    "height": 50,
    "curr_hp": 1,
    "endedTurn": false
  },
  {
    "id": 15,
    "type": "shape",
    "name": "Горячий_мир",
    "shape": "custom",
    "color": "#008000",
    "x": 1327.69,
    "y": 2010.24,
    "width": 50,
    "height": 50,
    "src": "pokras-spc/images/buildings/Горячий_мир.png",
    "curr_hp": 1,
    "endedTurn": false
  },
  {
    "id": 16,
    "type": "shape",
    "name": "Развитая_колония",
    "shape": "custom",
    "color": "#008000",
    "x": 1335.19,
    "y": 2006.53,
    "width": 40,
    "height": 40,
    "curr_hp": 1,
    "endedTurn": false
  },
  {
    "id": 17,
    "type": "shape",
    "name": "Верфь",
    "shape": "custom",
    "color": "#008000",
    "x": 1337.41,
    "y": 1962.27,
    "width": 40,
    "height": 40,
    "curr_hp": 1,
    "endedTurn": false
  },
  {
    "id": 18,
    "type": "shape",
    "name": "Фрегат",
    "shape": "custom",
    "color": "#008000",
    "x": 160.21,
    "y": 1900.12,
    "width": 40,
    "height": 40,
    "src": "pokras-spc/images/units/Фрегат.png",
    "curr_hp": 1,
    "endedTurn": false
  },
  {
    "id": 20,
    "type": "shape",
    "name": "Строитель",
    "shape": "custom",
    "color": "#008000",
    "x": 1061.27,
    "y": 2221.08,
    "width": 40,
    "height": 40,
    "curr_hp": 1,
    "endedTurn": false
  },
  {
    "id": 21,
    "type": "shape",
    "name": "Горячий_мир",
    "shape": "custom",
    "color": "#0000ff",
    "x": 351.99,
    "y": 173.48,
    "width": 50,
    "height": 50,
    "src": "pokras-spc/images/buildings/Горячий_мир.png",
    "curr_hp": 1,
    "endedTurn": false
  },
  {
    "id": 22,
    "type": "shape",
    "name": "Газовый_гигант",
    "shape": "custom",
    "color": "#0000ff",
    "x": 568.58,
    "y": 174.91,
    "width": 50,
    "height": 50,
    "src": "pokras-spc/images/buildings/Газовый_гигант.png",
    "curr_hp": 1,
    "disabled": 1,
    "endedTurn": false
  },
  {
    "id": 23,
    "type": "shape",
    "name": "Развитая_колония",
    "shape": "custom",
    "color": "#0000ff",
    "x": 355.93,
    "y": 380.75,
    "width": 40,
    "height": 40,
    "curr_hp": 1,
    "endedTurn": false
  },
  {
    "id": 24,
    "type": "shape",
    "name": "Верфь",
    "shape": "custom",
    "color": "#0000ff",
    "x": 350.35,
    "y": 327.73,
    "width": 40,
    "height": 40,
    "curr_hp": 1,
    "endedTurn": false
  },
  {
    "id": 26,
    "type": "shape",
    "name": "Строитель",
    "shape": "custom",
    "color": "#0000ff",
    "x": 954.52,
    "y": 1359.38,
    "width": 40,
    "height": 40,
    "curr_hp": 1,
    "endedTurn": false
  },
  {
    "id": 27,
    "type": "shape",
    "name": "Фрегат",
    "shape": "custom",
    "color": "#0000ff",
    "x": 1678.82,
    "y": 106.97,
    "width": 40,
    "height": 40,
    "src": "pokras-spc/images/units/Фрегат.png",
    "curr_hp": 1,
    "endedTurn": false
  },
  {
    "id": 28,
    "type": "shape",
    "name": "Горячий_мир",
    "shape": "custom",
    "color": "#d3d3d3",
    "x": 24.55,
    "y": 171.95,
    "width": 50,
    "height": 50,
    "src": "pokras-spc/images/buildings/Горячий_мир.png",
    "curr_hp": 1,
    "disabled": 1,
    "endedTurn": false
  },
  {
    "id": 30,
    "type": "shape",
    "name": "Безжизненный_мир",
    "shape": "custom",
    "color": "#d3d3d3",
    "x": 179.35,
    "y": 63.87,
    "width": 50,
    "height": 50,
    "src": "pokras-spc/images/buildings/Безжизненный_мир.png",
    "curr_hp": 1,
    "disabled": 1,
    "endedTurn": false
  },
  {
    "id": 31,
    "type": "shape",
    "name": "Водный_мир",
    "shape": "custom",
    "color": "#d3d3d3",
    "x": 355.22,
    "y": 783.84,
    "width": 50,
    "height": 50,
    "src": "pokras-spc/images/buildings/Водный_мир.png",
    "curr_hp": 1,
    "disabled": 1,
    "endedTurn": false
  },
  {
    "id": 32,
    "type": "shape",
    "name": "Водный_мир",
    "shape": "custom",
    "color": "#d3d3d3",
    "x": 566.81,
    "y": 985.36,
    "width": 50,
    "height": 50,
    "src": "pokras-spc/images/buildings/Водный_мир.png",
    "curr_hp": 1,
    "disabled": 1,
    "endedTurn": false
  },
  {
    "id": 33,
    "type": "shape",
    "name": "Умеренный_мир",
    "shape": "custom",
    "color": "#0000ff",
    "x": 891.08,
    "y": 278.21,
    "width": 50,
    "height": 50,
    "src": "pokras-spc/images/buildings/Умеренный_мир.png",
    "curr_hp": 1,
    "endedTurn": false
  },
  {
    "id": 34,
    "type": "shape",
    "name": "Водный_мир",
    "shape": "custom",
    "color": "#d3d3d3",
    "x": 1109.08,
    "y": 279.12,
    "width": 50,
    "height": 50,
    "src": "pokras-spc/images/buildings/Водный_мир.png",
    "curr_hp": 1,
    "disabled": 1,
    "endedTurn": false
  },
  {
    "id": 35,
    "type": "shape",
    "name": "Холодный_мир",
    "shape": "custom",
    "color": "#0000ff",
    "x": 1108.99,
    "y": 481.5,
    "width": 50,
    "height": 50,
    "src": "pokras-spc/images/buildings/Холодный_мир.png",
    "curr_hp": 1,
    "endedTurn": false
  },
  {
    "id": 36,
    "type": "shape",
    "name": "Газовый_гигант",
    "shape": "custom",
    "color": "#d3d3d3",
    "x": 1325.16,
    "y": 2313.85,
    "width": 50,
    "height": 50,
    "src": "pokras-spc/images/buildings/Газовый_гигант.png",
    "curr_hp": 1,
    "disabled": 1,
    "endedTurn": false
  },
  {
    "id": 37,
    "type": "shape",
    "name": "Холодный_мир",
    "shape": "custom",
    "color": "#d3d3d3",
    "x": 1654.32,
    "y": 2007.8,
    "width": 50,
    "height": 50,
    "src": "pokras-spc/images/buildings/Холодный_мир.png",
    "curr_hp": 1,
    "disabled": 1,
    "endedTurn": false
  },
  {
    "id": 38,
    "type": "shape",
    "name": "Безжизненный_мир",
    "shape": "custom",
    "color": "#008000",
    "x": 1759.01,
    "y": 1497.63,
    "width": 50,
    "height": 50,
    "src": "pokras-spc/images/buildings/Безжизненный_мир.png",
    "curr_hp": 1,
    "endedTurn": false
  },
  {
    "id": 39,
    "type": "shape",
    "name": "Газовый_гигант",
    "shape": "custom",
    "color": "#d3d3d3",
    "x": 1971.07,
    "y": 1501.25,
    "width": 50,
    "height": 50,
    "src": "pokras-spc/images/buildings/Газовый_гигант.png",
    "curr_hp": 1,
    "disabled": 1,
    "endedTurn": false
  },
  {
    "id": 40,
    "type": "shape",
    "name": "Холодный_мир",
    "shape": "custom",
    "color": "#d3d3d3",
    "x": 1756.13,
    "y": 1706.13,
    "width": 50,
    "height": 50,
    "src": "pokras-spc/images/buildings/Холодный_мир.png",
    "curr_hp": 1,
    "disabled": 1,
    "endedTurn": false
  },
  {
    "id": 41,
    "type": "shape",
    "name": "Добывающая_станция",
    "shape": "custom",
    "color": "#0000ff",
    "x": 892.02,
    "y": 226.21,
    "width": 40,
    "height": 40,
    "curr_hp": 1,
    "endedTurn": false
  },
  {
    "id": 42,
    "type": "shape",
    "name": "Газовый_гигант",
    "shape": "custom",
    "color": "#0000ff",
    "x": 674.55,
    "y": 1194.13,
    "width": 50,
    "height": 50,
    "src": "pokras-spc/images/buildings/Газовый_гигант.png",
    "curr_hp": 1,
    "disabled": 1,
    "endedTurn": false
  },
  {
    "id": 43,
    "type": "shape",
    "name": "Газовый_гигант",
    "shape": "custom",
    "color": "#0000ff",
    "x": 892.89,
    "y": 1192.23,
    "width": 50,
    "height": 50,
    "src": "pokras-spc/images/buildings/Газовый_гигант.png",
    "curr_hp": 1,
    "disabled": 1,
    "endedTurn": false
  },
  {
    "id": 44,
    "type": "shape",
    "name": "Горячий_мир",
    "shape": "custom",
    "color": "#0000ff",
    "x": 890.04,
    "y": 1398.22,
    "width": 50,
    "height": 50,
    "src": "pokras-spc/images/buildings/Горячий_мир.png",
    "curr_hp": 1,
    "endedTurn": false
  },
  {
    "id": 45,
    "type": "shape",
    "name": "Умеренный_мир",
    "shape": "custom",
    "color": "#0000ff",
    "x": 677.4,
    "y": 1396.32,
    "width": 50,
    "height": 50,
    "src": "pokras-spc/images/buildings/Умеренный_мир.png",
    "curr_hp": 1,
    "disabled": 1,
    "endedTurn": false
  },
  {
    "id": 46,
    "type": "shape",
    "name": "Добывающая_станция",
    "shape": "custom",
    "color": "#008000",
    "x": 1759.72,
    "y": 1454.6,
    "width": 40,
    "height": 40,
    "curr_hp": 1,
    "endedTurn": false
  },
  {
    "id": 47,
    "type": "shape",
    "name": "Горячий_мир",
    "shape": "custom",
    "color": "#008000",
    "x": 1862.7,
    "y": 1197.24,
    "width": 50,
    "height": 50,
    "src": "pokras-spc/images/buildings/Горячий_мир.png",
    "curr_hp": 1,
    "endedTurn": false
  },
  {
    "id": 48,
    "type": "shape",
    "name": "Холодный_мир",
    "shape": "custom",
    "color": "#008000",
    "x": 1647.62,
    "y": 1396.5,
    "width": 50,
    "height": 50,
    "src": "pokras-spc/images/buildings/Холодный_мир.png",
    "curr_hp": 1,
    "disabled": 1,
    "endedTurn": false
  },
  {
    "id": 49,
    "type": "shape",
    "name": "Безжизненный_мир",
    "shape": "custom",
    "color": "#008000",
    "x": 1003.07,
    "y": 2313.49,
    "width": 50,
    "height": 50,
    "src": "pokras-spc/images/buildings/Безжизненный_мир.png",
    "curr_hp": 1,
    "endedTurn": false
  },
  {
    "id": 51,
    "type": "shape",
    "name": "Умеренный_мир",
    "shape": "custom",
    "color": "#0000ff",
    "x": 1001.02,
    "y": 988.45,
    "width": 50,
    "height": 50,
    "src": "pokras-spc/images/buildings/Умеренный_мир.png",
    "curr_hp": 1,
    "disabled": 1,
    "endedTurn": false
  },
  {
    "id": 52,
    "type": "shape",
    "name": "Умеренный_мир",
    "shape": "custom",
    "color": "#0000ff",
    "x": 1210.59,
    "y": 991.82,
    "width": 50,
    "height": 50,
    "src": "pokras-spc/images/buildings/Умеренный_мир.png",
    "curr_hp": 1,
    "disabled": 1,
    "endedTurn": false
  },
  {
    "id": 53,
    "type": "shape",
    "name": "Безжизненный_мир",
    "shape": "custom",
    "color": "#0000ff",
    "x": 1215.07,
    "y": 1192.42,
    "width": 50,
    "height": 50,
    "src": "pokras-spc/images/buildings/Безжизненный_мир.png",
    "curr_hp": 1,
    "endedTurn": false
  },
  {
    "id": 54,
    "type": "shape",
    "name": "Водный_мир",
    "shape": "custom",
    "color": "#0000ff",
    "x": 997.66,
    "y": 1190.18,
    "width": 50,
    "height": 50,
    "src": "pokras-spc/images/buildings/Водный_мир.png",
    "curr_hp": 1,
    "disabled": 1,
    "endedTurn": false
  },
  {
    "id": 55,
    "type": "shape",
    "name": "Холодный_мир",
    "shape": "custom",
    "color": "#0000ff",
    "x": 1216.19,
    "y": 582.77,
    "width": 50,
    "height": 50,
    "src": "pokras-spc/images/buildings/Холодный_мир.png",
    "curr_hp": 1,
    "disabled": 1,
    "endedTurn": false
  },
  {
    "id": 56,
    "type": "shape",
    "name": "Газовый_гигант",
    "shape": "custom",
    "color": "#0000ff",
    "x": 999.9,
    "y": 790.09,
    "width": 50,
    "height": 50,
    "src": "pokras-spc/images/buildings/Газовый_гигант.png",
    "curr_hp": 1,
    "disabled": 1,
    "endedTurn": false
  },
  {
    "id": 58,
    "type": "shape",
    "name": "Молодая_колония",
    "shape": "custom",
    "color": "#0000ff",
    "x": 1113.78,
    "y": 486.59,
    "width": 40,
    "height": 40,
    "curr_hp": 1,
    "endedTurn": false
  },
  {
    "id": 59,
    "type": "shape",
    "name": "Молодая_колония",
    "shape": "custom",
    "color": "#008000",
    "x": 1867.98,
    "y": 1199.75,
    "width": 40,
    "height": 40,
    "curr_hp": 1,
    "endedTurn": false
  },
  {
    "id": 60,
    "type": "shape",
    "name": "Горячий_мир",
    "shape": "custom",
    "color": "#008000",
    "x": 674.85,
    "y": 2106.74,
    "width": 50,
    "height": 50,
    "src": "pokras-spc/images/buildings/Горячий_мир.png",
    "curr_hp": 1,
    "disabled": 1,
    "endedTurn": false
  },
  {
    "id": 61,
    "type": "shape",
    "name": "Горячий_мир",
    "shape": "custom",
    "color": "#008000",
    "x": 892.15,
    "y": 2111.91,
    "width": 50,
    "height": 50,
    "src": "pokras-spc/images/buildings/Горячий_мир.png",
    "curr_hp": 1,
    "disabled": 1,
    "endedTurn": false
  },
  {
    "id": 62,
    "type": "shape",
    "name": "Холодный_мир",
    "shape": "custom",
    "color": "#008000",
    "x": 891.12,
    "y": 2316.8,
    "width": 50,
    "height": 50,
    "src": "pokras-spc/images/buildings/Холодный_мир.png",
    "curr_hp": 1,
    "disabled": 1,
    "endedTurn": false
  },
  {
    "id": 63,
    "type": "shape",
    "name": "Водный_мир",
    "shape": "custom",
    "color": "#008000",
    "x": 671.74,
    "y": 2314.73,
    "width": 50,
    "height": 50,
    "src": "pokras-spc/images/buildings/Водный_мир.png",
    "curr_hp": 1,
    "disabled": 1,
    "endedTurn": false
  },
  {
    "id": 64,
    "type": "shape",
    "name": "Добывающая_станция",
    "shape": "custom",
    "color": "#008000",
    "x": 1332.41,
    "y": 1756.99,
    "width": 40,
    "height": 40,
    "curr_hp": 1,
    "endedTurn": false
  },
  {
    "id": 65,
    "type": "shape",
    "name": "Умеренный_мир",
    "shape": "custom",
    "color": "#008000",
    "x": 352.63,
    "y": 1903.7,
    "width": 50,
    "height": 50,
    "src": "pokras-spc/images/buildings/Умеренный_мир.png",
    "curr_hp": 1,
    "disabled": 1,
    "endedTurn": false
  },
  {
    "id": 66,
    "type": "shape",
    "name": "Газовый_гигант",
    "shape": "custom",
    "color": "#008000",
    "x": 566.34,
    "y": 1913.05,
    "width": 50,
    "height": 50,
    "src": "pokras-spc/images/buildings/Газовый_гигант.png",
    "curr_hp": 1,
    "disabled": 1,
    "endedTurn": false
  },
  {
    "id": 67,
    "type": "shape",
    "name": "Водный_мир",
    "shape": "custom",
    "color": "#008000",
    "x": 352.63,
    "y": 2110.41,
    "width": 50,
    "height": 50,
    "src": "pokras-spc/images/buildings/Водный_мир.png",
    "curr_hp": 1,
    "disabled": 1,
    "endedTurn": false
  },
  {
    "id": 68,
    "type": "shape",
    "name": "Добывающая_станция",
    "shape": "custom",
    "color": "#0000ff",
    "x": 1220.21,
    "y": 1141.25,
    "width": 40,
    "height": 40,
    "curr_hp": 1,
    "endedTurn": false
  },
  {
    "id": 69,
    "type": "shape",
    "name": "Строитель",
    "shape": "custom",
    "color": "#0000ff",
    "x": 142.88,
    "y": 144.48,
    "width": 40,
    "height": 40,
    "curr_hp": 1,
    "endedTurn": false
  },
  {
    "id": 70,
    "type": "shape",
    "name": "Умеренный_мир",
    "shape": "custom",
    "color": "#0000ff",
    "x": 1540.43,
    "y": 576.59,
    "width": 50,
    "height": 50,
    "src": "pokras-spc/images/buildings/Умеренный_мир.png",
    "curr_hp": 1,
    "disabled": 1,
    "endedTurn": false
  },
  {
    "id": 71,
    "type": "shape",
    "name": "Газовый_гигант",
    "shape": "custom",
    "color": "#0000ff",
    "x": 1751.89,
    "y": 582.16,
    "width": 50,
    "height": 50,
    "src": "pokras-spc/images/buildings/Газовый_гигант.png",
    "curr_hp": 1,
    "disabled": 1,
    "endedTurn": false
  },
  {
    "id": 72,
    "type": "shape",
    "name": "Водный_мир",
    "shape": "custom",
    "color": "#0000ff",
    "x": 1751.89,
    "y": 786.19,
    "width": 50,
    "height": 50,
    "src": "pokras-spc/images/buildings/Водный_мир.png",
    "curr_hp": 1,
    "disabled": 1,
    "endedTurn": false
  },
  {
    "id": 73,
    "type": "shape",
    "name": "Добывающая_станция",
    "shape": "custom",
    "color": "#008000",
    "x": 1547.25,
    "y": 1956.44,
    "width": 40,
    "height": 40,
    "curr_hp": 1,
    "endedTurn": false
  },
  {
    "id": 74,
    "type": "shape",
    "name": "Безжизненный_мир",
    "shape": "custom",
    "color": "#008000",
    "x": 134.44,
    "y": 2417.71,
    "width": 50,
    "height": 50,
    "src": "pokras-spc/images/buildings/Безжизненный_мир.png",
    "curr_hp": 1,
    "disabled": 1,
    "endedTurn": false
  },
  {
    "id": 75,
    "type": "shape",
    "name": "Газовый_гигант",
    "shape": "custom",
    "color": "#008000",
    "x": 240.79,
    "y": 2316.42,
    "width": 50,
    "height": 50,
    "src": "pokras-spc/images/buildings/Газовый_гигант.png",
    "curr_hp": 1,
    "disabled": 1,
    "endedTurn": false
  },
  {
    "id": 76,
    "type": "shape",
    "name": "Холодный_мир",
    "shape": "custom",
    "color": "#008000",
    "x": 349.67,
    "y": 2416.44,
    "width": 50,
    "height": 50,
    "src": "pokras-spc/images/buildings/Холодный_мир.png",
    "curr_hp": 1,
    "disabled": 1,
    "endedTurn": false
  },
  {
    "id": 77,
    "type": "shape",
    "name": "Газовый_гигант",
    "shape": "custom",
    "color": "#0000ff",
    "x": 1674.47,
    "y": 455.51,
    "width": 50,
    "height": 50,
    "src": "pokras-spc/images/buildings/Газовый_гигант.png",
    "curr_hp": 1,
    "disabled": 1,
    "endedTurn": false
  },
  {
    "id": 78,
    "type": "shape",
    "name": "Холодный_мир",
    "shape": "custom",
    "color": "#0000ff",
    "x": 1431.05,
    "y": 270.33,
    "width": 50,
    "height": 50,
    "src": "pokras-spc/images/buildings/Холодный_мир.png",
    "curr_hp": 1,
    "disabled": 1,
    "endedTurn": false
  },
  {
    "id": 79,
    "type": "shape",
    "name": "Строитель",
    "shape": "custom",
    "color": "#008000",
    "x": 1778.37,
    "y": 1887.15,
    "width": 40,
    "height": 40,
    "curr_hp": 1,
    "endedTurn": false
  },
  {
    "id": 80,
    "type": "shape",
    "name": "Добывающая_станция",
    "shape": "custom",
    "color": "#0000ff",
    "x": 357.6686789365056,
    "y": 124.89607452850186,
    "width": 40,
    "height": 40,
    "curr_hp": 1,
    "endedTurn": false
  },
  {
    "id": 81,
    "type": "shape",
    "name": "Горячий_мир",
    "shape": "custom",
    "color": "#0000ff",
    "x": 1757.96,
    "y": 280.18,
    "width": 50,
    "height": 50,
    "src": "pokras-spc/images/buildings/Горячий_мир.png",
    "curr_hp": 1,
    "disabled": 1,
    "endedTurn": false
  },
  {
    "id": 82,
    "type": "shape",
    "name": "Водный_мир",
    "shape": "custom",
    "color": "#0000ff",
    "x": 1972.42,
    "y": 281.48,
    "width": 50,
    "height": 50,
    "src": "pokras-spc/images/buildings/Водный_мир.png",
    "curr_hp": 1,
    "disabled": 1,
    "endedTurn": false
  },
  {
    "id": 83,
    "type": "shape",
    "name": "Безжизненный_мир",
    "shape": "custom",
    "color": "#0000ff",
    "x": 1967.22,
    "y": 481.65,
    "width": 50,
    "height": 50,
    "src": "pokras-spc/images/buildings/Безжизненный_мир.png",
    "curr_hp": 1,
    "disabled": 1,
    "endedTurn": false
  },
  {
    "id": 84,
    "type": "shape",
    "name": "Добывающая_станция",
    "shape": "custom",
    "color": "#008000",
    "x": 1549.93,
    "y": 1752.7,
    "width": 40,
    "height": 40,
    "curr_hp": 1,
    "endedTurn": false
  },
  {
    "id": 85,
    "type": "shape",
    "name": "Горячий_мир",
    "shape": "custom",
    "color": "#008000",
    "x": 244.65,
    "y": 1805.15,
    "width": 50,
    "height": 50,
    "src": "pokras-spc/images/buildings/Горячий_мир.png",
    "curr_hp": 1,
    "disabled": 1,
    "endedTurn": false
  },
  {
    "id": 86,
    "type": "shape",
    "name": "Газовый_гигант",
    "shape": "custom",
    "color": "#008000",
    "x": 24.56,
    "y": 2010.81,
    "width": 50,
    "height": 50,
    "src": "pokras-spc/images/buildings/Газовый_гигант.png",
    "curr_hp": 1,
    "disabled": 1,
    "endedTurn": false
  },
  {
    "id": 87,
    "type": "shape",
    "name": "Добывающая_станция",
    "shape": "custom",
    "color": "#0000ff",
    "x": 896.37,
    "y": 1351.34,
    "width": 40,
    "height": 40,
    "curr_hp": 1,
    "endedTurn": false
  },
  {
    "id": 88,
    "type": "shape",
    "name": "Горячий_мир",
    "shape": "custom",
    "color": "#0000ff",
    "x": 1536.42,
    "y": 66.58,
    "width": 50,
    "height": 50,
    "src": "pokras-spc/images/buildings/Горячий_мир.png",
    "curr_hp": 1,
    "disabled": 1,
    "endedTurn": false
  },
  {
    "id": 89,
    "type": "shape",
    "name": "Умеренный_мир",
    "shape": "custom",
    "color": "#0000ff",
    "x": 1760.68,
    "y": 67.44,
    "width": 50,
    "height": 50,
    "src": "pokras-spc/images/buildings/Умеренный_мир.png",
    "curr_hp": 1,
    "disabled": 1,
    "endedTurn": false
  },
  {
    "id": 90,
    "type": "shape",
    "name": "Безжизненный_мир",
    "shape": "custom",
    "color": "#0000ff",
    "x": 1649.42,
    "y": 172.67,
    "width": 50,
    "height": 50,
    "src": "pokras-spc/images/buildings/Безжизненный_мир.png",
    "curr_hp": 1,
    "disabled": 1,
    "endedTurn": false
  },
  {
    "id": 91,
    "type": "shape",
    "name": "Добывающая_станция",
    "shape": "custom",
    "color": "#008000",
    "x": 1008.28,
    "y": 2267.19,
    "width": 40,
    "height": 40,
    "curr_hp": 1,
    "endedTurn": false
  }
]