CURRENT_TURN=3;
OTHER_SAVE_DATA={
  "scale": 0.9151748705770909,
  "canvasOffsetX": -905.8637646057334,
  "canvasOffsetY": -1373.1307190047635,
  "shapeColor": "#008000"
};
USER_RESOURCES={
  "Нейтралы": {},
  "Враги": {
    "Еда": 0,
    "Металл": 0
  },
  "Десант": {
    "Еда": 0,
    "Металл": 23,
    "Кремний": 12,
    "Уран": 20,
    "Наука": 4
  },
  "Варвары": {},
  "Колорады": {
    "Металл": 15,
    "Кремний": 24,
    "Уран": 15,
    "Наука": 4
  }
};
USER_TECH_LVLS={
  "Десант": {
    "Энергетика": 0,
    "Двигатели": 0,
    "Социология": 0,
    "Биология": 0,
    "Оружие": 0,
    "Броня": 0,
    "Энерго-оружие": 0,
    "Щиты": 0
  },
  "Нейтралы": {},
  "Варвары": {},
  "Колорады": {
    "Энергетика": 0,
    "Двигатели": 0,
    "Социология": 0,
    "Биология": 0,
    "Оружие": 0,
    "Броня": 0,
    "Энерго-оружие": 0,
    "Щиты": 0
  }
};
OWNER_MAP={"16":[15],"23":[1]};
DEFAULT_DATA=[
  {
    "id": 1,
    "type": "shape",
    "name": "Холодный_мир",
    "shape": "custom",
    "color": "#0000ff",
    "x": 349.41,
    "y": 369.82,
    "width": 60,
    "height": 60,
    "src": "pokras-spc/images/buildings/Холодный_мир.png",
    "curr_hp": 1,
    "endedTurn": false,
    "lvl": 1
  },
  {
    "id": 6,
    "type": "shape",
    "name": "Столица",
    "shape": "custom",
    "color": "#0000ff",
    "x": 484.39,
    "y": 257.48,
    "width": 50,
    "height": 50,
    "curr_hp": 1,
    "endedTurn": false
  },
  {
    "id": 9,
    "type": "shape",
    "name": "Безжизненный_мир",
    "shape": "custom",
    "color": "#008000",
    "x": 1322.57,
    "y": 1801.97,
    "width": 50,
    "height": 50,
    "src": "pokras-spc/images/buildings/Безжизненный_мир.png",
    "curr_hp": 1,
    "disabled": 1,
    "endedTurn": false
  },
  {
    "id": 11,
    "type": "shape",
    "name": "Газовый_гигант",
    "shape": "custom",
    "color": "#008000",
    "x": 1541.39,
    "y": 1804.47,
    "width": 50,
    "height": 50,
    "src": "pokras-spc/images/buildings/Газовый_гигант.png",
    "curr_hp": 1,
    "disabled": 1,
    "endedTurn": false
  },
  {
    "id": 13,
    "type": "shape",
    "name": "Умеренный_мир",
    "shape": "custom",
    "color": "#008000",
    "x": 1541.39,
    "y": 2007.04,
    "width": 50,
    "height": 50,
    "src": "pokras-spc/images/buildings/Умеренный_мир.png",
    "curr_hp": 1,
    "disabled": 1,
    "endedTurn": false
  },
  {
    "id": 14,
    "type": "shape",
    "name": "Столица",
    "shape": "custom",
    "color": "#008000",
    "x": 1455.85,
    "y": 1890.14,
    "width": 50,
    "height": 50,
    "curr_hp": 1,
    "endedTurn": false
  },
  {
    "id": 15,
    "type": "shape",
    "name": "Горячий_мир",
    "shape": "custom",
    "color": "#008000",
    "x": 1328.54,
    "y": 2010.24,
    "width": 50,
    "height": 50,
    "src": "pokras-spc/images/buildings/Горячий_мир.png",
    "curr_hp": 1,
    "endedTurn": false
  },
  {
    "id": 16,
    "type": "shape",
    "name": "Развитая_колония",
    "shape": "custom",
    "color": "#008000",
    "x": 1335.19,
    "y": 2006.53,
    "width": 40,
    "height": 40,
    "curr_hp": 1,
    "endedTurn": false
  },
  {
    "id": 17,
    "type": "shape",
    "name": "Верфь",
    "shape": "custom",
    "color": "#008000",
    "x": 1329.91,
    "y": 1961.23,
    "width": 40,
    "height": 40,
    "curr_hp": 1,
    "endedTurn": false
  },
  {
    "id": 18,
    "type": "shape",
    "name": "Фрегат",
    "shape": "custom",
    "color": "#008000",
    "x": 1189.74,
    "y": 2174.25,
    "width": 40,
    "height": 40,
    "src": "pokras-spc/images/units/Фрегат.png",
    "curr_hp": 1,
    "endedTurn": false
  },
  {
    "id": 19,
    "type": "shape",
    "name": "Колонизатор",
    "shape": "custom",
    "color": "#008000",
    "x": 1858.56,
    "y": 1258.53,
    "width": 40,
    "height": 40,
    "curr_hp": 1,
    "endedTurn": false
  },
  {
    "id": 20,
    "type": "shape",
    "name": "Строитель",
    "shape": "custom",
    "color": "#008000",
    "x": 1813.23,
    "y": 1603.05,
    "width": 40,
    "height": 40,
    "curr_hp": 1,
    "endedTurn": false
  },
  {
    "id": 21,
    "type": "shape",
    "name": "Горячий_мир",
    "shape": "custom",
    "color": "#0000ff",
    "x": 351.99,
    "y": 173.48,
    "width": 50,
    "height": 50,
    "src": "pokras-spc/images/buildings/Горячий_мир.png",
    "curr_hp": 1,
    "disabled": 1,
    "endedTurn": false
  },
  {
    "id": 22,
    "type": "shape",
    "name": "Газовый_гигант",
    "shape": "custom",
    "color": "#0000ff",
    "x": 568.58,
    "y": 174.91,
    "width": 50,
    "height": 50,
    "src": "pokras-spc/images/buildings/Газовый_гигант.png",
    "curr_hp": 1,
    "disabled": 1,
    "endedTurn": false
  },
  {
    "id": 23,
    "type": "shape",
    "name": "Развитая_колония",
    "shape": "custom",
    "color": "#0000ff",
    "x": 355.93,
    "y": 380.75,
    "width": 40,
    "height": 40,
    "curr_hp": 1,
    "endedTurn": false
  },
  {
    "id": 24,
    "type": "shape",
    "name": "Верфь",
    "shape": "custom",
    "color": "#0000ff",
    "x": 350.35,
    "y": 327.73,
    "width": 40,
    "height": 40,
    "curr_hp": 1,
    "endedTurn": false
  },
  {
    "id": 25,
    "type": "shape",
    "name": "Колонизатор",
    "shape": "custom",
    "color": "#0000ff",
    "x": 415.63,
    "y": 278.64,
    "width": 40,
    "height": 40,
    "curr_hp": 1,
    "endedTurn": false
  },
  {
    "id": 26,
    "type": "shape",
    "name": "Строитель",
    "shape": "custom",
    "color": "#0000ff",
    "x": 1029.66,
    "y": 350.95,
    "width": 40,
    "height": 40,
    "curr_hp": 1,
    "endedTurn": false
  },
  {
    "id": 27,
    "type": "shape",
    "name": "Фрегат",
    "shape": "custom",
    "color": "#0000ff",
    "x": 826.12,
    "y": 1239.3,
    "width": 40,
    "height": 40,
    "src": "pokras-spc/images/units/Фрегат.png",
    "curr_hp": 1,
    "endedTurn": false
  },
  {
    "id": 28,
    "type": "shape",
    "name": "Горячий_мир",
    "shape": "custom",
    "color": "#d3d3d3",
    "x": 24.55,
    "y": 171.95,
    "width": 50,
    "height": 50,
    "src": "pokras-spc/images/buildings/Горячий_мир.png",
    "curr_hp": 1,
    "disabled": 1,
    "endedTurn": false
  },
  {
    "id": 30,
    "type": "shape",
    "name": "Безжизненный_мир",
    "shape": "custom",
    "color": "#d3d3d3",
    "x": 179.35,
    "y": 63.87,
    "width": 50,
    "height": 50,
    "src": "pokras-spc/images/buildings/Безжизненный_мир.png",
    "curr_hp": 1,
    "disabled": 1,
    "endedTurn": false
  },
  {
    "id": 31,
    "type": "shape",
    "name": "Водный_мир",
    "shape": "custom",
    "color": "#d3d3d3",
    "x": 355.22,
    "y": 783.84,
    "width": 50,
    "height": 50,
    "src": "pokras-spc/images/buildings/Водный_мир.png",
    "curr_hp": 1,
    "disabled": 1,
    "endedTurn": false
  },
  {
    "id": 32,
    "type": "shape",
    "name": "Водный_мир",
    "shape": "custom",
    "color": "#d3d3d3",
    "x": 566.81,
    "y": 985.36,
    "width": 50,
    "height": 50,
    "src": "pokras-spc/images/buildings/Водный_мир.png",
    "curr_hp": 1,
    "disabled": 1,
    "endedTurn": false
  },
  {
    "id": 33,
    "type": "shape",
    "name": "Умеренный_мир",
    "shape": "custom",
    "color": "#0000ff",
    "x": 891.08,
    "y": 278.21,
    "width": 50,
    "height": 50,
    "src": "pokras-spc/images/buildings/Умеренный_мир.png",
    "curr_hp": 1,
    "endedTurn": false
  },
  {
    "id": 34,
    "type": "shape",
    "name": "Водный_мир",
    "shape": "custom",
    "color": "#d3d3d3",
    "x": 1109.08,
    "y": 279.12,
    "width": 50,
    "height": 50,
    "src": "pokras-spc/images/buildings/Водный_мир.png",
    "curr_hp": 1,
    "disabled": 1,
    "endedTurn": false
  },
  {
    "id": 35,
    "type": "shape",
    "name": "Холодный_мир",
    "shape": "custom",
    "color": "#d3d3d3",
    "x": 1107.25,
    "y": 480.64,
    "width": 50,
    "height": 50,
    "src": "pokras-spc/images/buildings/Холодный_мир.png",
    "curr_hp": 1,
    "disabled": 1,
    "endedTurn": false
  },
  {
    "id": 36,
    "type": "shape",
    "name": "Газовый_гигант",
    "shape": "custom",
    "color": "#d3d3d3",
    "x": 1325.16,
    "y": 2313.85,
    "width": 50,
    "height": 50,
    "src": "pokras-spc/images/buildings/Газовый_гигант.png",
    "curr_hp": 1,
    "disabled": 1,
    "endedTurn": false
  },
  {
    "id": 37,
    "type": "shape",
    "name": "Холодный_мир",
    "shape": "custom",
    "color": "#d3d3d3",
    "x": 1654.32,
    "y": 2007.8,
    "width": 50,
    "height": 50,
    "src": "pokras-spc/images/buildings/Холодный_мир.png",
    "curr_hp": 1,
    "disabled": 1,
    "endedTurn": false
  },
  {
    "id": 38,
    "type": "shape",
    "name": "Безжизненный_мир",
    "shape": "custom",
    "color": "#008000",
    "x": 1756.13,
    "y": 1506.28,
    "width": 50,
    "height": 50,
    "src": "pokras-spc/images/buildings/Безжизненный_мир.png",
    "curr_hp": 1,
    "endedTurn": false
  },
  {
    "id": 39,
    "type": "shape",
    "name": "Газовый_гигант",
    "shape": "custom",
    "color": "#d3d3d3",
    "x": 1971.07,
    "y": 1501.25,
    "width": 50,
    "height": 50,
    "src": "pokras-spc/images/buildings/Газовый_гигант.png",
    "curr_hp": 1,
    "disabled": 1,
    "endedTurn": false
  },
  {
    "id": 40,
    "type": "shape",
    "name": "Холодный_мир",
    "shape": "custom",
    "color": "#d3d3d3",
    "x": 1756.13,
    "y": 1706.13,
    "width": 50,
    "height": 50,
    "src": "pokras-spc/images/buildings/Холодный_мир.png",
    "curr_hp": 1,
    "disabled": 1,
    "endedTurn": false
  },
  {
    "id": 41,
    "type": "shape",
    "name": "Добывающая_станция",
    "shape": "custom",
    "color": "#0000ff",
    "x": 893.14,
    "y": 231.82,
    "width": 40,
    "height": 40,
    "curr_hp": 1,
    "endedTurn": false
  },
  {
    "id": 42,
    "type": "shape",
    "name": "Газовый_гигант",
    "shape": "custom",
    "color": "#0000ff",
    "x": 674.55,
    "y": 1194.13,
    "width": 50,
    "height": 50,
    "src": "pokras-spc/images/buildings/Газовый_гигант.png",
    "curr_hp": 1,
    "disabled": 1,
    "endedTurn": false
  },
  {
    "id": 43,
    "type": "shape",
    "name": "Газовый_гигант",
    "shape": "custom",
    "color": "#0000ff",
    "x": 892.89,
    "y": 1192.23,
    "width": 50,
    "height": 50,
    "src": "pokras-spc/images/buildings/Газовый_гигант.png",
    "curr_hp": 1,
    "disabled": 1,
    "endedTurn": false
  },
  {
    "id": 44,
    "type": "shape",
    "name": "Горячий_мир",
    "shape": "custom",
    "color": "#0000ff",
    "x": 890.04,
    "y": 1398.22,
    "width": 50,
    "height": 50,
    "src": "pokras-spc/images/buildings/Горячий_мир.png",
    "curr_hp": 1,
    "disabled": 1,
    "endedTurn": false
  },
  {
    "id": 45,
    "type": "shape",
    "name": "Умеренный_мир",
    "shape": "custom",
    "color": "#0000ff",
    "x": 677.4,
    "y": 1396.32,
    "width": 50,
    "height": 50,
    "src": "pokras-spc/images/buildings/Умеренный_мир.png",
    "curr_hp": 1,
    "disabled": 1,
    "endedTurn": false
  },
  {
    "id": 46,
    "type": "shape",
    "name": "Добывающая_станция",
    "shape": "custom",
    "color": "#008000",
    "x": 1759.72,
    "y": 1454.6,
    "width": 40,
    "height": 40,
    "curr_hp": 1,
    "endedTurn": false
  },
  {
    "id": 47,
    "type": "shape",
    "name": "Горячий_мир",
    "shape": "custom",
    "color": "#008000",
    "x": 1862.7,
    "y": 1195.59,
    "width": 50,
    "height": 50,
    "src": "pokras-spc/images/buildings/Горячий_мир.png",
    "curr_hp": 1,
    "disabled": 1,
    "endedTurn": false
  },
  {
    "id": 48,
    "type": "shape",
    "name": "Холодный_мир",
    "shape": "custom",
    "color": "#008000",
    "x": 1647.62,
    "y": 1396.5,
    "width": 50,
    "height": 50,
    "src": "pokras-spc/images/buildings/Холодный_мир.png",
    "curr_hp": 1,
    "disabled": 1,
    "endedTurn": false
  },
  {
    "id": 49,
    "type": "shape",
    "name": "Безжизненный_мир",
    "shape": "custom",
    "color": "#008000",
    "x": 1003.07,
    "y": 2313.49,
    "width": 50,
    "height": 50,
    "src": "pokras-spc/images/buildings/Безжизненный_мир.png",
    "curr_hp": 1,
    "disabled": 1,
    "endedTurn": false
  }
]