CURRENT_TURN=3;
OTHER_SAVE_DATA={
  "scale": 1.0665570610380943,
  "canvasOffsetX": 49.26261382099358,
  "canvasOffsetY": -1118.989274360217,
  "shapeColor": "#d3d3d3"
};
USER_RESOURCES={
  "Нейтралы": {},
  "Варвары": {},
  "Мамонты": {
    "Минералы": 0
  },
  "Нео": {
    "Минералы": 2
  },
  "Йод": {
    "Минералы": 6
  },
  "Онид": {
    "Минералы": 7
  },
  "Чайки": {
    "Минералы": 13
  }
};
OWNER_MAP={"20":[23]};
DEFAULT_DATA=[
  {
    "id": 1,
    "type": "shape",
    "name": "Колония",
    "shape": "custom",
    "color": "#006699",
    "x": 679.3,
    "y": 1116.2,
    "width": 40,
    "height": 40,
    "src": null,
    "curr_hp": 1,
    "disabled": false,
    "endedTurn": false
  },
  {
    "id": 2,
    "type": "shape",
    "name": "Пешка",
    "shape": "custom",
    "color": "#006699",
    "x": 536.03,
    "y": 1183.8,
    "width": 40,
    "height": 40,
    "src": "",
    "curr_hp": 1,
    "disabled": false,
    "endedTurn": true
  },
  {
    "id": 3,
    "type": "shape",
    "name": "Король",
    "shape": "custom",
    "color": "#006699",
    "x": 898.56,
    "y": 1187.11,
    "width": 40,
    "height": 40,
    "src": null,
    "curr_hp": 1,
    "disabled": false,
    "endedTurn": true
  },
  {
    "id": 4,
    "type": "shape",
    "name": "Колония",
    "shape": "custom",
    "color": "#ff69b4",
    "x": 393.33,
    "y": 1653.12,
    "width": 40,
    "height": 40,
    "src": null,
    "curr_hp": 1,
    "disabled": false,
    "endedTurn": false,
    "title": "Нэко-ворлд"
  },
  {
    "id": 5,
    "type": "shape",
    "name": "Пешка",
    "shape": "custom",
    "color": "#ff69b4",
    "x": 178.98,
    "y": 1737.97,
    "width": 40,
    "height": 40,
    "src": null,
    "curr_hp": 1,
    "disabled": false,
    "endedTurn": true
  },
  {
    "id": 6,
    "type": "shape",
    "name": "Король",
    "shape": "custom",
    "color": "#ff69b4",
    "x": 607.13,
    "y": 1531.41,
    "width": 40,
    "height": 40,
    "src": null,
    "curr_hp": 1,
    "disabled": false,
    "endedTurn": true
  },
  {
    "id": 8,
    "type": "shape",
    "name": "Пешка",
    "shape": "custom",
    "color": "#ff69b4",
    "x": 462.06,
    "y": 1793.31,
    "width": 40,
    "height": 40,
    "src": null,
    "curr_hp": 1,
    "disabled": false,
    "endedTurn": true
  },
  {
    "id": 9,
    "type": "shape",
    "name": "Пешка",
    "shape": "custom",
    "color": "#006699",
    "x": 609.66,
    "y": 1051.45,
    "width": 40,
    "height": 40,
    "src": null,
    "curr_hp": 1,
    "disabled": false,
    "endedTurn": true
  },
  {
    "id": 10,
    "type": "shape",
    "name": "Колония",
    "shape": "custom",
    "color": "#930000",
    "x": 395.88,
    "y": 31.13,
    "width": 40,
    "height": 40,
    "src": null,
    "curr_hp": 1,
    "disabled": false,
    "endedTurn": false
  },
  {
    "id": 11,
    "type": "shape",
    "name": "Пешка",
    "shape": "custom",
    "color": "#930000",
    "x": 245.53,
    "y": 97.75,
    "width": 40,
    "height": 40,
    "src": null,
    "curr_hp": 1,
    "disabled": false,
    "endedTurn": false
  },
  {
    "id": 12,
    "type": "shape",
    "name": "Король",
    "shape": "custom",
    "color": "#930000",
    "x": 604.28,
    "y": 163.36,
    "width": 40,
    "height": 40,
    "src": null,
    "curr_hp": 1,
    "disabled": false,
    "endedTurn": false
  },
  {
    "id": 14,
    "type": "shape",
    "name": "Колония",
    "shape": "custom",
    "color": "#930000",
    "x": 174.86,
    "y": 30.09,
    "width": 40,
    "height": 40,
    "src": null,
    "curr_hp": 1,
    "disabled": false,
    "endedTurn": false
  },
  {
    "id": 15,
    "type": "shape",
    "name": "Пешка",
    "shape": "custom",
    "color": "#930000",
    "x": 246.72,
    "y": 30.37,
    "width": 40,
    "height": 40,
    "src": null,
    "curr_hp": 1,
    "disabled": false,
    "endedTurn": false
  },
  {
    "id": 16,
    "type": "shape",
    "name": "Пешка",
    "shape": "custom",
    "color": "#930000",
    "x": 395.94,
    "y": 94.82,
    "width": 40,
    "height": 40,
    "src": null,
    "curr_hp": 1,
    "disabled": false,
    "endedTurn": false
  },
  {
    "id": 17,
    "type": "shape",
    "name": "Пешка",
    "shape": "custom",
    "color": "#930000",
    "x": 536.98,
    "y": 30.39,
    "width": 40,
    "height": 40,
    "src": null,
    "curr_hp": 1,
    "disabled": false,
    "endedTurn": false
  },
  {
    "id": 18,
    "type": "shape",
    "name": "Колония",
    "shape": "custom",
    "color": "#d3d3d3",
    "x": 29.87,
    "y": 1320.23,
    "width": 40,
    "height": 40,
    "src": null,
    "curr_hp": 1,
    "disabled": false,
    "endedTurn": false
  },
  {
    "id": 19,
    "type": "shape",
    "name": "Колония",
    "shape": "custom",
    "color": "#d3d3d3",
    "x": 31.27,
    "y": 1392.67,
    "width": 40,
    "height": 40,
    "src": null,
    "curr_hp": 1,
    "disabled": false,
    "endedTurn": false
  },
  {
    "id": 20,
    "type": "shape",
    "name": "Ладья",
    "shape": "custom",
    "color": "#d3d3d3",
    "x": 110.36,
    "y": 1245.79,
    "width": 40,
    "height": 40,
    "src": null,
    "curr_hp": 1,
    "disabled": false,
    "endedTurn": true
  },
  {
    "id": 21,
    "type": "shape",
    "name": "Слон",
    "shape": "custom",
    "color": "#d3d3d3",
    "x": 245.76,
    "y": 1250.36,
    "width": 40,
    "height": 40,
    "src": null,
    "curr_hp": 1,
    "disabled": false,
    "endedTurn": true
  },
  {
    "id": 22,
    "type": "shape",
    "name": "Пешка",
    "shape": "custom",
    "color": "#d3d3d3",
    "x": 102.82,
    "y": 1387.09,
    "width": 40,
    "height": 40,
    "src": null,
    "curr_hp": 1,
    "disabled": false,
    "endedTurn": true
  },
  {
    "id": 23,
    "type": "shape",
    "name": "Пешка",
    "shape": "custom",
    "color": "#d3d3d3",
    "x": 84.32,
    "y": 1263.18,
    "width": 40,
    "height": 40,
    "src": null,
    "curr_hp": 1,
    "disabled": false,
    "endedTurn": true
  },
  {
    "id": 24,
    "type": "shape",
    "name": "Колония",
    "shape": "custom",
    "color": "#ff69b4",
    "x": 319.82,
    "y": 1789.08,
    "width": 40,
    "height": 40,
    "src": null,
    "curr_hp": 1,
    "disabled": false,
    "endedTurn": false,
    "title": "Мяфандия"
  },
  {
    "id": 25,
    "type": "shape",
    "name": "Колония",
    "shape": "custom",
    "color": "#006699",
    "x": 682.23,
    "y": 981.22,
    "width": 40,
    "height": 40,
    "src": null,
    "curr_hp": 1,
    "disabled": false,
    "endedTurn": false
  },
  {
    "id": 26,
    "type": "shape",
    "name": "Колония",
    "shape": "custom",
    "color": "#d3d3d3",
    "x": 179.73025488678437,
    "y": 1324.3017408631952,
    "width": 40,
    "height": 40,
    "src": null,
    "curr_hp": 1,
    "disabled": false,
    "endedTurn": false
  },
  {
    "id": 27,
    "type": "shape",
    "name": "Колония",
    "shape": "custom",
    "color": "#930000",
    "x": 323.23,
    "y": 97.75,
    "width": 40,
    "height": 40,
    "src": null,
    "curr_hp": 1,
    "disabled": false,
    "endedTurn": false
  },
  {
    "id": 28,
    "type": "shape",
    "name": "Пешка",
    "shape": "custom",
    "color": "#930000",
    "x": 463.71,
    "y": 98.51,
    "width": 40,
    "height": 40,
    "src": null,
    "curr_hp": 1,
    "disabled": false,
    "endedTurn": false
  },
  {
    "id": 29,
    "type": "shape",
    "name": "Колония",
    "shape": "custom",
    "color": "#640cff",
    "x": 32.7,
    "y": 223.28,
    "width": 40,
    "height": 40,
    "src": null,
    "curr_hp": 1,
    "disabled": false,
    "endedTurn": false,
    "title": "Роккенджима"
  },
  {
    "id": 30,
    "type": "shape",
    "name": "Пешка",
    "shape": "custom",
    "color": "#640cff",
    "x": 31.9,
    "y": 368.26,
    "width": 40,
    "height": 40,
    "src": null,
    "curr_hp": 1,
    "disabled": false,
    "endedTurn": true
  },
  {
    "id": 31,
    "type": "shape",
    "name": "Король",
    "shape": "custom",
    "color": "#640cff",
    "x": 175.79,
    "y": 231.99,
    "width": 40,
    "height": 40,
    "src": null,
    "curr_hp": 1,
    "disabled": false,
    "endedTurn": true
  },
  {
    "id": 32,
    "type": "shape",
    "name": "Колония",
    "shape": "custom",
    "color": "#006699",
    "x": 535.47,
    "y": 1256.63,
    "width": 40,
    "height": 40,
    "src": null,
    "curr_hp": 1,
    "disabled": false,
    "endedTurn": true
  },
  {
    "id": 33,
    "type": "shape",
    "name": "Пешка",
    "shape": "custom",
    "color": "#006699",
    "x": 753.8865549593719,
    "y": 1047.0585102952416,
    "width": 40,
    "height": 40,
    "src": null,
    "curr_hp": 1,
    "disabled": false,
    "endedTurn": true
  },
  {
    "id": 34,
    "type": "shape",
    "name": "Пешка",
    "shape": "custom",
    "color": "#006699",
    "x": 752.37,
    "y": 1187.39,
    "width": 40,
    "height": 40,
    "src": null,
    "curr_hp": 1,
    "disabled": false,
    "endedTurn": true
  },
  {
    "id": 35,
    "type": "shape",
    "name": "Пешка",
    "shape": "custom",
    "color": "#640cff",
    "x": 29.85,
    "y": 161.05,
    "width": 40,
    "height": 40,
    "src": null,
    "curr_hp": 1,
    "disabled": false,
    "endedTurn": true
  },
  {
    "id": 36,
    "type": "shape",
    "name": "Пешка",
    "shape": "custom",
    "color": "#ff69b4",
    "x": 316.35086136867585,
    "y": 1593.5932499337212,
    "width": 40,
    "height": 40,
    "src": null,
    "curr_hp": 1,
    "disabled": false,
    "endedTurn": true
  },
  {
    "id": 37,
    "type": "shape",
    "name": "Пешка",
    "shape": "custom",
    "color": "#ff69b4",
    "x": 313.5380723397607,
    "y": 1865.4961893955247,
    "width": 40,
    "height": 40,
    "src": null,
    "curr_hp": 1,
    "disabled": false,
    "endedTurn": true
  },
  {
    "id": 38,
    "type": "shape",
    "name": "Барьер",
    "shape": "custom",
    "color": "#d3d3d3",
    "x": 245.09353930282393,
    "y": 1184.8012443980442,
    "width": 40,
    "height": 40,
    "src": null,
    "curr_hp": 2,
    "disabled": false,
    "endedTurn": false
  },
  {
    "id": 39,
    "type": "shape",
    "name": "Барьер",
    "shape": "custom",
    "color": "#d3d3d3",
    "x": 319.16,
    "y": 1182.93,
    "width": 40,
    "height": 40,
    "src": null,
    "curr_hp": 2,
    "disabled": false,
    "endedTurn": false
  },
  {
    "id": 40,
    "type": "shape",
    "name": "Барьер",
    "shape": "custom",
    "color": "#d3d3d3",
    "x": 320.1,
    "y": 1250.43,
    "width": 40,
    "height": 40,
    "src": null,
    "curr_hp": 2,
    "disabled": false,
    "endedTurn": false
  },
  {
    "id": 41,
    "type": "shape",
    "name": "Пешка",
    "shape": "custom",
    "color": "#d3d3d3",
    "x": 321.04,
    "y": 1114.49,
    "width": 40,
    "height": 40,
    "src": null,
    "curr_hp": 1,
    "disabled": true,
    "endedTurn": true
  },
  {
    "id": 42,
    "type": "shape",
    "name": "Барьер",
    "shape": "custom",
    "color": "#d3d3d3",
    "x": 106.33,
    "y": 1455.77,
    "width": 40,
    "height": 40,
    "src": null,
    "curr_hp": 2,
    "disabled": false,
    "endedTurn": false
  },
  {
    "id": 43,
    "type": "shape",
    "name": "Барьер",
    "shape": "custom",
    "color": "#d3d3d3",
    "x": 33.2,
    "y": 1454.83,
    "width": 40,
    "height": 40,
    "src": null,
    "curr_hp": 2,
    "disabled": false,
    "endedTurn": false
  },
  {
    "id": 44,
    "type": "shape",
    "name": "Барьер",
    "shape": "custom",
    "color": "#d3d3d3",
    "x": 173.84,
    "y": 1458.58,
    "width": 40,
    "height": 40,
    "src": null,
    "curr_hp": 2,
    "disabled": false,
    "endedTurn": false
  }
]