CURRENT_TURN=6;
OTHER_SAVE_DATA={
  "scale": 1.0545062524167916,
  "canvasOffsetX": 72.39912549999997,
  "canvasOffsetY": 39.207250750000014,
  "shapeColor": "#640cff"
};
USER_RESOURCES={
  "Нейтралы": {},
  "Варвары": {},
  "Мамонты": {
    "Минералы": 11
  },
  "Нео": {
    "Минералы": 3
  },
  "Йод": {
    "Минералы": 12
  },
  "Онид": {
    "Минералы": 23
  },
  "Чайки": {
    "Минералы": 2
  }
};
OWNER_MAP={};
DEFAULT_DATA=[
  {
    "id": 1,
    "type": "shape",
    "name": "Колония",
    "shape": "custom",
    "color": "#006699",
    "x": 679.3,
    "y": 1116.2,
    "width": 40,
    "height": 40,
    "curr_hp": 1,
    "disabled": false,
    "endedTurn": false
  },
  {
    "id": 2,
    "type": "shape",
    "name": "Пешка",
    "shape": "custom",
    "color": "#006699",
    "x": 467.33,
    "y": 1252.54,
    "width": 40,
    "height": 40,
    "src": "",
    "curr_hp": 1,
    "disabled": false,
    "endedTurn": false,
    "title": "Пешка1"
  },
  {
    "id": 3,
    "type": "shape",
    "name": "Король",
    "shape": "custom",
    "color": "#006699",
    "x": 897.51,
    "y": 1054.04,
    "width": 40,
    "height": 40,
    "curr_hp": 1,
    "disabled": false,
    "endedTurn": false
  },
  {
    "id": 4,
    "type": "shape",
    "name": "Колония",
    "shape": "custom",
    "color": "#ff69b4",
    "x": 393.33,
    "y": 1653.12,
    "width": 40,
    "height": 40,
    "curr_hp": 1,
    "disabled": false,
    "endedTurn": false,
    "title": "Нэко-ворлд"
  },
  {
    "id": 5,
    "type": "shape",
    "name": "Пешка",
    "shape": "custom",
    "color": "#ff69b4",
    "x": 31.45,
    "y": 1801.82,
    "width": 40,
    "height": 40,
    "curr_hp": 1,
    "disabled": false,
    "endedTurn": true
  },
  {
    "id": 6,
    "type": "shape",
    "name": "Король",
    "shape": "custom",
    "color": "#ff69b4",
    "x": 823.49,
    "y": 1590.69,
    "width": 40,
    "height": 40,
    "curr_hp": 1,
    "disabled": false,
    "endedTurn": true
  },
  {
    "id": 8,
    "type": "shape",
    "name": "Пешка",
    "shape": "custom",
    "color": "#ff69b4",
    "x": 608.28,
    "y": 1869.44,
    "width": 40,
    "height": 40,
    "curr_hp": 1,
    "disabled": false,
    "endedTurn": true
  },
  {
    "id": 9,
    "type": "shape",
    "name": "Пешка",
    "shape": "custom",
    "color": "#006699",
    "x": 535.1,
    "y": 985.56,
    "width": 40,
    "height": 40,
    "curr_hp": 1,
    "disabled": false,
    "endedTurn": false
  },
  {
    "id": 10,
    "type": "shape",
    "name": "Колония",
    "shape": "custom",
    "color": "#930000",
    "x": 395.88,
    "y": 31.13,
    "width": 40,
    "height": 40,
    "curr_hp": 1,
    "disabled": false,
    "endedTurn": false
  },
  {
    "id": 12,
    "type": "shape",
    "name": "Король",
    "shape": "custom",
    "color": "#930000",
    "x": 535.01,
    "y": 300.05,
    "width": 40,
    "height": 40,
    "curr_hp": 1,
    "disabled": false,
    "endedTurn": false
  },
  {
    "id": 14,
    "type": "shape",
    "name": "Колония",
    "shape": "custom",
    "color": "#930000",
    "x": 174.86,
    "y": 30.09,
    "width": 40,
    "height": 40,
    "curr_hp": 1,
    "disabled": false,
    "endedTurn": false
  },
  {
    "id": 15,
    "type": "shape",
    "name": "Пешка",
    "shape": "custom",
    "color": "#930000",
    "x": 180.78,
    "y": 164.75,
    "width": 40,
    "height": 40,
    "curr_hp": 1,
    "disabled": false,
    "endedTurn": true
  },
  {
    "id": 16,
    "type": "shape",
    "name": "Пешка",
    "shape": "custom",
    "color": "#930000",
    "x": 320,
    "y": 235.8,
    "width": 40,
    "height": 40,
    "curr_hp": 1,
    "disabled": false,
    "endedTurn": false
  },
  {
    "id": 17,
    "type": "shape",
    "name": "Пешка",
    "shape": "custom",
    "color": "#930000",
    "x": 681.81,
    "y": 98.98,
    "width": 40,
    "height": 40,
    "curr_hp": 1,
    "disabled": false,
    "endedTurn": false
  },
  {
    "id": 18,
    "type": "shape",
    "name": "Колония",
    "shape": "custom",
    "color": "#d3d3d3",
    "x": 29.87,
    "y": 1320.23,
    "width": 40,
    "height": 40,
    "curr_hp": 1,
    "disabled": false,
    "endedTurn": false
  },
  {
    "id": 19,
    "type": "shape",
    "name": "Колония",
    "shape": "custom",
    "color": "#d3d3d3",
    "x": 31.27,
    "y": 1392.67,
    "width": 40,
    "height": 40,
    "curr_hp": 1,
    "disabled": false,
    "endedTurn": false
  },
  {
    "id": 20,
    "type": "shape",
    "name": "Ладья",
    "shape": "custom",
    "color": "#d3d3d3",
    "x": 177.96,
    "y": 1251,
    "width": 40,
    "height": 40,
    "curr_hp": 1,
    "disabled": false,
    "endedTurn": false
  },
  {
    "id": 21,
    "type": "shape",
    "name": "Слон",
    "shape": "custom",
    "color": "#d3d3d3",
    "x": 109.06,
    "y": 1388.76,
    "width": 40,
    "height": 40,
    "curr_hp": 1,
    "disabled": false,
    "endedTurn": false
  },
  {
    "id": 22,
    "type": "shape",
    "name": "Пешка",
    "shape": "custom",
    "color": "#d3d3d3",
    "x": 244.28,
    "y": 1388,
    "width": 40,
    "height": 40,
    "curr_hp": 1,
    "disabled": false,
    "endedTurn": false
  },
  {
    "id": 23,
    "type": "shape",
    "name": "Пешка",
    "shape": "custom",
    "color": "#d3d3d3",
    "x": 104.69,
    "y": 1184.22,
    "width": 40,
    "height": 40,
    "curr_hp": 1,
    "disabled": false,
    "endedTurn": false
  },
  {
    "id": 24,
    "type": "shape",
    "name": "Колония",
    "shape": "custom",
    "color": "#ff69b4",
    "x": 319.82,
    "y": 1789.08,
    "width": 40,
    "height": 40,
    "curr_hp": 1,
    "disabled": false,
    "endedTurn": false,
    "title": "Мяфандия"
  },
  {
    "id": 25,
    "type": "shape",
    "name": "Колония",
    "shape": "custom",
    "color": "#006699",
    "x": 682.23,
    "y": 981.22,
    "width": 40,
    "height": 40,
    "curr_hp": 1,
    "disabled": false,
    "endedTurn": false
  },
  {
    "id": 26,
    "type": "shape",
    "name": "Колония",
    "shape": "custom",
    "color": "#d3d3d3",
    "x": 179.73025488678437,
    "y": 1324.3017408631952,
    "width": 40,
    "height": 40,
    "curr_hp": 1,
    "disabled": false,
    "endedTurn": false
  },
  {
    "id": 27,
    "type": "shape",
    "name": "Колония",
    "shape": "custom",
    "color": "#930000",
    "x": 323.23,
    "y": 97.75,
    "width": 40,
    "height": 40,
    "curr_hp": 1,
    "disabled": false,
    "endedTurn": false
  },
  {
    "id": 28,
    "type": "shape",
    "name": "Пешка",
    "shape": "custom",
    "color": "#930000",
    "x": 608.25,
    "y": 164.91,
    "width": 40,
    "height": 40,
    "curr_hp": 1,
    "disabled": false,
    "endedTurn": false
  },
  {
    "id": 29,
    "type": "shape",
    "name": "Колония",
    "shape": "custom",
    "color": "#640cff",
    "x": 32.7,
    "y": 231.26,
    "width": 40,
    "height": 40,
    "curr_hp": 1,
    "disabled": false,
    "endedTurn": false,
    "title": "Роккенджима"
  },
  {
    "id": 30,
    "type": "shape",
    "name": "Пешка",
    "shape": "custom",
    "color": "#640cff",
    "x": 173.39,
    "y": 302.91,
    "width": 40,
    "height": 40,
    "curr_hp": 1,
    "disabled": false,
    "endedTurn": true
  },
  {
    "id": 31,
    "type": "shape",
    "name": "Король",
    "shape": "custom",
    "color": "#640cff",
    "x": 171.87,
    "y": 368.21,
    "width": 40,
    "height": 40,
    "curr_hp": 1,
    "disabled": false,
    "endedTurn": true
  },
  {
    "id": 32,
    "type": "shape",
    "name": "Колония",
    "shape": "custom",
    "color": "#006699",
    "x": 535.47,
    "y": 1256.63,
    "width": 40,
    "height": 40,
    "curr_hp": 1,
    "disabled": false,
    "endedTurn": false
  },
  {
    "id": 33,
    "type": "shape",
    "name": "Пешка",
    "shape": "custom",
    "color": "#006699",
    "x": 750.95,
    "y": 978.62,
    "width": 40,
    "height": 40,
    "curr_hp": 1,
    "disabled": false,
    "endedTurn": false,
    "title": "Пешка3"
  },
  {
    "id": 34,
    "type": "shape",
    "name": "Пешка",
    "shape": "custom",
    "color": "#006699",
    "x": 747.71,
    "y": 1320.98,
    "width": 40,
    "height": 40,
    "curr_hp": 1,
    "disabled": false,
    "endedTurn": false,
    "title": "Пешка4"
  },
  {
    "id": 36,
    "type": "shape",
    "name": "Пешка",
    "shape": "custom",
    "color": "#ff69b4",
    "x": 395.2,
    "y": 1530.55,
    "width": 40,
    "height": 40,
    "curr_hp": 1,
    "disabled": false,
    "endedTurn": false
  },
  {
    "id": 37,
    "type": "shape",
    "name": "Пешка",
    "shape": "custom",
    "color": "#ff69b4",
    "x": 319.05,
    "y": 1999.98,
    "width": 40,
    "height": 40,
    "curr_hp": 1,
    "disabled": false,
    "endedTurn": false
  },
  {
    "id": 38,
    "type": "shape",
    "name": "Барьер",
    "shape": "custom",
    "color": "#d3d3d3",
    "x": 321,
    "y": 1050.41,
    "width": 40,
    "height": 40,
    "curr_hp": 2,
    "disabled": false,
    "endedTurn": false
  },
  {
    "id": 39,
    "type": "shape",
    "name": "Барьер",
    "shape": "custom",
    "color": "#d3d3d3",
    "x": 319.16,
    "y": 1182.93,
    "width": 40,
    "height": 40,
    "curr_hp": 2,
    "disabled": false,
    "endedTurn": false
  },
  {
    "id": 40,
    "type": "shape",
    "name": "Барьер",
    "shape": "custom",
    "color": "#d3d3d3",
    "x": 320.1,
    "y": 1250.43,
    "width": 40,
    "height": 40,
    "curr_hp": 2,
    "disabled": false,
    "endedTurn": false
  },
  {
    "id": 41,
    "type": "shape",
    "name": "Пешка",
    "shape": "custom",
    "color": "#d3d3d3",
    "x": 246.21,
    "y": 1118.27,
    "width": 40,
    "height": 40,
    "curr_hp": 1,
    "disabled": false,
    "endedTurn": false
  },
  {
    "id": 42,
    "type": "shape",
    "name": "Барьер",
    "shape": "custom",
    "color": "#d3d3d3",
    "x": 106.33,
    "y": 1455.77,
    "width": 40,
    "height": 40,
    "curr_hp": 2,
    "disabled": false,
    "endedTurn": false
  },
  {
    "id": 43,
    "type": "shape",
    "name": "Барьер",
    "shape": "custom",
    "color": "#d3d3d3",
    "x": 33.2,
    "y": 1454.83,
    "width": 40,
    "height": 40,
    "curr_hp": 2,
    "disabled": false,
    "endedTurn": false
  },
  {
    "id": 44,
    "type": "shape",
    "name": "Барьер",
    "shape": "custom",
    "color": "#d3d3d3",
    "x": 173.84,
    "y": 1458.58,
    "width": 40,
    "height": 40,
    "curr_hp": 2,
    "disabled": false,
    "endedTurn": false
  },
  {
    "id": 45,
    "type": "shape",
    "name": "Колония",
    "shape": "custom",
    "color": "#930000",
    "x": 534.81,
    "y": 29.31,
    "width": 40,
    "height": 40,
    "curr_hp": 1,
    "disabled": false,
    "endedTurn": false
  },
  {
    "id": 46,
    "type": "shape",
    "name": "Пешка",
    "shape": "custom",
    "color": "#930000",
    "x": 105.39,
    "y": 96.06,
    "width": 40,
    "height": 40,
    "curr_hp": 1,
    "disabled": false,
    "endedTurn": true
  },
  {
    "id": 47,
    "type": "shape",
    "name": "Колония",
    "shape": "custom",
    "color": "#ff69b4",
    "x": 248.8,
    "y": 1520.64,
    "width": 40,
    "height": 40,
    "curr_hp": 1,
    "disabled": false,
    "endedTurn": false,
    "title": "Альфа-108"
  },
  {
    "id": 48,
    "type": "shape",
    "name": "Пешка",
    "shape": "custom",
    "color": "#ff69b4",
    "x": 319.34,
    "y": 1863.1,
    "width": 40,
    "height": 40,
    "curr_hp": 1,
    "disabled": false,
    "endedTurn": true
  },
  {
    "id": 49,
    "type": "shape",
    "name": "Колония",
    "shape": "custom",
    "color": "#006699",
    "x": 753.6163752310031,
    "y": 1116.988240336864,
    "width": 40,
    "height": 40,
    "curr_hp": 1,
    "disabled": false,
    "endedTurn": false
  },
  {
    "id": 50,
    "type": "shape",
    "name": "Колония",
    "shape": "custom",
    "color": "#d3d3d3",
    "x": 104.09,
    "y": 1115.63,
    "width": 40,
    "height": 40,
    "curr_hp": 1,
    "disabled": false,
    "endedTurn": false
  },
  {
    "id": 51,
    "type": "shape",
    "name": "Барьер",
    "shape": "custom",
    "color": "#d3d3d3",
    "x": 319.7532138966618,
    "y": 1324.499379986756,
    "width": 40,
    "height": 40,
    "curr_hp": 2,
    "disabled": false,
    "endedTurn": false
  },
  {
    "id": 52,
    "type": "shape",
    "name": "Барьер",
    "shape": "custom",
    "color": "#d3d3d3",
    "x": 320.6,
    "y": 1389.88,
    "width": 40,
    "height": 40,
    "curr_hp": 2,
    "disabled": false,
    "endedTurn": false
  },
  {
    "id": 53,
    "type": "shape",
    "name": "Барьер",
    "shape": "custom",
    "color": "#d3d3d3",
    "x": 318.06,
    "y": 1461.6,
    "width": 40,
    "height": 40,
    "curr_hp": 2,
    "disabled": false,
    "endedTurn": false
  },
  {
    "id": 55,
    "type": "shape",
    "name": "Колония",
    "shape": "custom",
    "color": "#d3d3d3",
    "x": 247.58,
    "y": 1254.03,
    "width": 40,
    "height": 40,
    "curr_hp": 1,
    "disabled": false,
    "endedTurn": false
  },
  {
    "id": 56,
    "type": "shape",
    "name": "Барьер",
    "shape": "custom",
    "color": "#d3d3d3",
    "x": 33.242897712423094,
    "y": 1050.630612162309,
    "width": 40,
    "height": 40,
    "curr_hp": 2,
    "disabled": false,
    "endedTurn": false
  },
  {
    "id": 57,
    "type": "shape",
    "name": "Барьер",
    "shape": "custom",
    "color": "#d3d3d3",
    "x": 104,
    "y": 1047.8,
    "width": 40,
    "height": 40,
    "curr_hp": 2,
    "disabled": false,
    "endedTurn": false
  },
  {
    "id": 58,
    "type": "shape",
    "name": "Барьер",
    "shape": "custom",
    "color": "#d3d3d3",
    "x": 176.64,
    "y": 1049.69,
    "width": 40,
    "height": 40,
    "curr_hp": 2,
    "disabled": false,
    "endedTurn": false
  },
  {
    "id": 59,
    "type": "shape",
    "name": "Колония",
    "shape": "custom",
    "color": "#930000",
    "x": 611.15,
    "y": 28.35,
    "width": 40,
    "height": 40,
    "curr_hp": 1,
    "disabled": false,
    "endedTurn": false
  },
  {
    "id": 60,
    "type": "shape",
    "name": "Пешка",
    "shape": "custom",
    "color": "#930000",
    "x": 250.25,
    "y": 232.69,
    "width": 40,
    "height": 40,
    "curr_hp": 1,
    "disabled": false,
    "endedTurn": true
  },
  {
    "id": 61,
    "type": "shape",
    "name": "Пешка",
    "shape": "custom",
    "color": "#930000",
    "x": 393.87,
    "y": 237.4,
    "width": 40,
    "height": 40,
    "curr_hp": 1,
    "disabled": false,
    "endedTurn": false
  },
  {
    "id": 62,
    "type": "shape",
    "name": "Пешка",
    "shape": "custom",
    "color": "#930000",
    "x": 749.39,
    "y": 97.99,
    "width": 40,
    "height": 40,
    "curr_hp": 1,
    "disabled": false,
    "endedTurn": false
  },
  {
    "id": 63,
    "type": "shape",
    "name": "Конь",
    "shape": "custom",
    "color": "#640cff",
    "x": 101.49,
    "y": 300.9,
    "width": 40,
    "height": 40,
    "curr_hp": 1,
    "disabled": false,
    "endedTurn": true
  },
  {
    "id": 64,
    "type": "shape",
    "name": "Конь",
    "shape": "custom",
    "color": "#640cff",
    "x": 103.46,
    "y": 231.18,
    "width": 40,
    "height": 40,
    "curr_hp": 1,
    "disabled": false,
    "endedTurn": false
  },
  {
    "id": 65,
    "type": "shape",
    "name": "Колония",
    "shape": "custom",
    "color": "#ff69b4",
    "x": 536.6,
    "y": 1799.27,
    "width": 40,
    "height": 40,
    "curr_hp": 1,
    "disabled": false,
    "endedTurn": false,
    "title": "Астра"
  },
  {
    "id": 66,
    "type": "shape",
    "name": "Пешка",
    "shape": "custom",
    "color": "#ff69b4",
    "x": 249.76,
    "y": 1727.26,
    "width": 40,
    "height": 40,
    "curr_hp": 1,
    "disabled": false,
    "endedTurn": true
  },
  {
    "id": 67,
    "type": "shape",
    "name": "Колония",
    "shape": "custom",
    "color": "#006699",
    "x": 608.53,
    "y": 983.28,
    "width": 40,
    "height": 40,
    "curr_hp": 1,
    "disabled": false,
    "endedTurn": false
  },
  {
    "id": 68,
    "type": "shape",
    "name": "Барьер",
    "shape": "custom",
    "color": "#d3d3d3",
    "x": 246.63,
    "y": 1456.85,
    "width": 40,
    "height": 40,
    "curr_hp": 2,
    "disabled": false,
    "endedTurn": false
  },
  {
    "id": 69,
    "type": "shape",
    "name": "Барьер",
    "shape": "custom",
    "color": "#d3d3d3",
    "x": 248.26,
    "y": 1048.64,
    "width": 40,
    "height": 40,
    "curr_hp": 2,
    "disabled": false,
    "endedTurn": false
  },
  {
    "id": 70,
    "type": "shape",
    "name": "Барьер",
    "shape": "custom",
    "color": "#d3d3d3",
    "x": 320.82,
    "y": 1119.75,
    "width": 40,
    "height": 40,
    "curr_hp": 2,
    "disabled": false,
    "endedTurn": false
  },
  {
    "id": 71,
    "type": "shape",
    "name": "Колония",
    "shape": "custom",
    "color": "#930000",
    "x": 610.25,
    "y": 233.74,
    "width": 40,
    "height": 40,
    "curr_hp": 1,
    "disabled": false,
    "endedTurn": false
  },
  {
    "id": 72,
    "type": "shape",
    "name": "Пешка",
    "shape": "custom",
    "color": "#930000",
    "x": 247.02663424401106,
    "y": 24.87061893001676,
    "width": 40,
    "height": 40,
    "curr_hp": 1,
    "disabled": false,
    "endedTurn": false
  },
  {
    "id": 73,
    "type": "shape",
    "name": "Пешка",
    "shape": "custom",
    "color": "#930000",
    "x": 248.15,
    "y": 100.22,
    "width": 40,
    "height": 40,
    "curr_hp": 1,
    "disabled": false,
    "endedTurn": false
  },
  {
    "id": 74,
    "type": "shape",
    "name": "Пешка",
    "shape": "custom",
    "color": "#930000",
    "x": 323.5,
    "y": 160.95,
    "width": 40,
    "height": 40,
    "curr_hp": 1,
    "disabled": false,
    "endedTurn": false
  },
  {
    "id": 75,
    "type": "shape",
    "name": "Пешка",
    "shape": "custom",
    "color": "#930000",
    "x": 389.85,
    "y": 167.7,
    "width": 40,
    "height": 40,
    "curr_hp": 1,
    "disabled": false,
    "endedTurn": false
  },
  {
    "id": 76,
    "type": "shape",
    "name": "Пешка",
    "shape": "custom",
    "color": "#930000",
    "x": 389.31,
    "y": 99.71,
    "width": 40,
    "height": 40,
    "curr_hp": 1,
    "disabled": false,
    "endedTurn": false
  },
  {
    "id": 77,
    "type": "shape",
    "name": "Колония",
    "shape": "custom",
    "color": "#ff69b4",
    "x": 174.79,
    "y": 1727.46,
    "width": 40,
    "height": 40,
    "curr_hp": 1,
    "disabled": false,
    "endedTurn": true,
    "title": "Тарандия"
  },
  {
    "id": 78,
    "type": "shape",
    "name": "Слон",
    "shape": "custom",
    "color": "#640cff",
    "x": 32.35,
    "y": 162.54,
    "width": 40,
    "height": 40,
    "curr_hp": 1,
    "disabled": false,
    "endedTurn": true
  }
]